### ISSUE TITLE
[proposal] refactor `metric-advisor` in koordlet as a framework with plugins

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#1001]
**What is your proposal**:
refactor `metric-advisor` in koordlet as a framework. 
Each collector should be a plugin.

**Why is this needed**:
For better extension.
Also in future, `koordlet` should support collector plugins calling prometheus exporters on node, parsing through [prometheus api](https://pkg.go.dev/github.com/prometheus/common@v0.39.0/expfmt).

**Is there a suggested solution, if so, please add it**:

**Comment by jasonliu747** [comment]
Nice!
