### ISSUE TITLE
[question] Fail to run colocation-of-spark-jobs example

### ISSUE THREAD

**Issue by yangjiajun2014** [koordinator-sh/koordinator#1004]
**What happened:**

I tried this example:https://koordinator.sh/zh-Hans/docs/best-practices/colocation-of-spark-jobs
But the job got error:

23/02/08 08:34:25 WARN TaskSetManager: Lost task 12057.0 in stage 372.0 (TID 178902) (172.16.0.127 executor 4): java.io.IOException: **No space left on device**
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(Unknown Source)
        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
        at java.base/java.io.BufferedOutputStream.write(Unknown Source)
        at java.base/java.io.DataOutputStream.writeLong(Unknown Source)
        at org.apache.spark.shuffle.IndexShuffleBlockResolver.$anonfun$writeMetadataFile$2(IndexShuffleBlockResolver.scala:448)
        at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:23)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofLong.foreach(ArrayOps.scala:258)
        at org.apache.spark.shuffle.IndexShuffleBlockResolver.$anonfun$writeMetadataFile$1(IndexShuffleBlockResolver.scala:448)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.shuffle.IndexShuffleBlockResolver.writeMetadataFile(IndexShuffleBlockResolver.scala:450)
        at org.apache.spark.shuffle.IndexShuffleBlockResolver.writeMetadataFileAndCommit(IndexShuffleBlockResolver.scala:379)
        at org.apache.spark.shuffle.sort.io.LocalDiskShuffleMapOutputWriter.commitAllPartitions(LocalDiskShuffleMapOutputWriter.java:119)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:71)
        at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**What you expected to happen:**
Run this example successfully.I think their should have options for spark tmp data store.Current example uses xxx/pods/xxx/volumes/kubernetes.io~empty-dir/spark-local-dir-1 to store some data in each node.

**Environment:**
- Koordinator version: - v1.1.1
- Kubernetes version (use kubectl version): v1.21.4
- docker/containerd version: docker 18.09.0

**Comment by jasonliu747** [comment]
Hi, can you provide us with your system specification? I think simply describing your node would work.

**Comment by yangjiajun2014** [comment]
> Hi, can you provide us with your system specification? I think simply describing your node would work.

Thanks for reply,I run 'kubectl describe node' and get:

Name:               xx.xx.xx.xx
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    cpu-feature.node.kubevirt.io/3dnow=true
                    cpu-feature.node.kubevirt.io/3dnowext=true
                    cpu-feature.node.kubevirt.io/abm=true
                    cpu-feature.node.kubevirt.io/acpi=true
                    cpu-feature.node.kubevirt.io/adx=true
                    cpu-feature.node.kubevirt.io/aes=true
                    cpu-feature.node.kubevirt.io/arat=true
                    cpu-feature.node.kubevirt.io/bmi1=true
                    cpu-feature.node.kubevirt.io/bmi2=true
                    cpu-feature.node.kubevirt.io/clflushopt=true
                    cpu-feature.node.kubevirt.io/clwb=true
                    cpu-feature.node.kubevirt.io/cr8legacy=true
                    cpu-feature.node.kubevirt.io/erms=true
                    cpu-feature.node.kubevirt.io/fsgsbase=true
                    cpu-feature.node.kubevirt.io/hypervisor=true
                    cpu-feature.node.kubevirt.io/la57=true
                    cpu-feature.node.kubevirt.io/mmxext=true
                    cpu-feature.node.kubevirt.io/monitor=true
                    cpu-feature.node.kubevirt.io/movbe=true
                    cpu-feature.node.kubevirt.io/mpx=true
                    cpu-feature.node.kubevirt.io/npt=true
                    cpu-feature.node.kubevirt.io/pclmuldq=true
                    cpu-feature.node.kubevirt.io/pcommit=true
                    cpu-feature.node.kubevirt.io/pdpe1gb=true
                    cpu-feature.node.kubevirt.io/pku=true
                    cpu-feature.node.kubevirt.io/popcnt=true
                    cpu-feature.node.kubevirt.io/rdrand=true
                    cpu-feature.node.kubevirt.io/rdtscp=true
                    cpu-feature.node.kubevirt.io/smap=true
                    cpu-feature.node.kubevirt.io/smep=true
                    cpu-feature.node.kubevirt.io/ss=true
                    cpu-feature.node.kubevirt.io/sse4.2=true
                    cpu-feature.node.kubevirt.io/sse4a=true
                    cpu-feature.node.kubevirt.io/svm=true
                    cpu-feature.node.kubevirt.io/svme-addr-chk=true
                    cpu-feature.node.kubevirt.io/xgetbv1=true
                    cpu-feature.node.kubevirt.io/xsave=true
                    cpu-feature.node.kubevirt.io/xsaveopt=true
                    cpu-model.node.kubevirt.io/Nehalem=true
                    cpu-model.node.kubevirt.io/Opteron_G1=true
                    cpu-model.node.kubevirt.io/Opteron_G2=true
                    cpu-model.node.kubevirt.io/Penryn=true
                    cpu-model.node.kubevirt.io/Westmere=true
                    cpu-vendor.node.kubevirt.io/AMD=true
                    cpumanager=false
                    failure-domain.beta.kubernetes.io/region=cn-east-204
                    failure-domain.beta.kubernetes.io/zone=cn-east-204a
                    host-model-cpu.node.kubevirt.io/EPYC=true
                    host-model-required-features.node.kubevirt.io/3dnow=true
                    host-model-required-features.node.kubevirt.io/3dnowext=true
                    host-model-required-features.node.kubevirt.io/acpi=true
                    host-model-required-features.node.kubevirt.io/clwb=true
                    host-model-required-features.node.kubevirt.io/erms=true
                    host-model-required-features.node.kubevirt.io/hypervisor=true
                    host-model-required-features.node.kubevirt.io/la57=true
                    host-model-required-features.node.kubevirt.io/monitor=true
                    host-model-required-features.node.kubevirt.io/mpx=true
                    host-model-required-features.node.kubevirt.io/npt=true
                    host-model-required-features.node.kubevirt.io/pcommit=true
                    host-model-required-features.node.kubevirt.io/pku=true
                    host-model-required-features.node.kubevirt.io/ss=true
                    host-model-required-features.node.kubevirt.io/svme-addr-chk=true
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=xx.xx.xx.xx
                    kubernetes.io/os=linux
                    kubevirt.io/schedulable=true
                    node.kubernetes.io/baremetal=false
                    node.kubernetes.io/container-engine=docker
                    node.kubernetes.io/subnetid=060b2f1a-1620-48a4-b756-9966dc766b7b
                    os.architecture=amd64
                    os.name=CentOS_Linux_7_Core
                    os.version=3.10.0-1160.25.1.el7.x86_64
                    topology.kubernetes.io/region=cn-east-204
                    topology.kubernetes.io/zone=cn-east-204a
Annotations:        alpha.kubernetes.io/provided-node-ip: xx.xx.xx.xx
                    csi.volume.kubernetes.io/nodeid:
                      {"disk.csi.everest.io":"274eb369-73fe-4281-b56d-3d365616afbe","local.csi.everest.io":"274eb369-73fe-4281-b56d-3d365616afbe","nas.csi.evere...
                    kubevirt.io/heartbeat: 2023-02-07T10:31:46Z
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 05 May 2022 15:23:58 +0800
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  xx.xx.xx.xx
  AcquireTime:     <unset>
  RenewTime:       Thu, 09 Feb 2023 17:19:29 +0800
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 09 Feb 2023 17:18:01 +0800   Thu, 05 May 2022 15:23:56 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 09 Feb 2023 17:18:01 +0800   Thu, 09 Feb 2023 14:17:53 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 09 Feb 2023 17:18:01 +0800   Thu, 05 May 2022 15:23:56 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Thu, 09 Feb 2023 17:18:01 +0800   Thu, 05 May 2022 15:24:12 +0800   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  xx.xx.xx.xx
  Hostname:    xx.xx.xx.xx
Capacity:
  cpu:                            8
  devices.kubevirt.io/kvm:        0
  devices.kubevirt.io/sev:        0
  devices.kubevirt.io/tun:        0
  devices.kubevirt.io/vhost-net:  0
  ephemeral-storage:              10186004Ki
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  kubernetes.io/batch-cpu:        4647
  kubernetes.io/batch-memory:     6772220887
  memory:                         16265188Ki
  pods:                           110
Allocatable:
  cpu:                            7910m
  devices.kubevirt.io/kvm:        0
  devices.kubevirt.io/sev:        0
  devices.kubevirt.io/tun:        0
  devices.kubevirt.io/vhost-net:  0
  ephemeral-storage:              9387421271
  hugepages-1Gi:                  0
  hugepages-2Mi:                  0
  kubernetes.io/batch-cpu:        4647
  kubernetes.io/batch-memory:     6772220887
  memory:                         13749220Ki
  pods:                           110
System Info:
  Machine ID:                 274eb369-73fe-4281-b56d-3d365616afbe
  System UUID:                274EB369-73FE-4281-B56D-3D365616AFBE
  Boot ID:                    38b89e7d-6a15-449c-9bf3-d07351974d0f
  Kernel Version:             3.10.0-1160.25.1.el7.x86_64
  OS Image:                   CentOS Linux 7 (Core)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://18.9.0
  Kubelet Version:            v1.21.7-r0-CCE21.11.1.B007
  Kube-Proxy Version:         v1.21.7-r0-CCE21.11.1.B007
ProviderID:                   13faa75c-cc44-11ec-8eb5-0255ac1000b0
Non-terminated Pods:          (5 in total)
  Namespace                   Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                                       ------------  ----------  ---------------  -------------  ---
  koordinator-system          koord-manager-5f569c8fb6-dgkp9             500m (6%)     1 (12%)     256Mi (1%)       1Gi (7%)       2d
  koordinator-system          koordlet-f54c5                             0 (0%)        500m (6%)   0 (0%)           256Mi (1%)     178m
  kube-system                 coredns-7b58d985cb-v86vx                   500m (6%)     500m (6%)   512Mi (3%)       512Mi (3%)     280d
  kube-system                 everest-csi-controller-5cccf6f66b-fqdww    250m (3%)     250m (3%)   600Mi (4%)       1500Mi (11%)   280d
  kube-system                 everest-csi-driver-64n9s                   200m (2%)     200m (2%)   600Mi (4%)       600Mi (4%)     280d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests      Limits
  --------                       --------      ------
  cpu                            1450m (18%)   2450m (30%)
  memory                         1968Mi (14%)  3892Mi (28%)
  ephemeral-storage              0 (0%)        0 (0%)
  hugepages-1Gi                  0 (0%)        0 (0%)
  hugepages-2Mi                  0 (0%)        0 (0%)
  devices.kubevirt.io/kvm        0             0
  devices.kubevirt.io/sev        0             0
  devices.kubevirt.io/tun        0             0
  devices.kubevirt.io/vhost-net  0             0
  kubernetes.io/batch-cpu        0             0
  kubernetes.io/batch-memory     0             0
Events:                          <none>

**Comment by zwzhang0107** [comment]
> java.io.IOException: No space left on device
it seems that some resource of your environment runs out, which might be fd or disk space.

**Comment by yangjiajun2014** [comment]
> > java.io.IOException: No space left on device
> 
> it seems that some resource of your environment runs out, which might be fd or disk space.

Thanks for u reply.Yes,this example writes more than 10G data to k8s default store(/mnt/paas/kubernetes/kubelet/xxx) in my environment.I only have 9.8G in this path so I want option to change store location of tmp data.

**Comment by zwzhang0107** [comment]
> Thanks for u reply.Yes,this example writes more than 10G data to k8s default store(/mnt/paas/kubernetes/kubelet/xxx) in my environment.I only have 9.8G in this path so I want option to change store location of tmp data.

Glad to hear that!
We will close this issue and if there is any new problem, please create a new issue and let us know.
