### ISSUE TITLE
[question] 支持CRD资源的调度吗?

### ISSUE THREAD

**Issue by 249805118** [koordinator-sh/koordinator#1005]
What happened:
生产中的计算任务都是根据Argo workflow来编排的。希望了解下Elastic Quota支持这种crd资源的调度吗？workflow不会在pod的lables和annotations中增加自定义的标签。
What you expected to happen:
支持crd资源的调度，而不是单单通过pod调度
Environment:
最新版本

**Comment by eahydra** [comment]
不太会考虑支持CRD的调度。Argo Workflow会触发创建Pod的吧？如果是的话，应该是可以给Pod增加 annotation/label的。

**Comment by 249805118** [comment]
好的，谢谢啦
