### ISSUE TITLE
[memory collect] memory usage calculate 

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#1016]
why calculate memory usage by `total_inactive_anon + total_active_anon + total_unevictable`, how about `memory.usage_in_bytes`

https://github.com/koordinator-sh/koordinator/blob/ddf7ad0f777aacbfdefc0e1b156685a7dc29908b/pkg/koordlet/util/system/cgroup.go#L66

**What happened:**
we got many zombie memory cgroups, memory usage calculated by `total_inactive_anon + total_active_anon + total_unevictable`（9GiB） is more than `memory.usage_in_bytes`(600MiB)。

**What you expected to happen:**

**Environment:**

- Koordinator version: - v1.0.0
- Kernel (e.g. uname -a): 4.19.91

**Anything else we need to know:**

**Comment by zwzhang0107** [comment]
memory.usage_in_bytes includes cache and buffer, which can be reclaimed by kernel.
why there are many zombie memory cgroups? maybe it is better to solve the root cause of cgroups leaks first.

**Comment by j4ckstraw** [comment]
> /area koordlet
> 
> @j4ckstraw `memory.usage_in_bytes` is a fuzz value for efficient access. The koordlet prefers to know which part of memory is exactly in use and not reclaimable.
> 
> > https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
> > 
> > * 5.5 usage_in_bytes
> >   For efficiency, as other kernel components, memory cgroup uses some optimization to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz value for efficient access. (Of course, when necessary, it's synchronized.) If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in memory.stat(see 5.2).
> 
> As for the zombie memory accounting, could you please show the content of `memory.stat` for more details?

Got it. thx

**Comment by j4ckstraw** [comment]
> memory.usage_in_bytes includes cache and buffer, which can be reclaimed by kernel. why there are many zombie memory cgroups? maybe it is better to solve the root cause of cgroups leaks first.

someone create and delete cgroup frequently, and I don't think the kernel handled it correctly.

**Comment by j4ckstraw** [comment]
> /area koordlet
> 
> @j4ckstraw `memory.usage_in_bytes` is a fuzz value for efficient access. The koordlet prefers to know which part of memory is exactly in use and not reclaimable.
> 
> > https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt
> > 
> > * 5.5 usage_in_bytes
> >   For efficiency, as other kernel components, memory cgroup uses some optimization to avoid unnecessary cacheline false sharing. usage_in_bytes is affected by the method and doesn't show 'exact' value of memory (and swap) usage, it's a fuzz value for efficient access. (Of course, when necessary, it's synchronized.) If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in memory.stat(see 5.2).
> 
> As for the zombie memory accounting, could you please show the content of `memory.stat` for more details?

```bash
# cat /proc/cgroups
#subsys_name    hierarchy       num_cgroups     enabled
cpuset  7       94      1
cpu     3       95      1
cpuacct 3       95      1
blkio   12      92      1
memory  11      11105   1
devices 10      92      1
freezer 8       92      1
net_cls 2       92      1
perf_event      4       92      1
net_prio        2       92      1
hugetlb 9       92      1
pids    6       92      1
rdma    5       1       1

# cat memory.stat
cache 0
rss 0
rss_huge 0
shmem 0
mapped_file 0
dirty 0
writeback 0
swap 0
workingset_refault_anon 0
workingset_refault_file 0
workingset_activate_anon 0
workingset_activate_file 0
workingset_restore_anon 0
workingset_restore_file 0
workingset_nodereclaim 0
pgpgin 0
pgpgout 0
pgfault 0
pgmajfault 0
inactive_anon 0
active_anon 0
inactive_file 0
active_file 0
unevictable 0
hierarchical_memory_limit 9223372036854771712
hierarchical_memsw_limit 9223372036854771712
total_cache 0
total_rss 2300289024
total_rss_huge 0
total_shmem 0
total_mapped_file 0
total_dirty 12840960
total_writeback 135168
total_swap 0
total_workingset_refault_anon 0
total_workingset_refault_file 17363836928
total_workingset_activate_anon 0
total_workingset_activate_file 9502507008
total_workingset_restore_anon 0
total_workingset_restore_file 7980331008
total_workingset_nodereclaim 0
total_pgpgin 110984069775
total_pgpgout 110985063330
total_pgfault 198018798757
total_pgmajfault 280888
total_inactive_anon 4906328064
total_active_anon 1486848
total_inactive_file 0
total_active_file 128274432
total_unevictable 0

# cat memory.usage_in_bytes
885968896
```

**Comment by zwzhang0107** [comment]
> memory.usage_in_bytes is 844MiB, while total_inactive_anon + total_active_anon + total_unevictable is 4680MiB.

which one is more accurate, maybe the `` since the cgroup is still unreleased.

could the `reap_background` can solve the zombie problem for you?
https://openanolis.cn/sig/Cloud-Kernel/doc/659601505054416682

**Comment by wenjianhn** [comment]
> could the `reap_background` can solve the zombie problem for you?
> https://openanolis.cn/sig/Cloud-Kernel/doc/659601505054416682

@zwzhang0107, No. kmem accounting is enabled in our prod env.
`reap_background` is not able to reclaim slab caches of a dying mem cgroup.

memory.force_empty is used as workround at the moment.
Without it we are likely to hit the following [issue](https://lore.kernel.org/linux-mm/YpXD12Qa51%2F5EUdy@FVFYT0MHHV2J.usts.net/T/#m1c430eaeddbc196242421e0736fd4a5c7730ace5) even if kmem account is disabled:
```txt
But user memory allocations (LRU pages) pinning memcgs for a long time -
it exists at a larger scale and is causing recurring problems in the real
world: page cache doesn't get reclaimed for a long time, or is used by the
second, third, fourth, ... instance of the same job that was restarted into
a new cgroup every time. Unreclaimable dying cgroups pile up, waste memory,
and make page reclaim very inefficient.
```

**Comment by zwzhang0107** [comment]
> env

Since the memory could not be used by others, I think it should be take account until it's released for memory calculation.

zombie/dirty memcg is another topic, it should be solved by other options. I recommend `reap_background` for zombie and `water_mark.ratio` for cache.
