### ISSUE TITLE
REQUEST: New membership for <chzhj>

### ISSUE THREAD

**Issue by chzhj** [koordinator-sh/koordinator#1031]
### GitHub Username

chzhj

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@hormes

### Sponsor 2

@zwzhang0107

### List of contributions to the Koordinator project

PRs Reviewed / authored

https://github.com/koordinator-sh/koordinator/pull/305
https://github.com/koordinator-sh/koordinator/pull/1006
https://github.com/koordinator-sh/koordinator/pull/1020

Subprojects I am involved with

koordinator-sh/koordinator

**Comment by hormes** [comment]
+1

**Comment by hormes** [comment]
Welcome to the Koordinator community! We are excited to have you onboard as we work together to make workload 
 scheduling more efficient and flexible.

**Comment by zwzhang0107** [comment]
+1

**Comment by FillZpp** [comment]
@chzhj  Congratulations! We have sent a github message to invite you as member of Koordinator, please check the message.

After joining the member, please keep **role: public** in https://github.com/orgs/koordinator-sh/people, so correct member statics can be collected by community.
