### ISSUE TITLE
[proposal]Koordlet  frequent  restarts when CPI PSI monitoring is enabled due to high memory usage

### ISSUE THREAD

**Issue by Re-Grh** [koordinator-sh/koordinator#1046]
**What is your proposal**:
When the psi cpi function is enabled, the koordlet container uses memory to maintain around 240mb, which is prone to trigger the 256mb limit and cause oom and pod restart problems, as shown in the figure below.

![image](https://lh3.googleusercontent.com/k6RpBuO7q7vFQJ3uBZZzrIKnvmbovgw0xehFc2ufplr4Pwb9a7QIJzFJZTI4i4w4xR92FSC57KoVaiDM1ytuIUpyF-JzPeJUVe97Y78_cMyNnQ7bOqLXmomASwO6JvVw5i1boggOGP85P_TE_WfDa4uslXTWs5FKSgXHeOc8VksiWc8xZDgyEXWSP6zivKzlzcs-XmJK6Eyi-F-f5W5IcLgbcnYP5MRR7OG7rOvkgprr4KadbYZ7VIaRZo0YUMqVo8Rs-xTDghREphenNVOSqIaMCZljiJ7Zwcy7wvS1236mRk23unqiD3Mk5M4xYtpRSFHV2CSS1ovYmdGMQBlDF4tfys-yUAncM0n4utQBbEQFFaxkcL-Xbq0mbFM2TTSwnSyVzr7yNJFWayjdX16fFTdBD0X79FCuo_5WrQNmZHomtrhgXijn-t_0DNt2NIoxSfM5ZQIim8llsBbjwmg8f_0u2eCGpP9MAczR2rhKsq0voXsi21VEUGrUzo9d5QEeE8UBNWbhXuhvVJO04hQMGD_aqYm5GTnNITmAD29lVSuidfja1mx48zCQwWACANkBnJaaiTzrp-SzGB8TIk8mPhoEgP89FsQNOGQ6YpY4hB_u_b-94jeNlKCnPwQIRyoDteh63gzvFLQ2VqZYOwI6F_sO1mEmvUS4qYjnRktVZ91UuLxlGhlUdkGlaX2wu2ORzYQt78DvAMs1016yTn-d83xJP61isj0sN1AZWw0DExLBzR0YNl9x17QZUy279PzqDW6x7lTyr8GE94dgFbpfqc6OZ7Ik0l7XInh0rGl5w6Q0ir5Y8UGcoE_6Lq3IBK1OmtEg8F2wD8FLYRDIahMWMujz5V22p9Gno5vGQek-ToT3HlFXH8KfBjl_LCp3h8ayj3bysbKx9_bFowxM9Y_C3ygY3N0zqsSB2s3A7J2T_l_1BJRf=w1336-h290-no?authuser=0)
**Why is this needed**:
To improve the stability of the koodlet and reduce the overhead of metric collection

**Is there a suggested solution, if so, please add it**:
Maybe can use Golang's memory profiling tools and increase the frequency of garbage collection.

**Comment by maaoBit** [comment]
Enable CPI PSI, and test in one node cluster
```
 ~ kubectl get node -o wide
NAME       STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
maao-dev   Ready    control-plane   11d   v1.24.2   192.168.2.2   <none>        Ubuntu 20.04.4 LTS   5.15.0-60-generic   containerd://1.6.18
 ~ kubectl get po -A | wc -l
104
~ kubectl get po -n koordinator-system koordlet-vq6bg -o yaml | grep CPI
    - -feature-gates=BECPUEvict=true,BEMemoryEvict=true,CgroupReconcile=true,Accelerators=true,PSICollector=true,CPICollector=true
```
<img width="1372" alt="Pasted image 20230306110542" src="https://user-images.githubusercontent.com/4652520/223308999-3aa24d41-2345-4992-89be-64441be39151.png">

The container used about 260MB memory, but `go_memstats_alloc_bytes` is always below 50MB. It seems that most of the memory is used by sqlite3 (cgo). As per this, reducing `GOGC` does not reduce memory usage much.

When set `metric-expire-seconds=900`(default 1800), container memory usage drops to around 160MB.
![Pasted image 20230306164704](https://user-images.githubusercontent.com/4652520/223310895-5e9f1850-1681-4c7c-9e60-9c19ca5ac0bc.png)

Does the modification of `metric-expire-seconds` affect other modules which use metric_cache? In addition, does sqlite3 have memory leaks?  There seem to be related [issue](https://github.com/go-gorm/sqlite/issues/128) reports.

**Comment by Re-Grh** [comment]
Thank you for your reply. For now, the memory usage statistics of Golang after enabling the feature are not large, and the oom issue may be related to the memory usage of cgo's SQLite3. Although there are few oom situations in other components of Koordlet, replacing the database with TSDB is indeed under consideration, and with the use of TSDB in the future, the memory issue in this issue could be resolved.The issue link for the previous metric_cache refactoring plan is here：https://github.com/koordinator-sh/koordinator/issues/586

**Comment by songtao98** [comment]
> Enable CPI PSI, and test in one node cluster
> 
> ```
>  ~ kubectl get node -o wide
> NAME       STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
> maao-dev   Ready    control-plane   11d   v1.24.2   192.168.2.2   <none>        Ubuntu 20.04.4 LTS   5.15.0-60-generic   containerd://1.6.18
>  ~ kubectl get po -A | wc -l
> 104
> ~ kubectl get po -n koordinator-system koordlet-vq6bg -o yaml | grep CPI
>     - -feature-gates=BECPUEvict=true,BEMemoryEvict=true,CgroupReconcile=true,Accelerators=true,PSICollector=true,CPICollector=true
> ```
> 
> <img alt="Pasted image 20230306110542" width="1372" src="https://user-images.githubusercontent.com/4652520/223308999-3aa24d41-2345-4992-89be-64441be39151.png">
> 
> The container used about 260MB memory, but `go_memstats_alloc_bytes` is always below 50MB. It seems that most of the memory is used by sqlite3 (cgo). As per this, reducing `GOGC` does not reduce memory usage much.
> 
> When set `metric-expire-seconds=900`(default 1800), container memory usage drops to around 160MB. ![Pasted image 20230306164704](https://user-images.githubusercontent.com/4652520/223310895-5e9f1850-1681-4c7c-9e60-9c19ca5ac0bc.png)
> 
> Does the modification of `metric-expire-seconds` affect other modules which use metric_cache? In addition, does sqlite3 have memory leaks? There seem to be related [issue](https://github.com/go-gorm/sqlite/issues/128) reports.

@maaoBit Thanks for your contribution for testing possible memory leak in CPI and PSI collectors! The opnion about sqlite3 is quite useful and we will pay more attention on it such as replace it with TSDB. 

However, when this problem first occurred, I was wondering if it is an accessible and reasonable memory usage lift which simply caused by new collector. So I did some observations to see if set a higher memory limit can solve the OOM problem. The fact is that over a long period of time(3-4 days), the memory usage remains stable for a few hours, then starts to increase, and so on. This really shocks me. 
![image](https://user-images.githubusercontent.com/110808397/223342957-76772e5a-0e84-4952-8e62-7bb300639390.png)


Could you give it a longer observe to see if the same phenomenon happens? I hope the way I did my evaluation is wrong and there is no other problems in the source code that leads to memory leak.

**Comment by maaoBit** [comment]
OK, I'll keep watching for a few days.
