### ISSUE TITLE
[proposal] koord-scheduler needs to support that Pod can only use resources of Reservation

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1087]
**What is your proposal**:

The current implementation of koord-scheduler is that Pod allocates resources on nodes with Reservation as much as possible (assuming there are available Reservations), but sometimes it is possible to use other nodes that do not have reserved resources. But there are also some cases where the Pod should only use the resources of the Reservation.

**Why is this needed**:

The cluster administrator will reserve resources for some applications or users in advance, and the remaining resources will continue to be reserved for other users. The purpose of this is to manage resources more finely.

**Is there a suggested solution, if so, please add it**:

1. Maybe we should define a new API for Reservation to help the scheduler decide whether to filter nodes without Reservations.
2. In PreFilter, check whether the Pod has a Reservation, if not, abort scheduling.
3. In Filter, if the node has no Reservation, skip it.

**Comment by eahydra** [comment]
cc @hormes @FillZpp @saintube @ZiMengSheng

**Comment by saintube** [comment]
@eahydra Is this an attribute of the reservation or of the pod?
