### ISSUE TITLE
[question] runtime-hooks: disable standalone mode when use proxy mode

### ISSUE THREAD

**Issue by maaoBit** [koordinator-sh/koordinator#1094]
**What happened:**
https://github.com/koordinator-sh/koordinator/blob/main/docs/design-archive/koordlet-runtime-hooks.md#working-mode
When runtime-proxy is installed and the proxy mode is used, it seems that the standalone mode will still run and do repeated work. Is there any way to turn off standalone mode when using proxy mode？

**What you expected to happen:**
There is a flag of koordlet to turn off the standalone mode.

**Environment:**

- Koordinator version: - v1.1.1
- Kubernetes version (use kubectl version): v1.24.2
- docker/containerd version: containerd 1.6.18
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by zwzhang0107** [comment]
Standalone mode is still necessary since the cgroup files in kubepods/ dir still needs to be reconciled, which also for the final  consistency.
Is there any problems to both run the reconciler and the proxy mode?

**Comment by maaoBit** [comment]
emm... I ignored kubeqos level by mistake. It made me think that proxy mode and standalone mode are exactly the same in function. Thanks @zwzhang0107 for the clarification.
