### ISSUE TITLE
[proposal] Support Colocation of Flink Jobs

### ISSUE THREAD

**Issue by kaori-seasons** [koordinator-sh/koordinator#1110]
Hi, community. After reading the community's documentation,Refer to the Spark-type big data task implementation mechanism. If the workloads in the existing cluster want to coexist through Koordinator, you need to modify the existing Controller/Operator to support Koordinator definition Protocols such as QoS class, priority and resource model. So if we need to support Koordniator for Flink’s cluster hosting tasks, do we need to do the following: 
- 1. Write ```cluster-colocation-profile.yaml``` to complete the injection of Koordinator QoS, Resources like Koordinator Priority
- 2. Due to the current business scenarios of our company, 50% are flink streaming tasks, and the other 50% are flink batch processing tasks. only four levels of koord-prod, koord-mid, koord-batch, and koord-free are supported in the priority types currently supported by koordinator. It seems that I should Introduce a new ```koord-stream``` type and test it.

The current planning mode of Flink on kubernetes is ```Native Application``` or ```Application```. Since I am currently in the stage of learning Koordinator, I have some questions about resource priority allocation for flink streaming tasks. Can you give me some advice? @eahydra

**What is your proposal**:

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by eahydra** [comment]
Hi @complone, if 50% of the flink jobs are batch tasks, you can try to use Koordinator for colocation. Inject Koordinator's QoS protocol through ClusterColocationProfile. As for the priority, of course, you can define it yourself, but currently Koordinator restricts some priority segments. For example, koord-prod refers to the priority range >= 9000 && <= 9999. See https://koordinator.sh/docs/architecture/priority for specific definitions

**Comment by eahydra** [comment]
The streaming computing framework of Flink consumes more resources. In order to ensure availability and runtime effects, you can consider enabling the LeastAllocated scoring strategy in the resource allocation dimension, and combine [LoadAware Scheduling](https://koordinator.sh/docs/user-manuals/load-aware-scheduling) to complete load balancing.

**Comment by hormes** [comment]
In generally, try to run batch jobs in a collocation mode(by ClusterColocationProfile) with a safe water level, and then try to gradually increase the [water level configuration](https://koordinator.sh/docs/user-manuals/cpu-suppress) of a single node and run more jobs.

**Comment by complone** [comment]
@eahydra  @hormes  Thank you both for your replies, I will do some research in the near future
