### ISSUE TITLE
[proposal]How to avoid A evicted pod is scheduled to the node, which is  just evicted a pod 。

### ISSUE THREAD

**Issue by gj199575** [koordinator-sh/koordinator#1114]
How to avoid A evicted pod is scheduled to the node, which is  just evicted a pod 。

**Comment by jasonliu747** [comment]
如何避免将Pod调度到刚刚发生驱逐事件的节点上

@gj199575 这样理解对吗

**Comment by gj199575** [comment]
> 如何避免将Pod调度到刚刚发生驱逐事件的节点上
> 
> @gj199575 这样理解对吗

yep

**Comment by KunWuLuan** [comment]
If the evicted pod is scheduled to the node, it means the node become the best node again.
Maybe we should change the plugin args in this situation?
