### ISSUE TITLE
[proposal] compatible with PodGroup new label key

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1157]
**What is your proposal**:

https://github.com/kubernetes-sigs/scheduler-plugins/commit/23e980c0e53bcbdaf08c9ae142f09fb0f92ee71b updates the PodGroup label key  `scheduling.x-k8s.io/pod-group: pg1`, we should compatible it.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by lvxian-kjl** [comment]
This appears unfinished—do we have a plan to support the new PodGroup label key later?
