### ISSUE TITLE
[BUG] failed to calculate node topology

### ISSUE THREAD

**Issue by dykhliww** [koordinator-sh/koordinator#1201]
**What happened**:

#kubectl describe pod XXX

Events:
  Type     Reason            Age   From             Message
  Warning  FailedScheduling  23s   koord-scheduler  0/5 nodes are available: 2 node(s) invalid CPU Topology, 3 node(s) had taint {dedicated: master}, that the pod didn't tolerate.

#kubectl logs koordlet-2zx2f -nkoordinator-system

I0410 14:25:26.458142   11700 states_noderesourcetopology.go:295] start to report node topology
E0410 14:25:26.463152   11700 states_noderesourcetopology.go:306] failed to calculate node topology, err: failed to GetKubeletConfiguration, err: request http://xx.xx.xx.xx:10255/configz failed, code 404

How to solve 404？

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: v1.1.1
- Kubernetes version (use `kubectl version`): v1.21.3
- Install details (e.g. helm install args):  - --kubelet-insecure-tls=true
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
It seems the kubelet config is not exported at `:10255/configz`. However, it is not required. Please try to add the `-disable-query-kubelet-config=true` in the args of the koordlet DaemonSet.

**Comment by dykhliww** [comment]
Thanks, I have got it.
