### ISSUE TITLE
[BUG] Qos and resource not match

### ISSUE THREAD

**Issue by dykhliww** [koordinator-sh/koordinator#1207]
**What happened**:
有如下设置：
metadata:
   .....
   koordinator.sh/qosClass: BE
spec:
    .....
    resources:
      limits:
        cpu: "1"
        memory: 1G
      requests:
        cpu: "1"
        memory: 1G

K8s regard it as guaranteed, but koordinator regard it as BE，there is conflict.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: v1.1.1
- Kubernetes version (use `kubectl version`):  v1.21.3
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by zwzhang0107** [comment]
BE pods should set with batch-cpu and batch-memory, and we recommend to use colocation-profile.
https://koordinator.sh/docs/user-manuals/colocation-profile/

**Comment by zwzhang0107** [comment]
i'll close this issue.
you and reopen this issue and let us known if there is any more problem.
