### ISSUE TITLE
[BUG] The update frequency of NodeResourceTopology CR is still high

### ISSUE THREAD

**Issue by wangxiaoq** [koordinator-sh/koordinator#1219]
**What happened**:

Issue https://github.com/koordinator-sh/koordinator/issues/817 point that koordlet should not update the NodeResourceTopology if it is the same as the previous one.

But after this bug has been fixed in https://github.com/koordinator-sh/koordinator/pull/893, I found the NodeResourceTopology requests frequency is still high.

After add some logs in koordlet, I found the reason. `node.koordinator.sh/pod-cpu-allocs` annotation in NodeResourceTopology is considered different between current one and the previous one even they are same. For example:

the previous one:
```
[map[cpuset:48 managedByKubelet:true name:nginx-deployment-66f7c4b554-ndqml namespace:iks-ns-bigdata-cloud-prod uid:9ee55b28-5ad9-44eb-9ef3-161074a29f2b] map[cpuset:1-2,49-50 managedByKubelet:true name:kruise-rollout-controller-manager-65dbdd8b77-9jg27 namespace:kruise-rollout uid:f738817e-50ae-4fbc-a2b4-5b5f0a8b339f] map[cpuset:11-12,59-60 managedByKubelet:true name:iks-resource-holder-c4m0-5d8b7bd474-9b86d namespace:default uid:5015049d-40c4-4946-af12-56beff18a042] map[cpuset:3-4,51-52 managedByKubelet:true name:kruise-rollout-controller-manager-65dbdd8b77-jbfwr namespace:kruise-rollout uid:84ed7389-cffb-4e05-be5c-e942026d19e8]]
```

the current one:

```
[map[cpuset:11-12,59-60 managedByKubelet:true name:iks-resource-holder-c4m0-5d8b7bd474-9b86d namespace:default uid:5015049d-40c4-4946-af12-56beff18a042] map[cpuset:3-4,51-52 managedByKubelet:true name:kruise-rollout-controller-manager-65dbdd8b77-jbfwr namespace:kruise-rollout uid:84ed7389-cffb-4e05-be5c-e942026d19e8] map[cpuset:48 managedByKubelet:true name:nginx-deployment-66f7c4b554-ndqml namespace:iks-ns-bigdata-cloud-prod uid:9ee55b28-5ad9-44eb-9ef3-161074a29f2b] map[cpuset:1-2,49-50 managedByKubelet:true name:kruise-rollout-controller-manager-65dbdd8b77-9jg27 namespace:kruise-rollout uid:f738817e-50ae-4fbc-a2b4-5b5f0a8b339f]]
```

They are considered different just because the elements in the two slices order are not same.

**What you expected to happen**:

Do not effected by the elements order in  `node.koordinator.sh/pod-cpu-allocs` annotation slice

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: 1.1.1
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by zwzhang0107** [comment]
i think maybe it should be compared with formatted.
