### ISSUE TITLE
[proposal] CI should fail if diff coverage is below 70%

### ISSUE THREAD

**Issue by jasonliu747** [koordinator-sh/koordinator#124]
**Why is this needed**:
Diff coverage is the percentage of new or modified lines that are covered by tests. This provides a clear and achievable standard for code review: If you touch a line of code, that line should be covered. 

Code coverage is every developer's responsibility!

So, I think CI should fail if diff coverage is below 70% or something else. 

**Is there a suggested solution, if so, please add it**:
Codecov might support this. Need to do some research.

**Comment by jasonliu747** [comment]
https://docs.codeclimate.com/docs/configuring-your-analysis#test-coverage

**Comment by hormes** [comment]
+10086

**Comment by jasonliu747** [comment]
@saintube #131 didn't work, please take a look when you're free. Thanks.
