### ISSUE TITLE
aware scheduling

### ISSUE THREAD

**Issue by nailianglu** [koordinator-sh/koordinator#1246]
Organization/Company: SiRun (Beijing) Technology Co., Ltd.
Location: Beijing, China
Contact: wentao.lv@sirun.net
Purpose/Scenario: Use Koordinator load aware scheduling

**Comment by hormes** [comment]
I have added your information to the comments of this [issue](https://github.com/koordinator-sh/koordinator/issues/466).

**Comment by zwzhang0107** [comment]
Hi! welcome to join Koordinator!

**Comment by leason00** [comment]
Organization/Company: Youzan
Location: HangZhou, China
Contact: [lisen@youzan.com](mailto:lisen@youzan.com)
Purpose/Scenario: Use Koordinator load aware scheduling
