### ISSUE TITLE
[BUG]Find an bug with resource reservation for hostport reservation.

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#1247]
**What happened**:
Find an bug with resource reservation for hostport reservation.
t0: reservation reserved hostport 8080 for pod-1.
t1: pod-1 used the reserved hostport 8080, and the nodeInfo recorded the occupation of hostport 8080.
t2: pod-1 successfully used the reservation, so reservation will immediately delete, causing the deletion of hostport 8080 of pod-1 from nodeInfo.
As a result, any new pod can now use hostport 8080 without any restrictions.
**What you expected to happen**:
Maybe it can add a used hostport in the reservation status, so that when deleting Reservepod, the used hostport can be set to nil.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by eahydra** [comment]
Thanks for reporting this issue. Appreciate your suggestion, indeed we should record the hostPort used by the Pod in the ReservationStatus.
