### ISSUE TITLE
[proposal] koordlet collect container status info from CRI

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#1249]
**What is your proposal**:
get container status from CRI

**Why is this needed**:
koordlet need ContainerStatus info like sandbox id for rund setting and mount info for blkio qos.

**Is there a suggested solution, if so, please add it**:
add container_status_informer in states_informer module of koordlet

**Comment by zwzhang0107** [comment]
@halegreen Welcome and glad to hear!
The interface of `GetAllContainers()` sounds good, besides, I think here are more interfaces need to be defined:
- `GetContainer(containerHashID string) *ContainerMeta` to get container with specified ID
- `GetAllSandboxContainers() []*ContainerMeta` to get all sandbox containers, which is useful for rund senerio #1248
- `GeSandboxContainer(podUID string) *ContainerMeta` to get sandbox container by with specified ID
- `GetContainersByPodUID(podUID string) []*ContainerMeta` to get all containers with  specified pod UID

I totally agree with that these interfaces should be implemented in `ContainerInformer`, however, for `StatesInformer`, maybe it is not necessary to implements them.
The reason is that now `StatesInformer` has already provided too much details with interfaces like `GetNodeSLO`, `GetNodeTopo`. Since the plugin in `runtime-hooks` or `resmanager` only needs one or two "informers", it is better to provide an interface like `GetInformer(n InformerName)`, and let each plugin call the interfaces.

By the way, we should also consider the performance of getting infos from CRI. ContainerInformer should sync all infos periodically, and once some containers is newly created, we should use `inotify` mechanism to get the specified containers in pod to speed up the syncing like PodsInformer.

**Comment by halegreen** [comment]
@zwzhang0107 hi, thanks for your nice advices !  that's sounds really grateful.
And I want to clarify the `GetInformer(n InformerName)`  interface, my idea is to create  `InformerGetter` and `Informer` interface in `koordlet/statesinformer/api.go`: 

```
type InformerGetter interface {
	GetInformer(name informerName) Informer
}

type Informer interface {
	Run(stopCh <-chan struct{}) error
	HasSynced() bool

	GetNode() *corev1.Node
	GetNodeSLO() *slov1alpha1.NodeSLO
	GetAllPods() []*PodMeta
	GetNodeTopo() *topov1alpha1.NodeResourceTopology
	RegisterCallbacks(objType RegisterType, name, description string, callbackFn UpdateCbFn)
	GetContainer(containerHashID string) *ContainerMeta
	GetAllSandboxContainers() []*ContainerMeta
	GeSandboxContainer(podUID string) *ContainerMeta
	GetContainersByPodUID(podUID string) []*ContainerMeta
}
```
 
Struct  `statesInformer` and `containerInformer` implements the the `Informer` interface . 
For some method not implemented,  we throw **panic**,  such as  `GetContainer` method in `statesInformer`: 

```
func (s *statesInformer) GetContainer(containerHashID string) *ContainerMeta {
	panic("not implemented in this informer")
}
```

Thus, plugins in `runtime-hooks` and `resmanager` will change the `NewStatesInformer` to `NewStatesInformerGetter`; and  for the place calling `statesInformer`,   we can modify to `informerGetter.GetInformer(statesinformer.StatesInformerName).GetNodeSLO()` , with the least modification.

ex:
```
func (r *resmanager) getNodeSLOCopy() *slov1alpha1.NodeSLO {
	return r.statesInformer.GetInformer(statesinformer.StatesInformerName).GetNodeSLO()
}
```

Please take a look if it's OK for the usage of `Informer` ?

**Comment by halegreen** [comment]
And I want to know is `GetSandboxContainer ` interface used to return container in a pod sandbox? what about there's one more containers ?

**Comment by zwzhang0107** [comment]
@halegreen thanks for your contribution, actually, things might be more simple.

Now the `statesinformer` pkg has lots of `informerPlugins`, such as podsInformer, nodeInformer (we can see them from pkg/koordlet/statesinformer/registry.go). The new `ContainersInformer` should also be an `informerPlugin` type.

As for the StatesInformer interface,  we can simplify it, e.g.
``` go
type StatesInformer interface {
	Run(stopCh <-chan struct{}) error
	HasSynced() bool
        GetInformerPlugin(pluginName) InformerPlugin, error
        RegisterCallbacks(objType RegisterType, name, description string, callbackFn UpdateCbFn)
```

For other pkgs(resmanager.plugin) who are ready to use `GetContainer(containerHashID string)`, we can init them with `ContainersInformer` directly, so that `StatesInformer` doesnot need to provide so much detail functions.
For those who use method like `GetNode` or `GetNodeSLO`, we can refactor in the future and let them use `NodeInformer` or `NodeSLOInformer` plugin.

`GetSandboxContainer` returns the only one SANDBOX Container of pod, and `GetContainersByPodUID` is for returning info of other Containers.
