### ISSUE TITLE
在学习代码时，对这段逻辑感觉到困惑

### ISSUE THREAD

**Issue by VinceCui** [koordinator-sh/koordinator#1266]
这里的逻辑是，首先获取BE cgroup下的cpuset，如果BE组下有Pod，则获取第一个Pod的cpuset

据我所知，之所以这样处理是因为BE组下的Pod的cpuset一定会被Koordinator设置为和BE组相同，那么为何此处还需要多次一举？是否有什么别的考虑？

https://github.com/koordinator-sh/koordinator/blob/4a493a8645164e9ee5ad446c402a05cbd7f37798/pkg/koordlet/util/node.go#L55

麻烦解答一下，Thx~

**Comment by saintube** [comment]
@VinceCui 感谢细致的研读，这里是一个对 upstream Kubelet CPU Manager 的兼容逻辑。
首先，kubelet 在配置 `--cpu-manager-policy=static` 时会设置 container 的 `cpuset.cpus`，而 koordlet 的弹性绑核压制(CPUSuppress) 功能也需要调整 BE pod 的绑核，这就存在冲突的可能性。因此，对 `--cpu-manager-policy=static` 的情况，koordlet 为了避免冲突，选择在 container-level cgroup 一层设置 `cpuset.cpus` 而非在 besteffort 大组。见#546, #556。
然后，部分功能比如 CPUEvict 在获取 BE Pod 当前被压制后的 CPU Limit 时，也要考虑上述逻辑，需要结合 besteffort qos-level 和 container-level 两层的 `cpuset.cpus` 情况，对应了你这里提问的改动。这个改动也是来自社区伙伴的使用反馈，见 #871, #914。

**Comment by VinceCui** [comment]
OK, thank you.
