### ISSUE TITLE
Is the resctrl_unsupported.go file still meaningful at present?

### ISSUE THREAD

**Issue by yanxiaoqi932** [koordinator-sh/koordinator#1269]
**What happened: **Is the resctrl_unsupported.go file still meaningful at present? It seems that resctrl_linux.go has realized the related functions. Or do you need to extend it to the windows system? I hope you can answer, thanks.****

**What you expected to happen:**

**Environment:**

- Koordinator version: - v1.2.0

**Anything else we need to know:**

**Comment by zwzhang0107** [comment]
other system does not support resctrl now, this file is for compiling an UT.
