### ISSUE TITLE
[proposal] Chinese docs about best practice is English

### ISSUE THREAD

**Issue by lowang-bh** [koordinator-sh/koordinator#1272]
The docs about best practice switch to Chinese is still in Englisth.
[colocation-of-spark-jobs](https://koordinator.sh/zh-Hans/docs/best-practices/colocation-of-spark-jobs/)

**What is your proposal**:

Change to Chinese.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by hormes** [comment]
Yes, the translation is not finished yet, are you interested in participating? [doc](https://github.com/koordinator-sh/website/blob/main/i18n/zh-Hans/docusaurus-plugin-content-docs/current/best-practices/colocation-of-spark-jobs.md)

**Comment by lowang-bh** [comment]
ok, let me translate it.

**Comment by lowang-bh** [comment]
see [PR-134](https://github.com/koordinator-sh/website/pull/134) on website
