### ISSUE TITLE
[question]当前版本是否支撑cgroups的动态修改？

### ISSUE THREAD

**Issue by GreatLazyMan** [koordinator-sh/koordinator#1279]
根据阿里云ack官网，ack-koordinator提供一个Cgroups类型的资源以动态修改cpu limit等资源配置，想咨询下社区版当前是否支撑？

https://help.aliyun.com/document_detail/197267.htm

**Environment:**

- Koordinator version: - v1.2.
- Kubernetes version (use kubectl version): v1.25.8
- docker/containerd version: containerd 1.6.20
- OS (e.g: cat /etc/os-release): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. uname -a): 5.4.197-1.el7.elrepo.x86_64

**Anything else we need to know:**

**Comment by hormes** [comment]
当前版本未支持该特性，你是在什么语境下需要动态修改什么资源，可以描述一下具体的场景吗？

**Comment by GreatLazyMan** [comment]
不是什么特别场景，就是在学习cgroup操作的时候，看到cgroup本身支持动态修改，但是k8s中修改deployment中的resource的limit和request却需要重启pod。
看到ack-koordinator可以动态修改pod的cgroup，比较好奇，想咨询了解一下看看效果

**Comment by lowang-bh** [comment]
k8s 1.27开始支持动态修改resource
