### ISSUE TITLE
[proposal]koordlet 获取并维护task信息

### ISSUE THREAD

**Issue by songzh215** [koordinator-sh/koordinator#1301]
**What is your proposal**:
通过nm-adapter接口获取task元信息，并维护在内存中，使得koordlet感知task信息。

**Why is this needed**:
实现以下能力：
1. 采集离线任务资源使用
2. 离线驱逐与压制策略

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
/0524

**Comment by zwzhang0107** [comment]
copilot和korodlet之间有一个协议，会传递cgroup目录信息
协议待讨论，研发中

**Comment by zwzhang0107** [comment]
/0614 研发完成待测试
