### ISSUE TITLE
[proposal] NodeManager Adapter for Koordinator

### ISSUE THREAD

**Issue by Suozz** [koordinator-sh/koordinator#1306]
**What is your proposal**:

- [x] set yarn-container in memory cgroup if hadoop version is 2.x
- [x] API: kill container by container name
- [x] API: list yarn containers

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
/0524

**Comment by zwzhang0107** [comment]
/0531 todo
