### ISSUE TITLE
[proposal] NodeManager init Script

### ISSUE THREAD

**Issue by Suozz** [koordinator-sh/koordinator#1307]
**What is your proposal**:

- [ ] set yarn `yarn.nodemanager.linux-container-executor.cgroups.hierarchy` by detecting cgroup drvier
- [ ] Upgrade NodeManager configuration dynamically without restarting NodeManger Container

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
/0531

**Comment by zuston** [comment]
Good job! So glad to see Hadoop yarn support natively in Koordinator.

Do we have a complete proposal for this? We have designed the dynamic resource for Yarn Nodenamanger on Koordinator and deployed. Maybe we could share some experience and design on this.

**Comment by zwzhang0107** [comment]
/0614 待测试验证

**Comment by zwzhang0107** [comment]
> Good job! So glad to see Hadoop yarn support natively in Koordinator.
> 
> Do we have a complete proposal for this? We have designed the dynamic resource for Yarn Nodenamanger on Koordinator and deployed. Maybe we could share some experience and design on this.

hi, please take a look at this:
https://github.com/koordinator-sh/koordinator/discussions/1297

**Comment by Suozz** [comment]
EMR 平台已适配

**Comment by zwzhang0107** [comment]
> Good job! So glad to see Hadoop yarn support natively in Koordinator.
> 
> Do we have a complete proposal for this? We have designed the dynamic resource for Yarn Nodenamanger on Koordinator and deployed. Maybe we could share some experience and design on this.

@zuston  sorry for just saw this comment, here is the proposal:
https://github.com/koordinator-sh/koordinator/discussions/1297

it will be great if we can have some discussion.
