### ISSUE TITLE
对于负载均衡调度算法中，估算Pod用量部分有点费解

### ISSUE THREAD

**Issue by VinceCui** [koordinator-sh/koordinator#1310]
https://github.com/koordinator-sh/koordinator/blob/7c5a8ddf43526732d4440d5ce6640d36b1c1cc9f/pkg/scheduler/plugins/loadaware/estimator/default_estimator.go#LL97C12-L97C12

此处的代码用于估算一个Pod的资源使用量，考虑一个场景，假如有一个Pod，其中所有容器均只设置了Request而没有Limit，那么，根据以下代码，	quantity为requestQuantity

if limitQuantity.Cmp(requestQuantity) > 0 {
		scalingFactor = 100
		quantity = limitQuantity
	} else {
		quantity = requestQuantity
	}

紧接着，到这一块时：
	switch resourceName {
	case corev1.ResourceCPU:
		estimatedUsed = int64(math.Round(float64(quantity.MilliValue()) * float64(scalingFactor) / 100))
		if estimatedUsed > limitQuantity.MilliValue() {
			estimatedUsed = limitQuantity.MilliValue()
		}
假设scalingFactor=100，那么estimatedUsed=quantity=requestQuantity，所以>limitQuantity（0），那么，最终estimatedUsed就等于limitQuantity，也就是等于0了。

按照如上推理，一个只有Request而无Limit的Pod，其估算的Used=0，感觉不太合理。是否我的理解有所偏差，希望有时间可以解答一下~

**Comment by eahydra** [comment]
这看起来是个BUG..这种Pod跑下来就有问题了..  @VinceCui 有兴趣修复下么？

**Comment by eahydra** [comment]
@VinceCui 还准备提交PR解决这个问题么？

**Comment by eahydra** [comment]
这个问题搁置时间比较久了，感谢 @VinceCui 的反馈。 我领走解决掉。
/assign
