### ISSUE TITLE
[proposal]refactor pod/container PSI/CPI  metircs cache to tsdb

### ISSUE THREAD

**Issue by zshmmm** [koordinator-sh/koordinator#1329]
**What is your proposal**:
see https://github.com/koordinator-sh/koordinator/issues/1241 for full description.

**Why is this needed**:
refactor pod/container PSI/CPI metircs cache to tsdb for better performance and expansibility.

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
welcome!!
