### ISSUE TITLE
[BUG] descheduler evict Pod error

### ISSUE THREAD

**Issue by leason00** [koordinator-sh/koordinator#1348]
**What happened**:

```
I0602 15:08:53.003630       1 recorder.go:103] events "msg"="Warning"  "message"="Failed evict Pod \"prod/bd-prod-lumberjack-streaming-7587d86d45-4v4lc\" caused by Eviction in version \"v1\" cannot be handled as a Eviction: no kind \"Eviction\" is registered for version \"policy/v1\" in scheme \"k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30\"" "object"={"kind":"PodMigrationJob","name":"7e1aaa37-d8ec-444b-92d2-8d153dd0f7d1","uid":"2addaab6-58fb-40d8-bd67-8646ec5eb369","apiVersion":"scheduling.koordinator.sh/v1alpha1","resourceVersion":"4265598"} "reason"="Evicting"
I0602 15:08:53.115431       1 controller.go:265] begin process MigrationJob 78c0bfae-38fe-4fe8-97cf-78d80f24a30c
```
descheduler error

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: descheduler 1.2
- Kubernetes version (use `kubectl version`): v1.21.7
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by eahydra** [comment]
as we talked, in k8s v1.21.x, there is no eviction registered in policy/v1beta1. Only the k8s version has the problem.
