### ISSUE TITLE
[BUG] Memory qos WmarkRatio description

### ISSUE THREAD

**Issue by tianzichenone** [koordinator-sh/koordinator#136]
**What happened**:

memoryqos apis/slo/v1alpha1/nodeslo_types.go :
WmarkRatio docs:

	// `memory.wmark_high` := min(memory.high, memory.limit_in_bytes) * memory.wmark_scale_factor

this should be 
`memory.wmark_high` := min(memory.high, memory.limit_in_bytes) * memory.wmark_ratio?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by hormes** [comment]
@saintube
