### ISSUE TITLE
[proposal] Support  batch workload  in Koordinator

### ISSUE THREAD

**Issue by hzyfox** [koordinator-sh/koordinator#1367]
**What is your proposal**:

  Support  AI/ML and batch workload  in Koordinator

**Why is this needed**:

 With the popularity of cloud-native technology, more and more applications are running on infrastructure based on Kubernetes. While the Koordinator has done great work in Pod-level scheduling, such as discriminating pod scheduling based on QoS and achieving high utilization by combining elastic resource quota, efficient pod packing, over-commitment, and node sharing with container resource isolation. However, the Koordinator still lacks some applications-level scheduling functions, as it only supports Pod-level scheduling and cannot support application prioritization and fair scheduling like Yarn.

**Is there a suggested solution, if so, please add it**:

  TODO (:

**Comment by hormes** [comment]
Do you already have some ideas, welcome to in-depth exchanges.
