### ISSUE TITLE
[proposal] Coscheduling Support multiple Gang match policy

### ISSUE THREAD

**Issue by xulinfei1996** [koordinator-sh/koordinator#1379]
**What is your proposal**:
Koord-scheduler Coscheduling's gang match policy support multiple gang match policy.

**Why is this needed**:
So that users could use the gang match policy according to their need, not only the once-satisfied policy.

**Is there a suggested solution, if so, please add it**:

**Comment by KunWuLuan** [comment]
it seems same with 
- https://github.com/koordinator-sh/koordinator/issues/940
- https://github.com/kubernetes-sigs/scheduler-plugins/issues/560
