### ISSUE TITLE
[BUG] sharePoolCPUCore not exclude LSE

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#1403]
**What happened**:
I found sharePoolCPUCore logic not exclude LSE pod in function `getNodeStateForBurst` https://github.com/koordinator-sh/koordinator/blob/382f7a03b7dd42eac5866c9fffbc25760807080d/pkg/koordlet/resmanager/cpu_burst.go#L234

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by j4ckstraw** [comment]
how about this? `sharePoolCPUCoresTotal = nodeCPUCoresTotal - LSE - LSR`

**Comment by j4ckstraw** [comment]
how about this? 
`sharePoolCPUCoresTotal = nodeCPUCoresTotal - LSE - LSR`
`sharePoolCPUCoresUsage = nodeCPUCoresUsage - LSE - LSR - BE`

**Comment by j4ckstraw** [comment]
> how about this? `sharePoolCPUCoresTotal = nodeCPUCoresTotal - LSE - LSR` `sharePoolCPUCoresUsage = nodeCPUCoresUsage - LSE - LSR - BE`

or this? 
`sharePoolCPUCoresTotal = nodeCPUCoresTotal - LSE`
`sharePoolCPUCoresUsage = nodeCPUCoresUsage - LSE - LSR - BE`

**Comment by saintube** [comment]
> how about this? `sharePoolCPUCoresTotal = nodeCPUCoresTotal - LSE - LSR` `sharePoolCPUCoresUsage = nodeCPUCoresUsage - LSE - LSR - BE`

This is correct.

**Comment by eahydra** [comment]
fixed by #1404
