### ISSUE TITLE
[proposal] Essential QoS Enhancement Features of Koordlet

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#141]
**What is your proposal**:
List a series of QoS enhancement features of Koordlet since v0.4.

**Why is this needed**:

- [x] #147 
- [ ] #148
- [ ] blkio qos

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
1、features
* cpu evict strategy v0.4
* network qos v0.4
* blkio qos -v0.5/v0.6
* AMD pqos support（x86 LLC/MBA）- v0.5
* Kernel and environment adaptivity（cgroup v1/v2） - v0.5
* observability - v0.6
* recommender
    * api v0.5
    * Implement start at  v0.6

2、runtime-hooks <-> runtime-manager v0.4
	cpu qos plugins

3、qos-plugin-manager
	proposal during v0.4, describe the problem and plan
      doc with design v0.5
      implement v0.6

4、doc plan

**Comment by jasonliu747** [comment]
qos-plugin-manager proposal postpone to v0.5 /cc @stormgbs
