### ISSUE TITLE
[BUG] SLO-Controller calculation batch-cpu fluctuates frequently

### ISSUE THREAD

**Issue by tzzcfrank** [koordinator-sh/koordinator#1427]
**What happened**:

The BE Resource is calculated by the formula ```Node.Total - Node.Reserved - System.Used - Pod(non-BE).Used```, where ```System.Used = Node.Used - Pod(All).Used```. However, the System.Used calculation implementation has some problems, as follows: 
* At time t1, NodeMetric is updated; at time t2, the controller calculates NodeResource based on the update of NodeMetric. 
* Pod-B ends at time t2, and the controller regards the usage of Pod-B as System.Used

| component  | t1 | t2 | t3 | 
| ------------- | ------------- | ------------- | ------------- |
| koordlet  | node usage：2.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: 1 core <br/> update NodeMetrics  | node usage：1.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> update NodeMetrics |
| slo-controller  | | node usage：2.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> calculate node resource | node usage：1.5 core <br/> BE Pod-A: 1 core <br/> BE Pod-B: terminated <br/> calculate node resource |

Calculated according to the code of https://github.com/koordinator-sh/koordinator/blob/v1.2.0/pkg/slo-controller/noderesource/plugins/batchresource/plugin.go#L82

| t1 | t2 | t3 | 
| ------------- | ------------- | ------------- |
| System.Used：0.5 core <br/> Batch-CPU: x core |  System.Used：1.5 core <br/> Batch-CPU: x-1 core  | System.Used：0.5 core <br/> Batch-CPU: x core |

**What you expected to happen**:

Expecting time t2, the controller calculates System.Used = 0.5 core

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Node.Used uses the average value of the last 60 seconds, and Pod(All).Used uses the current value, which also causes the System.Used value to be inaccurate.

**Comment by zwzhang0107** [comment]
same with #991

**Comment by saintube** [comment]
@tzzcfrank Thanks for your feedback. As mentioned above, this problem can be fixed by adding a SystemUsage in #991. Moreover, we can alleviate the lagging of the resource ledger by updating the NodeMetric earlier when the calculated metrics differ too much from the last update.
