### ISSUE TITLE
[question]Using Koordinator in multi-cluster enviroment

### ISSUE THREAD

**Issue by reonard** [koordinator-sh/koordinator#1445]
**What happened:**

I'd like to hybrid deploy the Spark applications among the online web applications which run in serval separated clusters. Koordinator looks quite suitable for my case, but i am not sure if Koordinator has the ability to manage k8s workloads across clusters.

**What you expected to happen:**

Is there any suggestion or best practice for hybrid deployment in multi-clusters when using Koordinator?

**Environment:**

- Koordinator version: - v1.2
- Kubernetes version (use kubectl version): v1.9 and later
- docker/containerd version: containerd 19.03.13
- OS (e.g: cat /etc/os-release): CentOS 8.2
- Kernel (e.g. uname -a): 4.18.0-193.el8.x86_64

**Anything else we need to know:**

**Comment by hormes** [comment]
Koordinator currently solves the inCluster problem. If you have multiple K8s clusters, I think a reasonable solution is to divide them into two layers:
1. The upper layer resolves which cluster a job is sent to
2. InCluster uses Koordinator to solve resource scheduling and colocation isolation in the cluster

Cross-cluster scheduling is not a work that Koordinator will carry out in the near future. You can reuse your current multi-cluster solution when you are not doing colocation deployment.

**Comment by reonard** [comment]
> Koordinator currently solves the inCluster problem. If you have multiple K8s clusters, I think a reasonable solution is to divide them into two layers:
> 
> 1. The upper layer resolves which cluster a job is sent to
> 2. InCluster uses Koordinator to solve resource scheduling and colocation isolation in the cluster
> 
> Cross-cluster scheduling is not a work that Koordinator will carry out in the near future. You can reuse your current multi-cluster solution when you are not doing colocation deployment.

got it,  thanks
