### ISSUE TITLE
[BUG] architecture overview page not found

### ISSUE THREAD

**Issue by YongCHN** [koordinator-sh/koordinator#1452]
[architecture
](https://koordinator.sh/docs/docs/architecture/overview)

could not be opened.

![image](https://github.com/koordinator-sh/koordinator/assets/6441772/91876518-80e3-4219-bb47-a840f3286c1c)

**Comment by saintube** [comment]
@YongCHN Perhaps https://koordinator.sh/docs/architecture/overview is right.
It seems to be a dead link problem. Could you please add more info about where to get the link?
