### ISSUE TITLE
A FullPCPU pod may be scheduled to SpreadByPCPUs Node and bind cpuset with  policy.

### ISSUE THREAD

**Issue by ZiMengSheng** [koordinator-sh/koordinator#1453]
**What happened:**

**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by eahydra** [comment]
This is by design. Sometimes administrators want all Pods on a batch of nodes to use the Spread policy.
