### ISSUE TITLE
[BUG] koordlet continues reporting errors like:  error write /host-cgroup/memory/memory.limit_in_bytes: invalid argument

### ISSUE THREAD

**Issue by wangxiaoq** [koordinator-sh/koordinator#1467]
**What happened**:

koordlet continues reeporting error messages like:

```
I0710 11:39:58.311818   22264 container_context.go:207] set container xxx/xxx/xxx-main-container memory limit 6838812672 on cgroup parent  failed, error write /host-cgroup/memory/memory.limit_in_bytes: invalid argument
I0710 15:54:41.709863   22264 container_context.go:171] set container xxx/xxx/xxx-main-container cpu share 4096 on cgroup parent  failed, error write /host-cgroup/cpu/cpu.shares: invalid argument
I0710 15:54:41.709901   22264 container_context.go:195] set container xxx/xxx/xxx-main-container cfs quota 400000 on cgroup parent  failed, error write /host-cgroup/cpu/cpu.cfs_quota_us: invalid argument

```

**What you expected to happen**:

koordlet should not report these errors.

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl logs <koordlet-pod> -nkoordinator-system | grep -i "invalid argument"
```

**Anything else we need to know?**:

**Environment**:
- App version: 1.1.1
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by wangxiaoq** [comment]
I find some code here: https://github.com/koordinator-sh/koordinator/blob/main/pkg/koordlet/runtimehooks/protocol/container_context.go#L113 , we do not check the error value of `koordletutil.GetContainerCgroupPathWithKubeByID`. So if the conatinerID of the container is not allocated, the error would happen.

**Comment by wangxiaoq** [comment]
Sure it is a temporary error, once the conatinerID is allocated, the errors will disappears.

**Comment by zwzhang0107** [comment]
yep, it's better to check before writing.

**Comment by wangxiaoq** [comment]
> may have been fixed.
> 
> https://github.com/koordinator-sh/koordinator/blob/dd21c02eb16ad4c1f7e6b64c87530ef0b90fe43f/pkg/koordlet/runtimehooks/protocol/container_context.go#L180-L185

It seems so, thank you
