### ISSUE TITLE
[proposal] Add non-preemptible feature in Elastic Quota Management

### ISSUE THREAD

**Issue by jiasheng55** [koordinator-sh/koordinator#1473]
**What is your proposal**:
- Background
  - In the Google Borg paper, it describes a feature that "production" workloads cannot be preempted.
  > Although a preempted task will often be rescheduled elsewhere in the cell, preemption cascades could occur if a high-priority task bumped out a slightly lower-priority one, which bumped out another slightly-lower priority task, and so on. To eliminate most of this, **we disallow tasks in the production priority band to preempt one another.**
  - As [Multi Hierarchy Elastic Quota Management](https://koordinator.sh/docs/designs/multi-hierarchy-elastic-quota-management) documented, if the workload under a ElasticQuota uses more than "Min" resources, regardless of its Priority/QoS level, the workload may be preempted.

- Proposal
  - For important workloads, can we support setting Pods as non-preemptible (e.g. set koordinator.sh/preemptible: false), **so the sum of resource usage of Pods with this setting cannot exceed the Min of ElasticQuota, thus avoiding preemption** (Or we can limit "koord-prod" Priority workloads' resource usage not exceeding Min by configuration).

- Reference
  - [Uber Peloton](https://peloton.readthedocs.io/en/latest/user-guide/#resource-pools).

**Why is this needed**:
With this feature, users can deploy different types of workloads in a single ElasticQuota, including production workloads which cannot tolerate preemption, and non-production workloads which can take the advantages of ElasticQuota for more resources.

**Is there a suggested solution, if so, please add it**:

- Solution A: Add a new label (e.g. koordinator.sh/preemptible: true/false) to control whether a Pod can be preempted or not.
- Solution B: Add a configuration to control whether Pods with "koord-prod" Priority can be preempted or not.

Both Solution A and B should ensure that the sum of resource usage of non-preemptible Pods cannot exceed the Min of ElasticQuota.

**Comment by buptcozy** [comment]
@jiasheng55 this issue valid, we will arrange it.

**Comment by xulinfei1996** [comment]
@jiasheng55 this issue make sense. 
I think the implementation can be that, we classify pods as two kinds, one is guaranteed (non-preemptible) and the other is oversold (preemptible). For guaranteed pod, it can only use under MinQuota, for oversold pod, it can use under RuntimeQuota, by modify the PreFilter function. Once used Quota is over RuntimeQuota, we should only evict oversold pod.
And we should add a controller, which to make sure preemptible pods' usedQuota is smaller than the RuntimeQuota - minus(MinQuota, sum  of the non-preemptible pods' request)

**Comment by hormes** [comment]
It seems that everyone agrees with this proposal, can you provide a proposal or pr?

**Comment by eahydra** [comment]
@jiasheng55 The scene has been described very clearly, and the core Proposal is also very clear. If possible, you are welcome to submit a complete Proposal or PR, let's have fun.

**Comment by jiasheng55** [comment]
Thanks everyone, it sounds interesting to make some contributions to this project. Let me learn the contributing guide first. Any help would be grateful:)

**Comment by hormes** [comment]
> Thanks everyone, it sounds interesting to make some contributions to this project. Let me learn the contributing guide first. Any help would be grateful:)

Contributing: https://github.com/koordinator-sh/koordinator/blob/main/CONTRIBUTING.md

The Proposal  template: https://github.com/koordinator-sh/koordinator/blob/main/docs/proposals/YYYYMMDD-template.md,  and there are also previous proposals in the same directory.

**Comment by tan90github** [comment]
Please assign to me.
