### ISSUE TITLE
[proposal] Use libpfm4 in perf collector

### ISSUE THREAD

**Issue by Rouzip** [koordinator-sh/koordinator#1476]
**What is your proposal**:
Improve observability by adding more core events. Refactor the perf module to support perf group to calculate metrics more accurately.

**Why is this needed**:
`perf-utils` can only collect limited events and it cannot collect group events, we can use `libpfm4` to get more core events and refactor the perf module.
`libpfm4` is developed by Google, and it can parse all kinds of core/uncore events. We can use `CGO` to use it in golang without adding too much dependency.
Some events need to be measured at the same time(such as CPI and MPKI), and limited PMUs may lead to PMU multiplexing, resulting in large deviations in measurement data.

**Is there a suggested solution, if so, please add it**:
We can use [libpfm4](https://sourceforge.net/p/perfmon2/libpfm4/ci/master/tree/) to parse events in perf collector.
Steps:

1. Init `libpfm4` library, create perfValue pool and byte buffer pool
2. Create perf collector for each container
3. Use syscall `perf_event_open` to create fd for perf group and save the `id` for each event
4. Enable leader perf group to start events schedule in kernel space
5. Wait a period and stop all perf group, read data from leader group fd
6. Close all fds and cgroup fd

**Comment by xigang** [comment]
If the frequency of libpfm4 library collecting perf events is too high, it will interfere with the business process, so it is necessary to control the collection frequency. Our current collection period of perf event is 2min.

**Comment by Rouzip** [comment]
> The `libpfm4` library collects perf event frequency too high, which will interfere with the biz process, and the collection frequency needs to be controlled. Our current collection frequency is 2 minutes.

I just use `libpfm4` to convert event name to `unix.PerfEventAttr` struct like this:

```go
// https://man7.org/linux/man-pages/man3/pfm_get_os_event_encoding.3.html
func pfmGetOsEventEncoding(event string, perfEventAttrPtr unsafe.Pointer) error {
	arg := pfmPerfEncodeArgT{}
	arg.attr = perfEventAttrPtr
	fstr := C.CString("")
	defer C.free(unsafe.Pointer(fstr))
	arg.size = C.ulong(unsafe.Sizeof(arg))
	eventCStr := C.CString(event)
	defer C.free(unsafe.Pointer(eventCStr))
	if err := C.pfm_get_os_event_encoding(eventCStr, C.PFM_PLM0|C.PFM_PLM3, C.PFM_OS_PERF_EVENT, unsafe.Pointer(&arg)); err != C.PFM_SUCCESS {
		return fmt.Errorf("failed to get event encoding: %d", err)
	}
	return nil
}
```
I think it will not cause any interference compared to before.

**Comment by Rouzip** [comment]
Any suggestions and questions is welcome. @xigang @songtao98 @zwzhang0107

**Comment by xigang** [comment]
> > The `libpfm4` library collects perf event frequency too high, which will interfere with the biz process, and the collection frequency needs to be controlled. Our current collection frequency is 2 minutes.
> 
> I just use `libpfm4` to convert event name to `unix.PerfEventAttr` struct like this:
> 
> ```go
> // pfmPerfEncodeArgT represents structure that is used to parse perf event name
> // into perf_event_attr using libpfm4.
> type pfmPerfEncodeArgT struct {
> 	attr unsafe.Pointer
> 	fstr unsafe.Pointer
> 	size C.size_t
> 	_    C.int // idx
> 	_    C.int // cpu
> 	_    C.int // flags
> }
> 
> // https://man7.org/linux/man-pages/man3/pfm_get_os_event_encoding.3.html
> func pfmGetOsEventEncoding(event string, perfEventAttrPtr unsafe.Pointer) error {
> 	arg := pfmPerfEncodeArgT{}
> 	arg.attr = perfEventAttrPtr
> 	fstr := C.CString("")
> 	defer C.free(unsafe.Pointer(fstr))
> 	arg.size = C.ulong(unsafe.Sizeof(arg))
> 	eventCStr := C.CString(event)
> 	defer C.free(unsafe.Pointer(eventCStr))
> 	if err := C.pfm_get_os_event_encoding(eventCStr, C.PFM_PLM0|C.PFM_PLM3, C.PFM_OS_PERF_EVENT, unsafe.Pointer(&arg)); err != C.PFM_SUCCESS {
> 		return fmt.Errorf("failed to get event encoding: %d", err)
> 	}
> 	return nil
> }
> ```
> 
> I think it will not cause any interference compared to before.

@Rouzip If you only use `pfmGetOsEventEncoding` to get `*unix.PerfEventAttr`, the performance overhead is small. If you use the `unix.PerfEventOpen` api, the system overhead will be large (when the calling frequency is high).

**Comment by xigang** [comment]
If the real-time requirements of `IPC` metric are not very high (minute level), there is no problem using `libpfm4`.
