### ISSUE TITLE
[question] How to Schedule the resources of the openkruise CloneSet Controller?

### ISSUE THREAD

**Issue by binliiii** [koordinator-sh/koordinator#1481]
There is a CloneSet controller uses koord-scheduler as the default scheduler.
1. If CloneSet determines that the current change can be updated in place, and other nodes have sufficient resources, will Koordinator be dispatched to other nodes?
2. How to use koordinator and kruise CloneSet controllers elegantly?

**Comment by eahydra** [comment]
> 1. If CloneSet determines that the current change can be updated in place, and other nodes have sufficient resources, will Koordinator be dispatched to other nodes?

CloneSet has already decided to update pod in place, cannot re-create new pod, so the scheduler cannot participate here.

> 2. How to use koordinator and kruise CloneSet controllers elegantly?

Koordinator and OpenKruise are orthogonal, and there is no special scenario for the two to work well together.

**Comment by binliiii** [comment]
@eahydra 
yeah, if most pods use in-place update, and the cluster is unbalanced after a period of time, can I use koordinator's Load Aware Descheduling for optimization?
this a suitable solution?
