### ISSUE TITLE
[BUG]I install koordinator on huaweicloud cce,but I can't get the right result for the spark-pi job.

### ISSUE THREAD

**Issue by forcoder** [koordinator-sh/koordinator#150]
**What happened**:
when I use koordinator on huaweiCloud cce.
![image](https://user-images.githubusercontent.com/5011087/168946648-2b787a6f-56d9-456f-9a43-622bfd9cdba5.png)

I describe the pod:
![image](https://user-images.githubusercontent.com/5011087/168946961-56a97e67-f5d4-4cdf-9ed5-24e802b02f58.png)
![image](https://user-images.githubusercontent.com/5011087/168946989-1cfc2ae2-8738-4e96-a003-39d4e253907e.png)

I can't find batch-cpu and batch-memory information from the node:
![image](https://user-images.githubusercontent.com/5011087/168946822-66deee4e-d478-4d5a-b241-74d974c6ed55.png)

 I fetch logs from koordlet use kubectl logs ds:
kubectl logs --tail=10 koordlet-cd9xg
![image](https://user-images.githubusercontent.com/5011087/168947313-b5ae33e3-ca19-4edd-855b-b20f2ce54719.png)

So I modify the kubelet config for the node:
![image](https://user-images.githubusercontent.com/5011087/168947390-80898e01-964e-4694-a5ca-65cbe1b3300d.png)

I get the error info when the koordlet send request to kubelet:
this is the logs on the koordlet pod:
![image](https://user-images.githubusercontent.com/5011087/168945123-5c9fab7a-de10-4ba2-9848-0be00c4b500d.png)
this is the thumbnail on the node:
![image](https://user-images.githubusercontent.com/5011087/168945175-68cd109b-f055-49f6-83b9-ca615e6a04d8.png)
![image](https://user-images.githubusercontent.com/5011087/168945410-9f0d7e47-1a82-4b58-9da0-eba37a099b7b.png)

kubelet config:
`kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 0.0.0.0
#address: 7.183.231.172
authentication:
  anonymous:
    enabled: false
  x509:
    clientCAFile: /opt/cloud/cce/srv/kubernetes/cluster-ca.crt
authorization:
  mode: Webhook
clusterDNS:

\- 10.247.3.10
clusterDomain: cluster.local
enableControllerAttachDetach: true
evictionHard:
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
  imagefs.available: 10%
featureGates:
  DevicePlugins: true
  MultiGPUScheduling: true
  ExpandCSIVolumes: true
  CSIInlineVolume: true
  CSIMigrationFlexVolumeFuxi: true
  CSIMigrationFlexVolumeFuxiComplete: true
  CSIMigration: true
  IPv6DualStack: false
  ReserveMemoryCgroupForPageCache: false
  SizeMemoryBackedVolumes: true
  OversubscriptionResource: false

maxPods: 110
podPidsLimit: -1
port: 10250
readOnlyPort: 10255
staticPodPath: "/opt/cloud/cce/kubernetes/manifests"
serverTLSBootstrap: true
imageGCHighThresholdPercent: 80
imageGCLowThresholdPercent: 70
kubeAPIQPS: 100
kubeAPIBurst: 100
cpuManagerPolicy: none
tlsCipherSuites:
\- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
\- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
\- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
\- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kubeletCgroups: "/kubelet"
eventRecordQPS: 5
`

kubernetes version: 
![image](https://user-images.githubusercontent.com/5011087/168945905-56ce429c-8ed8-4a79-8b42-da8b439a3123.png)

**What you expected to happen**:
kubelet response the pod information to the koordlet

**How to reproduce it (as minimally and precisely as possible)**:
use huawei cloud cce and helm install koordinator.
**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`): 
- Install details (e.g. helm install args):
- Others:

**Comment by forcoder** [comment]
`test`

**Comment by jasonliu747** [comment]
Hi @forcoder, according to this [article](https://support.huaweicloud.com/intl/en-us/cce_faq/cce_faq_00290.html), Huawei CCE is supposed to supoort 10255 port. Can you confirm with people from Huawei?

**Comment by hormes** [comment]
@forcoder as discuss in DingDing group, could you submit a PR compatible with the mode of list-watch pods from apiserver？

**Comment by forcoder** [comment]
> @forcoder as discuss in DingDing group, could you submit a PR compatible with the mode of list-watch pods from apiserver？

I have a try
