### ISSUE TITLE
[proposal] Optimize filter switch of PodMigrations

### ISSUE THREAD

**Issue by ZiMengSheng** [koordinator-sh/koordinator#1511]
**Why is this needed**:
PodMigrationJob currently has non-retrievable and retrievable filter. Retrievable filter aims at rate-limiting and non-retrievable filter focus on pod's situation. 
However, some filters currently classified as retrievable filter are not really retrievable, such as expected replicas of workload equals 1 or two replicas of workload are all alrealdy unavailable now. 

**What is your proposal**:
For case as "expected replicas of workload equals one", we can move it to non-retrievable filter.
For case as  "two replicas of workload are all alrealdy unavailable", because its logic mixes with maxMigratingPerWorkload, we still classify it as retrievable filter but reuse the EvictAnnotation switch of non-retrievabe filter to allow user skip it.

**Is there a suggested solution, if so, please add it**:

**Reference**

non-retrievable filters:
- bare pods
- system critical
- local storage
- pvc
- daemonset
- mirror,static
- terminating
- maxEvictionCost
- expectedReplicas: maxMigrating equals expected replicas
- namespace include
- namespace exclude

retrievable filters:
- rete-limited
- maxMigratingPerNamespace
- maxMigratingPerNode
- maxMigratingPerWorkload

**Comment by eahydra** [comment]
If there is already annotation `descheduler.alpha.kubernetes.io/evict` in the MigrationJob or Pod, all filters should be skipped, retryable or not.
