### ISSUE TITLE
[question] The update QPS of the noderesourcetopologies resource is too high 

### ISSUE THREAD

**Issue by sleep0nTime** [koordinator-sh/koordinator#1531]
**What happened:** 
Koordlet will update the noderesourcetopologies resource corresponding to the current node every 3 seconds. For Agents, the frequency of requesting the apiserver is a bit too high.
![image](https://github.com/koordinator-sh/koordinator/assets/5621319/7c696b19-01f2-43ab-8f54-9a9bdae92b89)

**What you expected to happen:**
Reduce the QPS of updating the noderesourcetopologies resource.

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by saintube** [comment]
@sleep0nTime Do you still use koordinator v0.6.2? The problem is fixed in #893, #1221.
