### ISSUE TITLE
[question] koord-runtime-proxy can not work with 1.27.3

### ISSUE THREAD

**Issue by iamryanchia** [koordinator-sh/koordinator#1541]
**What happened:**

The document says koordinator requires `Kubernetes version >= 1.18` which means it can support 1.18+. However the latest version 1.2.0 can not work with 1.27.3 as cri v1alpha2 has dropped from 1.26.0.

**What you expected to happen:**

Please write more explicit in the document. And has any plan to support cri v1? Thank you!

**Environment:**

- Koordinator version: - v1.2.0
- Kubernetes version (use kubectl version): v1.27.3
- crio version: containerd v1.27.0
- OS (e.g: cat /etc/os-release): Ubuntu 22.04.2 LTS

**Comment by saintube** [comment]
/area koord-runtime-proxy
/area koordlet

Duplicate with #1051.

**Comment by saintube** [comment]
/area runtime-proxy
/area koordlet

Duplicate with #1051.
