### ISSUE TITLE
[question] Could WSL2 be used for testing purpose?

### ISSUE THREAD

**Issue by guhuajun** [koordinator-sh/koordinator#1558]
**What happened:**

```bash
sudo kubectl -n koordinator-system logs koordlet-qbl4d | grep gpu
```

```bash
I0819 10:04:28.529389  152058 states_device_linux.go:147] gpu device not exist
I0819 10:04:28.556178  152058 states_device_linux.go:275] start to do gpu health check
W0819 10:04:28.556216  152058 collector_gpu_linux.go:72] nvml init gpu data, error unable to get device minor number: Not Supported
I0819 10:04:28.559193  152058 states_device_linux.go:281] get a unhealthy gpu GPU-dbb5557a-cd2e-0f27-531c-a2ca5524e4a3
```

**What you expected to happen:**
Found a healthy GPU in WSL2 environment for testing purpose

**Environment:**

- Koordinator version: - v1.3.0
- Kubernetes version (use kubectl version): v1.26.3+k3s1
- docker/containerd version: containerd 20.10.25
- OS (e.g: cat /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. uname -a): 5.15.90.1-microsoft-standard-WSL2

**Anything else we need to know:**

See the discussions and fixes in following page

https://github.com/NVIDIA/k8s-device-plugin/issues/332
https://gitlab.com/Vinrobot/nvidia-kubernetes-device-plugin/-/commit/8816d1d25a0c09543574f8db2f0f47abd6fbbfa1

Microsoft documentation:
https://learn.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl

**Comment by eahydra** [comment]
We have no plans to support WSL2, but welcome to contribute a PR if you are interested in this work.
