### ISSUE TITLE
[BUG] koordlet close cgroup file error and cannot collect cycles

### ISSUE THREAD

**Issue by bowen-intel** [koordinator-sh/koordinator#1568]
**What happened**:
While using koordlet version v1.3.0, and after activating the performance collector feature, an error arises during the closure of cgroup files upon perf data collection. The error message is as follows:
```text
E0822 17:41:55.375473 1723326 performance_collector_linux.go:156] PerfCollector cleanup err : close cgroupFile /host-cgroup/kubepods.slice/xxx.scope, err : close /host-cgroup/kubepods.slice/xxx.scope: file already closed
```
and the result of cycles is 0(the result of instructions is not 0)
```text
koordlet_container_cpi{container_id="containerd://xxx",container_name="xxx",cpi_field="cycles",node="xxx",pod_name="xxx",pod_namespace="xxx",pod_uid="xxx"} 0
koordlet_container_cpi{container_id="containerd://xxx",container_name="xxx",cpi_field="instructions",node="xxx",pod_name="xxx",pod_namespace="xxx",pod_uid="xxx"} 3.46941397e+09
```
**What you expected to happen**:
No Error, the result of cycles is not 0.
**How to reproduce it (as minimally and precisely as possible)**:
1. Create a ns and create a deployment which has 100 nginx instances.
2. Install koordinator and enable `CPI`, `PSI`.
3. Use `kubectl` get the log of `koordlet`. Use `curl` get the metrics.

**Anything else we need to know?**:
Use `perf` can get right result.
**Environment**:
- App version: v1.3.0
- Kubernetes version (use `kubectl version`): v1.27.2
- Install details (e.g. helm install args): helm install koordinator koordinator-sh/koordinator --version 1.3.0
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:1.7.1
  - OS version:Ubuntu 22.04
  - Kernal version:5.15.0-79-generic
  - Cgroup driver: cgroupfs
- Others:

**Comment by zwzhang0107** [comment]
PTAL @songtao98

**Comment by bowen-intel** [comment]
I think part of the error is caused by perf collector `Cleanup` twice[[1]](https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L198)[[2]](https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L154).

**Comment by bowen-intel** [comment]
The another error is caused by this [pr](https://github.com/koordinator-sh/koordinator/pull/1482). Sorry for this error orz.

**Comment by songtao98** [comment]
> I think part of the error is caused by PerfCollector `Cleanup` twice[[1]](https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L198)[[2]](https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L154).

Yes, and I recall that the initial implementation intends to CleanUp the perfCollector outside the profile function(at the [[2] ](https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L154)position), thus making profile function do only the profile job. I think the CleanUp at [[1] ]((https://github.com/koordinator-sh/koordinator/blob/bb9907d1ca683f6f3d43d8b5d7c9a2dfe573efb2/pkg/koordlet/metricsadvisor/collectors/performance/performance_collector_linux.go#L198)is redundant.

**Comment by zwzhang0107** [comment]
nice job! @bowen-intel
