### ISSUE TITLE
[BUG]安装runtimeproxy失败

### ISSUE THREAD

**Issue by ghostloda** [koordinator-sh/koordinator#1580]
**What happened**:
kubelet启动失败：
`
CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/koord-runtimeproxy/runtimeproxy.sock
`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: 1.3.0
- Kubernetes version (use `kubectl version`): v1.26.2
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd: v1.6.19
  - OS version: centos7.9
  - Kernal version: 5.12.0
  - Cgroup driver: systemd
- Others:

**Comment by saintube** [comment]
/area runtime-proxy
/area koordlet

Sorry. The current version of runtimeproxy does not support CRI v1 API (>= k8s 1.26.0). It will be fixed in the following versions.

Duplicate with https://github.com/koordinator-sh/koordinator/issues/1051.

**Comment by hormes** [comment]
It will be fixed by #1593.
