### ISSUE TITLE
[proposal] koord-scheduler failed to list v1.CSIDriver

### ISSUE THREAD

**Issue by BlackPigHe** [koordinator-sh/koordinator#1582]
**What is your proposal**:
failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:serviceaccount:koordinator-system:koord-scheduler" cannot list resource "csidrivers" in API group "storage.k8s.io"

**Why is this needed**:
k8s resource type 有很多，否则koord-scheduler无法正常启动

**Is there a suggested solution, if so, please add it**:
cluster角色需要增加一些权限

kubectl edit ClusterRole koord-scheduler-role
增加以下配置
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - get
  - list
  - watch

**Comment by eahydra** [comment]
你遇到的这个问题，所在的K8s 集群版本以及koordinator版本是多少？
koord-scheduler默认会复用 kube-scheduler role的RBAC，这些默认都有权限的。

**Comment by BlackPigHe** [comment]
k8s 1.18.3
koordinator-sh/koordinator --version 1.3.0

**Comment by eahydra** [comment]
> k8s 1.18.3 koordinator-sh/koordinator --version 1.3.0

ok. 那我知道原因所在了。koordinator依赖的k8s 代码升级到了v1.24后，这里确实遗漏了一个针对 CSIDriver 兼容的逻辑。

**Comment by lowang-bh** [comment]
Hi, @eahydra , I checked the code and find scheduler use sa named `koord-scheduler`. But I didn't find any service account defines of `koord-scheduler`, just SA named `scheduler`.  I am confused.

https://github.com/koordinator-sh/koordinator/blob/4c1cfb392d94c0e5836194e4e02642e1c43f0602/config/manager/scheduler.yaml#L63

https://github.com/koordinator-sh/koordinator/blob/4c1cfb392d94c0e5836194e4e02642e1c43f0602/config/rbac/scheduler_role_binding.yaml#L1-L20

**Comment by eahydra** [comment]
> Hi, @eahydra , I checked the code and find scheduler use sa named `koord-scheduler`. But I didn't find any service account defines of `koord-scheduler`, just SA named `scheduler`. I am confused.
> 
> https://github.com/koordinator-sh/koordinator/blob/4c1cfb392d94c0e5836194e4e02642e1c43f0602/config/manager/scheduler.yaml#L63
> 
> https://github.com/koordinator-sh/koordinator/blob/4c1cfb392d94c0e5836194e4e02642e1c43f0602/config/rbac/scheduler_role_binding.yaml#L1-L20

These files are written according to kustomize specifications and need to be generated with kustomize to see the actual configuration files used.
