### ISSUE TITLE
[question] What is difference between koordinator evict pod and kubelet evict pod. For example if memory usage is much high.

### ISSUE THREAD

**Issue by MIBc** [koordinator-sh/koordinator#1634]
What is difference between koordinator evict pod and kubelet evict pod. For example if memory usage is much high.

**Comment by zwzhang0107** [comment]
koordlet use different strategies during evicting pods on node.
you can get more details from the doc:
https://koordinator.sh/docs/user-manuals/memory-evict/
https://koordinator.sh/docs/user-manuals/cpu-evict
