### ISSUE TITLE
[BUG]Koordinator Related Pod Preemptted by User Created Pod

### ISSUE THREAD

**Issue by zhiying11qian** [koordinator-sh/koordinator#1756]
**What happened**:
    We want to see how the cluster do when resources are used to the limit and additional pods are deployed.
    We deploy one additional nginx Pod which request for 1core CPU when the resource in the Cluster were all used.
    There was no resource can be requested for the nginx node . so the node was always pending .
But we found that the Koordinator related pods were restarted ,e.g:koordinator-system/koord-scheduler-95bdbcddb-pwlxx.
    Sometimes koord-descheduler was preemptted too.
    Koord-scheduler is 2Replica by default, and I checked the logs of the non-deleted pods and found the following message.
```
I1122 10:27:55.613060 1 eventhandlers.go:116]"Add event for unscheduled pod" pod="default/nginx-be-8447f59895-kszkq"
I1122 10:27:55.613112 1 scheduling_queue.go:963]"About to try and schedule pod" pod="default/nginx-be-8447f59895-kszkq"
I1122 10:27:55.613123 1 schedule_one.go:84]"Attempting to schedule pod" pod="default/nginx-be-8447f59895-kszkq"
I1122 10:27:55.618631 1 preemption.go:349]"**Preemptor Pod preempted victim Pod" preemptor="default/nginx-be-8447f59895-kszkq" victim="" koordinator-system/koord-scheduler-95bdbcddb-pwlxx" node="linode-3q-opt-koordinator-worker1"**
I1122 10:27:55.618799 1 scheduler.go:352] "Unable to schedule pod; no fit; waiting" pod="default/nginx-be-8447f59895-kszkq" err="0/3 nodes are available:. 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }, 2 Insufficient cache: 1 }, 2 Insufficient cpu."
I1122 10:27:55.618845 1 schedule_one.go:849]"Updating pod condition" pod="default/nginx-be-8447f59895-kszkq" conditionType=PodScheduled conditionStatus=False conditionReason="Unschedulable"
I1122 10:27:55.620123 1 eventhandlers.go:204]"Update event for scheduled pod" pod="koordinator-system/koord-scheduler-95bdbcddb-pwlxx"
I1122 10:27:55.646130 1 eventhandlers.go:184]"Add event for scheduled pod" pod="koordinator-system/koord-scheduler-95bdbcddb-sf9g2"
```
We checked the Koordinator related pod and found the pods were not deployed with any  Koordinator priorityClass or Qos.
The Nginx pod we deployed was using the  priorityClass with koord-batch .
I'd like to check, is this normal behavior or does it affect Koordinator's own functionality? If so, is there any way to avoid it?

**What you expected to happen**:
The co-location was not enabled ,so the BE Class Pod was not going to use the kubernetes.io/batch-cpu resource . Will always be Pending.
but the Koordinator Pod should not be deleted.
Maybe it is good idea to define Priority/QosClass in advance for Koordinator-related pods?

**How to reproduce it (as minimally and precisely as possible)**:
   We installed the Koordinator without any extra args ,just Helm Install
   The following Yaml is used to deploy the test Pod.
　the pod deployed to use all resource on the cluster 
   ```
apiVersion: apps/v1
--
kind: Deployment
metadata:
name: nginx-ls
labels:
app: nginx-ls
spec:
replicas: 3
selector:
matchLabels:
app: nginx-ls
template:
metadata:
name: nginx-ls
labels:
app: nginx-ls
koordinator.sh/qosClass: LS # set the QoS class as LSR, the binding   policy is FullPCPUs by default
# in v0.5, binding policy should be specified.
# e.g. to set binding policy as FullPCPUs (prefer allocating full   physical CPUs of the same core):
#annotations:
#scheduling.koordinator.sh/resource-spec:   '{"preferredCPUBindPolicy": "FullPCPUs"}'
spec:
schedulerName: koord-scheduler # use the koord-scheduler
containers:
- name: nginx-prod
image: nginx
resources:
limits:
cpu: '1'
requests:
cpu: '1'
priorityClassName: koord-prod
```

the  additional pod deployed to see how cluster works

```
apiVersion: apps/v1
--
kind: Deployment
metadata:
name: nginx-be
labels:
app: nginx-be
spec:
replicas: 1
selector:
matchLabels:
app: nginx-be
template:
metadata:
name: nginx-be
labels:
app: nginx-be
koordinator.sh/qosClass: BE # set the QoS class as LSR, the binding   policy is FullPCPUs by default
# in v0.5, binding policy should be specified.
# e.g. to set binding policy as FullPCPUs (prefer allocating full   physical CPUs of the same core):
#annotations:
#scheduling.koordinator.sh/resource-spec:   '{"preferredCPUBindPolicy": "FullPCPUs"}'
spec:
schedulerName: koord-scheduler # use the koord-scheduler
containers:
- name: nginx-batch
image: nginx
resources:
limits:
cpu: '1'
requests:
cpu: '1'
priorityClassName: koord-batch
```

**Anything else we need to know?**:

**Environment**:  
- App version: 1.3 
- Kubernetes version (use `kubectl version`):
   ```
  buildDate: "2023-04-12T12:15:50Z"
  compiler: gc
  gitCommit: 49433308be5b958856b6949df02b716e0a7cf0a3
  gitTreeState: clean
  gitVersion: v1.24.13
  goVersion: go1.19.8
  major: "1"
  minor: "24"
  platform: linux/amd64
  kustomizeVersion: v4.5.4
  serverVersion:
  buildDate: "2023-08-24T04:20:55Z"
  compiler: gc
  gitCommit: 22a9682c8fe855c321be75c5faacde343f909b04
  gitTreeState: clean
  gitVersion: v1.24.17+rke2r1
  goVersion: go1.20.7 X:boringcrypto
  major: "1"
  minor: "24"
  platform: linux/amd64

  ```

- Install details (e.g. helm install args):   `helm install koordinator koordinator-sh/koordinator --version 1.3.0` without setting extra args
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:  containerd://1.7.3-k3s1
  - OS version: Ubuntu 22.04.3 LTS
  - Kernal version:  5.15.0-88-generic
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by zwzhang0107** [comment]
do you mean that koord-scheduler is preempted by itself due to other pods pending?
this should not happen, could you provide more infos about the resource allocated status.
cc @eahydra
