### ISSUE TITLE
[proposal] PodMigrationJob support external conditions

### ISSUE THREAD

**Issue by sjtufl** [koordinator-sh/koordinator#1760]
**What is your proposal**:
Introduce mechanism for PodMigrationJob to make sure that some external conditions are met before performing actual evictions on pods.

**Why is this needed**:
PodMigrationJob supports two types of pod migration modes currently, i.e. `EvictDirectly` and `ReservationFirst`. Pod eviction is performed directly, or after Reservation is successfully scheduled. However, as an operation at high risk, evicting pod must meet some external interception conditions in scenarios with high technical risk requirements (such as financial scenarios). Typical external conditions include cutting off _North/South_ & _East/West_ traffic, getting approval from change risk control system, etc. Therefore, the external conditions mechanism is needed to let the PodMigrationJob check whether the predefined interception conditions have been met before performing the actual eviction operation, reducing the risk of pod migration.

**Is there a suggested solution, if so, please add it**:

**Comment by eahydra** [comment]
Awesome! Looking forward to Proposals and PRs. 🎉
