### ISSUE TITLE
[BUG] Failed to apply l3 cat and mba policy due to deficiencies in CPU cache info collection.

### ISSUE THREAD

**Issue by chl178** [koordinator-sh/koordinator#1777]
**What happened**:
```
W1213 10:54:56.286611   27294 resctrl_reconcile.go:253] failed to write l3 cat policy on schemata for group BE, err: failed to read current resctrl schemata, path /host-sys-fs/resctrl/BE/schemata, err: failed to parse l3 schemata, content     L3:0=ffff;1=ffff;2=ffff;3=ffff;4=ffff;5=ffff;6=ffff;7=ffff;16=ffff;17=ffff;18=ffff;19=ffff;20=ffff;21=ffff;22=ffff;23=ffff
    MB:0=2048;1=2048;2=2048;3=2048;4=2048;5=2048;6=2048;7=2048;16=2048;17=2048;18=2048;19=2048;20=2048;21=2048;22=2048;23=2048
, err: read resctrl schemata failed, L3 masks of node 8 is missing
W1213 10:54:56.286629   27294 resctrl_reconcile.go:352] failed to apply l3 cat policy for group BE, err: failed to read current resctrl schemata, path /host-sys-fs/resctrl/BE/schemata, err: failed to parse l3 schemata, content     L3:0=ffff;1=ffff;2=ffff;3=ffff;4=ffff;5=ffff;6=ffff;7=ffff;16=ffff;17=ffff;18=ffff;19=ffff;20=ffff;21=ffff;22=ffff;23=ffff
    MB:0=2048;1=2048;2=2048;3=2048;4=2048;5=2048;6=2048;7=2048;16=2048;17=2048;18=2048;19=2048;20=2048;21=2048;22=2048;23=2048
, err: read resctrl schemata failed, L3 masks of node 8 is missing
W1213 10:54:56.286737   27294 resctrl_reconcile.go:279] failed to write mba policy on schemata for group BE, err: failed to read current resctrl schemata, path /host-sys-fs/resctrl/BE/schemata, err: failed to parse l3 schemata, content     L3:0=ffff;1=ffff;2=ffff;3=ffff;4=ffff;5=ffff;6=ffff;7=ffff;16=ffff;17=ffff;18=ffff;19=ffff;20=ffff;21=ffff;22=ffff;23=ffff
    MB:0=2048;1=2048;2=2048;3=2048;4=2048;5=2048;6=2048;7=2048;16=2048;17=2048;18=2048;19=2048;20=2048;21=2048;22=2048;23=2048
, err: read resctrl schemata failed, L3 masks of node 8 is missing
W1213 10:54:56.286755   27294 resctrl_reconcile.go:356] failed to apply cat MB policy for group BE, err: failed to read current resctrl schemata, path /host-sys-fs/resctrl/BE/schemata, err: failed to parse l3 schemata, content     L3:0=ffff;1=ffff;2=ffff;3=ffff;4=ffff;5=ffff;6=ffff;7=ffff;16=ffff;17=ffff;18=ffff;19=ffff;20=ffff;21=ffff;22=ffff;23=ffff
    MB:0=2048;1=2048;2=2048;3=2048;4=2048;5=2048;6=2048;7=2048;16=2048;17=2048;18=2048;19=2048;20=2048;21=2048;22=2048;23=2048
, err: read resctrl schemata failed, L3 masks of node 8 is missing
```

**What you expected to happen**:
Apply the policy successfully
**How to reproduce it (as minimally and precisely as possible)**:
Enable resctrl in resource-qos-config while the node cache ids are not contiguous.
**Anything else we need to know?**:
I checked the **[Intel and Linux official documentation](https://www.kernel.org/doc/html/v5.4/x86/resctrl_ui.html#cache-ids)** and found that instead of using "socket" or "core" to define the set of logical cpus sharing a resource they use a "Cache ID", and it isn't guaranteed to be a contiguous sequence, there may be gaps. 

But koordinator assumed that the cache IDs are contiguous.[code link](https://github.com/koordinator-sh/koordinator/blob/c927e11a57e105697d43c65e5dfb643adcf096f5/pkg/koordlet/util/system/resctrl.go#L366C6-L366C6)

Koordlet uses `lscpu` command with `-e=CPU,NODE,SOCKET,CORE,CACHE,ONLINE` flag to get the node cpu info, but actually the cache ID info are stored in the `/sys/devices/system/cpu/cpu*/cache/index*/id`
**Environment**:
- App version: v1.3.0
- Kubernetes version (use kubectl version): v1.23.13
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
@chl178 Thanks for your feedback. It is a bug and should be fixed by generating the RDT schemata according to the map `L3ToCPU`. Though the common Intel Xeon processors tested take the consecutive L3 cache IDs, could you please also show us your CPU model (e.g. Intel Xeon Platinum 8269CY...) and the output of `lscpu -e`.

**Comment by chl178** [comment]
@saintube AMD EPYC 7542 32-Core Processor. Thanks for your help!

**Comment by saintube** [comment]
> @saintube AMD EPYC 7542 32-Core Processor. Thanks for your help! The output of lscpu -e:
> 
> ```
> CPU NODE SOCKET CORE L1d:L1i:L2:L3 ONLINE    MAXMHZ    MINMHZ
> 
>   0    0      0    0 0:0:0:0          yes 3406.9331 1500.0000
>   1    0      0    1 1:1:1:0          yes 3406.9331 1500.0000
>   2    0      0    2 2:2:2:0          yes 3406.9331 1500.0000
>   3    0      0    3 3:3:3:0          yes 3406.9331 1500.0000
>   4    0      0    4 4:4:4:1          yes 3406.9331 1500.0000
>   5    0      0    5 5:5:5:1          yes 3406.9331 1500.0000
>   6    0      0    6 6:6:6:1          yes 3406.9331 1500.0000
>   7    0      0    7 7:7:7:1          yes 3406.9331 1500.0000
>   8    0      0    8 8:8:8:2          yes 3406.9331 1500.0000
>   9    0      0    9 9:9:9:2          yes 3406.9331 1500.0000
>  10    0      0   10 10:10:10:2       yes 3406.9331 1500.0000
>  11    0      0   11 11:11:11:2       yes 3406.9331 1500.0000
>  12    0      0   12 12:12:12:3       yes 3406.9331 1500.0000
>  13    0      0   13 13:13:13:3       yes 3406.9331 1500.0000
>  14    0      0   14 14:14:14:3       yes 3406.9331 1500.0000
>  15    0      0   15 15:15:15:3       yes 3406.9331 1500.0000
>  16    0      0   16 16:16:16:4       yes 3406.9331 1500.0000
>  17    0      0   17 17:17:17:4       yes 3406.9331 1500.0000
>  18    0      0   18 18:18:18:4       yes 3406.9331 1500.0000
>  19    0      0   19 19:19:19:4       yes 3406.9331 1500.0000
>  20    0      0   20 20:20:20:5       yes 3406.9331 1500.0000
>  21    0      0   21 21:21:21:5       yes 3406.9331 1500.0000
>  22    0      0   22 22:22:22:5       yes 3406.9331 1500.0000
>  23    0      0   23 23:23:23:5       yes 3406.9331 1500.0000
>  24    0      0   24 24:24:24:6       yes 3406.9331 1500.0000
>  25    0      0   25 25:25:25:6       yes 3406.9331 1500.0000
>  26    0      0   26 26:26:26:6       yes 3406.9331 1500.0000
>  27    0      0   27 27:27:27:6       yes 3406.9331 1500.0000
>  28    0      0   28 28:28:28:7       yes 3406.9331 1500.0000
>  29    0      0   29 29:29:29:7       yes 3406.9331 1500.0000
>  30    0      0   30 30:30:30:7       yes 3406.9331 1500.0000
>  31    0      0   31 31:31:31:7       yes 3406.9331 1500.0000
>  32    1      1   32 32:32:32:8       yes 3406.9331 1500.0000
>  33    1      1   33 33:33:33:8       yes 3406.9331 1500.0000
>  34    1      1   34 34:34:34:8       yes 3406.9331 1500.0000
>  35    1      1   35 35:35:35:8       yes 3406.9331 1500.0000
>  36    1      1   36 36:36:36:9       yes 3406.9331 1500.0000
>  37    1      1   37 37:37:37:9       yes 3406.9331 1500.0000
>  38    1      1   38 38:38:38:9       yes 3406.9331 1500.0000
>  39    1      1   39 39:39:39:9       yes 3406.9331 1500.0000
>  40    1      1   40 40:40:40:10      yes 3406.9331 1500.0000
>  41    1      1   41 41:41:41:10      yes 3406.9331 1500.0000
>  42    1      1   42 42:42:42:10      yes 3406.9331 1500.0000
>  43    1      1   43 43:43:43:10      yes 3406.9331 1500.0000
>  44    1      1   44 44:44:44:11      yes 3406.9331 1500.0000
>  45    1      1   45 45:45:45:11      yes 3406.9331 1500.0000
>  46    1      1   46 46:46:46:11      yes 3406.9331 1500.0000
>  47    1      1   47 47:47:47:11      yes 3406.9331 1500.0000
>  48    1      1   48 48:48:48:12      yes 3406.9331 1500.0000
>  49    1      1   49 49:49:49:12      yes 3406.9331 1500.0000
>  50    1      1   50 50:50:50:12      yes 3406.9331 1500.0000
>  51    1      1   51 51:51:51:12      yes 3406.9331 1500.0000
>  52    1      1   52 52:52:52:13      yes 3406.9331 1500.0000
>  53    1      1   53 53:53:53:13      yes 3406.9331 1500.0000
>  54    1      1   54 54:54:54:13      yes 3406.9331 1500.0000
>  55    1      1   55 55:55:55:13      yes 3406.9331 1500.0000
>  56    1      1   56 56:56:56:14      yes 3406.9331 1500.0000
>  57    1      1   57 57:57:57:14      yes 3406.9331 1500.0000
>  58    1      1   58 58:58:58:14      yes 3406.9331 1500.0000
>  59    1      1   59 59:59:59:14      yes 3406.9331 1500.0000
>  60    1      1   60 60:60:60:15      yes 3406.9331 1500.0000
>  61    1      1   61 61:61:61:15      yes 3406.9331 1500.0000
>  62    1      1   62 62:62:62:15      yes 3406.9331 1500.0000
>  63    1      1   63 63:63:63:15      yes 3406.9331 1500.0000
>  64    0      0    0 0:0:0:0          yes 3406.9331 1500.0000
>  65    0      0    1 1:1:1:0          yes 3406.9331 1500.0000
>  66    0      0    2 2:2:2:0          yes 3406.9331 1500.0000
>  67    0      0    3 3:3:3:0          yes 3406.9331 1500.0000
>  68    0      0    4 4:4:4:1          yes 3406.9331 1500.0000
>  69    0      0    5 5:5:5:1          yes 3406.9331 1500.0000
>  70    0      0    6 6:6:6:1          yes 3406.9331 1500.0000
>  71    0      0    7 7:7:7:1          yes 3406.9331 1500.0000
>  72    0      0    8 8:8:8:2          yes 3406.9331 1500.0000
>  73    0      0    9 9:9:9:2          yes 3406.9331 1500.0000
>  74    0      0   10 10:10:10:2       yes 3406.9331 1500.0000
>  75    0      0   11 11:11:11:2       yes 3406.9331 1500.0000
>  76    0      0   12 12:12:12:3       yes 3406.9331 1500.0000
>  77    0      0   13 13:13:13:3       yes 3406.9331 1500.0000
>  78    0      0   14 14:14:14:3       yes 3406.9331 1500.0000
>  79    0      0   15 15:15:15:3       yes 3406.9331 1500.0000
>  80    0      0   16 16:16:16:4       yes 3406.9331 1500.0000
>  81    0      0   17 17:17:17:4       yes 3406.9331 1500.0000
>  82    0      0   18 18:18:18:4       yes 3406.9331 1500.0000
>  83    0      0   19 19:19:19:4       yes 3406.9331 1500.0000
>  84    0      0   20 20:20:20:5       yes 3406.9331 1500.0000
>  85    0      0   21 21:21:21:5       yes 3406.9331 1500.0000
>  86    0      0   22 22:22:22:5       yes 3406.9331 1500.0000
>  87    0      0   23 23:23:23:5       yes 3406.9331 1500.0000
>  88    0      0   24 24:24:24:6       yes 3406.9331 1500.0000
>  89    0      0   25 25:25:25:6       yes 3406.9331 1500.0000
>  90    0      0   26 26:26:26:6       yes 3406.9331 1500.0000
>  91    0      0   27 27:27:27:6       yes 3406.9331 1500.0000
>  92    0      0   28 28:28:28:7       yes 3406.9331 1500.0000
>  93    0      0   29 29:29:29:7       yes 3406.9331 1500.0000
>  94    0      0   30 30:30:30:7       yes 3406.9331 1500.0000
>  95    0      0   31 31:31:31:7       yes 3406.9331 1500.0000
>  96    1      1   32 32:32:32:8       yes 3406.9331 1500.0000
>  97    1      1   33 33:33:33:8       yes 3406.9331 1500.0000
>  98    1      1   34 34:34:34:8       yes 3406.9331 1500.0000
>  99    1      1   35 35:35:35:8       yes 3406.9331 1500.0000
> 100    1      1   36 36:36:36:9       yes 3406.9331 1500.0000
> 101    1      1   37 37:37:37:9       yes 3406.9331 1500.0000
> 102    1      1   38 38:38:38:9       yes 3406.9331 1500.0000
> 103    1      1   39 39:39:39:9       yes 3406.9331 1500.0000
> 104    1      1   40 40:40:40:10      yes 3406.9331 1500.0000
> 105    1      1   41 41:41:41:10      yes 3406.9331 1500.0000
> 106    1      1   42 42:42:42:10      yes 3406.9331 1500.0000
> 107    1      1   43 43:43:43:10      yes 3406.9331 1500.0000
> 108    1      1   44 44:44:44:11      yes 3406.9331 1500.0000
> 109    1      1   45 45:45:45:11      yes 3406.9331 1500.0000
> 110    1      1   46 46:46:46:11      yes 3406.9331 1500.0000
> 111    1      1   47 47:47:47:11      yes 3406.9331 1500.0000
> 112    1      1   48 48:48:48:12      yes 3406.9331 1500.0000
> 113    1      1   49 49:49:49:12      yes 3406.9331 1500.0000
> 114    1      1   50 50:50:50:12      yes 3406.9331 1500.0000
> 115    1      1   51 51:51:51:12      yes 3406.9331 1500.0000
> 116    1      1   52 52:52:52:13      yes 3406.9331 1500.0000
> 117    1      1   53 53:53:53:13      yes 3406.9331 1500.0000
> 118    1      1   54 54:54:54:13      yes 3406.9331 1500.0000
> 119    1      1   55 55:55:55:13      yes 3406.9331 1500.0000
> 120    1      1   56 56:56:56:14      yes 3406.9331 1500.0000
> 121    1      1   57 57:57:57:14      yes 3406.9331 1500.0000
> 122    1      1   58 58:58:58:14      yes 3406.9331 1500.0000
> 123    1      1   59 59:59:59:14      yes 3406.9331 1500.0000
> 124    1      1   60 60:60:60:15      yes 3406.9331 1500.0000
> 125    1      1   61 61:61:61:15      yes 3406.9331 1500.0000
> 126    1      1   62 62:62:62:15      yes 3406.9331 1500.0000
> 127    1      1   63 63:63:63:15      yes 3406.9331 1500.0000
> ```

@chl178 The output of `lscpu` shows 128 logical CPUs with consecutive L3 IDs while you said it was a `32-Core Processor`. Is it a VM-based environment but the CPU topology info is leaked from the host?

**Comment by chl178** [comment]
I am sure that it is a physical node with two AMD EPYC 7542 in two sockets. And I think the L3 IDs got by `lscpu -e` is not identical with the cache IDs in the RDT schemata.

Part of my output of lscpu:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          128
On-line CPU(s) list:             0-127
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7542 32-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1511.072
CPU max MHz:                     3406.9331
CPU min MHz:                     1500.0000
BogoMIPS:                        5799.95
Virtualization:                  AMD-V
L1d cache:                       2 MiB
L1i cache:                       2 MiB
L2 cache:                        32 MiB
L3 cache:                        256 MiB
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
```
The `/sys/devices/system/cpu/cpu*/cache/index*/id` shows that the cache IDs are in 0-7 and 16-23 which are not contiguous.

**Comment by saintube** [comment]
> @saintube I am sure that it is a physical node with two AMD EPYC 7542 in two sockets. And I think the L3 IDs got by `lscpu -e` is not identical with the ‘’cache IDs‘’ used in the RDT schemata.
> 
> 128 = 32 cores * 2 sockets * 2 threads Part of my output of `lscpu`:
> 
> ```
> Architecture:                    x86_64
> CPU op-mode(s):                  32-bit, 64-bit
> Byte Order:                      Little Endian
> Address sizes:                   43 bits physical, 48 bits virtual
> CPU(s):                          128
> On-line CPU(s) list:             0-127
> Thread(s) per core:              2
> Core(s) per socket:              32
> Socket(s):                       2
> NUMA node(s):                    2
> Vendor ID:                       AuthenticAMD
> CPU family:                      23
> Model:                           49
> Model name:                      AMD EPYC 7542 32-Core Processor
> Stepping:                        0
> Frequency boost:                 enabled
> CPU MHz:                         1511.072
> CPU max MHz:                     3406.9331
> CPU min MHz:                     1500.0000
> BogoMIPS:                        5799.95
> Virtualization:                  AMD-V
> L1d cache:                       2 MiB
> L1i cache:                       2 MiB
> L2 cache:                        32 MiB
> L3 cache:                        256 MiB
> NUMA node0 CPU(s):               0-31,64-95
> NUMA node1 CPU(s):               32-63,96-127
> ```
> 
> The `/sys/devices/system/cpu/cpu*/cache/index*/id` shows that the ‘’cache IDs‘’ are in 0-7 and 16-23 which are not contiguous and same with the IDs used in RDT schemata.

@chl178 It could be a bug for [the lscpu tool](https://github.com/util-linux/util-linux) (maybe fixed in newer versions) to some AMD processors. We can check the kernel files it relies on via `strace`.
For the koordlet, we'd better switch to a more stable interface like `/sys/devices/system/cpu/cpu*/cache/index*/id` to get the L3 cache indexes. This issue can be fixed in the next version v1.5. PRs are also welcome :)

**Comment by chl178** [comment]
@saintube I am a little bit confused about the code of the resctrl part in Koordinator. I have read the [Intel goresctrl Library](https://github.com/intel/goresctrl). While goresctrl does not have the function to get the cache IDs from external resources, in the Koordinator, after verifying the successful mount of resctrl and the correctness of the schemata structure, the code still retrieves the L3 ID using "lscpu." Why can't it directly read the IDs from the schemata? It's like going in a big circle just to confirm cache IDs are "L3 IDs". If the system successfully mounted the resctrl then the IDs generated in schemata must be right, it seems like meaningless to check IDs again except for prevent IDS in schemata from being modified incorrectly by others. However, when you change the id incorrectly, resctrl itself won't allow the change.

**Comment by saintube** [comment]
> Why can't it directly read the IDs from the schemata?

Cause there may be machines that do not support RDT or the system is resctrl unmounted, we should not rely on the resctrl schemata for the basic CPU info. However, it is a good solution when updating the resctrl schemata and retrieving the L3 cache indexes.

**Comment by Rouzip** [comment]
> @chl178 Cause there may be machines that do not support RDT or the system is resctrl unmounted, we should not rely on the resctrl schemata for the basic CPU info. However, it is a good solution when updating the resctrl schemata and retrieving the L3 cache indexes.

During the creation and update of schemata in `ResctrlSchemataRaw`, Koordinator defaults to consecutive cache IDs. As a result, when reconstructing from a `slice` to a `string`, it may lead to the incorrect creation of [L3 schemata](https://github.com/koordinator-sh/koordinator/blob/437ed19563a3bc5bb0a3f42ebd672be92fa0a5f1/pkg/koordlet/util/system/resctrl.go#L248-L250) and [MB schemata](https://github.com/koordinator-sh/koordinator/blob/437ed19563a3bc5bb0a3f42ebd672be92fa0a5f1/pkg/koordlet/util/system/resctrl.go#L262-L264). To fix this issue, can we modify `ResctrlSchemataRaw` to store cache ID information like this?
```go
type ResctrlSchemataRaw struct {
	L3    map[int]int64
	MB    map[int]int64
	L3Num int
}
```

**Comment by saintube** [comment]
> > @chl178 Cause there may be machines that do not support RDT or the system is resctrl unmounted, we should not rely on the resctrl schemata for the basic CPU info. However, it is a good solution when updating the resctrl schemata and retrieving the L3 cache indexes.
> 
> During the creation and update of schemata in `ResctrlSchemataRaw`, Koordinator defaults to consecutive cache IDs. As a result, when reconstructing from a `slice` to a `string`, it may lead to the incorrect creation of [L3 schemata](https://github.com/koordinator-sh/koordinator/blob/437ed19563a3bc5bb0a3f42ebd672be92fa0a5f1/pkg/koordlet/util/system/resctrl.go#L248-L250) and [MB schemata](https://github.com/koordinator-sh/koordinator/blob/437ed19563a3bc5bb0a3f42ebd672be92fa0a5f1/pkg/koordlet/util/system/resctrl.go#L262-L264). To fix this issue, can we modify `ResctrlSchemataRaw` to store cache ID information like this?
> 
> ```go
> type ResctrlSchemataRaw struct {
> 	L3    map[int]int64
> 	MB    map[int]int64
> 	L3Num int
> }
> ```

Yes. It is a good idea.
