### ISSUE TITLE
[question] question about isBECPUUsageHighEnough 

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#1825]
does this mean if only 1 core left for BE pod, we decide BECPUUsageHighEnough?

_Originally posted by @j4ckstraw in https://github.com/koordinator-sh/koordinator/pull/1451#discussion_r1445796553_

**Comment by j4ckstraw** [comment]
https://github.com/koordinator-sh/koordinator/blob/ea0160d512d2bd7592646e6742329ada543da81b/pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go#L241C1-L243C3 may change the logic.

**Comment by saintube** [comment]
> https://github.com/koordinator-sh/koordinator/blob/ea0160d512d2bd7592646e6742329ada543da81b/pkg/koordlet/qosmanager/plugins/cpuevict/cpu_evict.go#L241C1-L243C3 may change the logic.

Nice catch! It is a mistake that regard the BE usage < 1C as a high level. Your comment is correct. /cc @zwzhang0107
