### ISSUE TITLE
HighNodeLoad support

### ISSUE THREAD

**Issue by elvis-cai** [koordinator-sh/koordinator#1842]
The current coordinator includes support for the `LowNodeLoad` plugin, enabling the balancing of pods from nodes with high usage to those that are under-utilized. Notably, the Kubernetes descheduler also offers support for `HighNodeUtilization`, as detailed in their documentation (https://github.com/kubernetes-sigs/descheduler?tab=readme-ov-file#highnodeutilization). 
In light of this, I'm curious to know if there are any plans to integrate support for HighNodeLoad as well. Thank you.

**Comment by eahydra** [comment]
The LowNodeLoad provided by koordinator is optimized for runtime resource utilization and tries to reduce nodes with high load levels. The LowNodeUtilization or HighNodeUtilization in k8s descheduler is biased toward the optimization of resource allocation water levels. We currently have no plans to implement a plugin similar to HighNodeUtilization to keep the node's runtime water level high. If you want to use the native HighNodeUtilization plugin, koord-descheduler is also compatible. If you are willing to implement such a plugin, that would be great!
