### ISSUE TITLE
[proposal] Get node bandwidth automatically for network qos

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#1883]
**What is your proposal**:
In cloud environment, node bandwidth is limited according to the instance type by providers. Define in slo-controller-config is complex since they may various instance types in cluster.

We need to define a protocol on Node, such as annotation called `node-bandwith`. koordinator users can implements their own controller to patch the annotation on node according to the instance type.

koordinator also need to check whether the network qos config is valid for each node and alert if there is something unreasonable.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by sjtufl** [comment]
Split into 2 parts:

1.  Introduce an extension API (through annotation) to specify the total bandwidth for a node. This parameter takes precedence over settings established in the corresponding NodeStrategy or ClusterStrategy for the given node. The annotation will influence the NodeSLO, which is subsequently consumed by the network QoS component.
2.  Implement validation of the total-node-bandwidth configuration within webhook plugins (both node & cm).
