### ISSUE TITLE
[issue] Optimize CPI collect in perfGroup

### ISSUE THREAD

**Issue by Rouzip** [koordinator-sh/koordinator#1884]
**What is your proposal**:
Refactor CPI collection logic, splitting the collection logic for containers that are unrelated.

**Why is this needed**:
In mixed deployment scenarios, the combination of multi-core CPUs and a large number of pods can lead to concentrated syscall invocations during CPI collection, causing spikes in CPU usage.

**Is there a suggested solution, if so, please add it**:
By introducing jitter, the CPI collection logic has been diversified, resulting in a more evenly distributed CPU usage pattern.

**Comment by songtao98** [comment]
@Rouzip By **introducing jitter**, do you refer to add a small delay to the timing of CPI collection events across different container? For this, maybe one simple strategy to divide containers is by QoS or Priority. 

_P.S._ one of my concern is that jitter might affect the precision of CPI data by reflecting container performance at varied times, leading to potential accuracy loss. Anyway, by intuition, this should be acceptable.

**Comment by Rouzip** [comment]
> @Rouzip By **introducing jitter**, do you refer to add a small delay to the timing of CPI collection events across different container? For this, maybe one simple strategy to divide containers is by QoS or Priority.
> 
> _P.S._ one of my concern is that jitter might affect the precision of CPI data by reflecting container performance at varied times, leading to potential accuracy loss. Anyway, by intuition, this should be acceptable.

Thanks for your reply. After double check the code, I found that the high spikes of CPU usage reason is in the wrong implement in **perfGroup** interface. I will fix this issue soon.
