### ISSUE TITLE
[question]按照官方文档部署完v1.4.0版本后，Colocation Profile测试失败

### ISSUE THREAD

**Issue by dongliangwu** [koordinator-sh/koordinator#1888]
**What happened:**
基于官方文档进行了部署，但是部署完成后koord-scheduler组件健康检查失败，查看日志发现是该组件无权限操作storage.k8s.io api group。在rbac中添加上对应的权限后组件可以正常运行。
然后参考文档进行Colocation Profile测试：
profile.yaml为
apiVersion: config.koordinator.sh/v1alpha1
kind: ClusterColocationProfile
metadata:
  name: colocation-profile-example
spec:
  namespaceSelector:
    matchLabels:
      koordinator.sh/enable-colocation: "true"
  selector:
    matchLabels:
      koordinator.sh/enable-colocation: "true"
  qosClass: BE
  priorityClassName: koord-batch
  koordinatorPriority: 1000
  schedulerName: koord-scheduler
  labels:
    koordinator.sh/mutated: "true"
  annotations: 
    koordinator.sh/intercepted: "true"
  patch:
    spec:
      terminationGracePeriodSeconds: 30

nginx pod yaml文件如下：
apiVersion: v1
kind: Pod
metadata:
  labels:
    koordinator.sh/enable-colocation: "true"
  name: test-pod
spec:
  containers:
  - name: app
    image: nginx:1.15.1
    resources:
        limits:
          cpu: "1"
          memory: "3456Mi"
        requests:
          cpu: "1"
          memory: "3456Mi"

**What you expected to happen:**
预期会在pod的labels中添加如下字段：
  labels:
    koordinator.sh/qosClass: BE
    koordinator.sh/priority: 1000
    koordinator.sh/mutated: true

但实际并未出现。

kubectl get mutatingwebhookconfigurations可以看到有对应的mutatingwebhookconfigurations创建成功。
 请问还有哪些排查方法呢？期待尽快回复，非常感谢！

**Environment:**

- Koordinator version: - v1.4.0
- Kubernetes version (use kubectl version): v1.20.13
- docker/containerd version: containerd 1.5.13
- OS (e.g: cat /etc/os-release): RHEL8.6
- Kernel (e.g. uname -a): Linux 4.18.0-372.32.1.el8_6.x86_64 

**Anything else we need to know:**

**Comment by ZiMengSheng** [comment]
For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer, thus the scheduler can work well

**Comment by ZiMengSheng** [comment]
Your profile require namespace should has the label koordinator.sh/enable-colocation: "true", does the namespace has this label?

**Comment by dongliangwu** [comment]
> Your profile require namespace should has the label koordinator.sh/enable-colocation: "true", does the namespace has this label?

namespace中没有这个label，需要我手动添加吗？ 文档里面似乎没有看到需要手动添加这个标签呢，我是用chart部署的

**Comment by ZiMengSheng** [comment]
![image](https://github.com/koordinator-sh/koordinator/assets/20925848/a8daf7d2-0ed6-48a6-9c74-4bea89e04fc6)

> > Your profile require namespace should has the label koordinator.sh/enable-colocation: "true", does the namespace has this label?
> 
> namespace中没有这个label，需要我手动添加吗？ 文档里面似乎没有看到需要手动添加这个标签呢，我是用chart部署的

**Comment by dongliangwu** [comment]
> 需要手动加的，文档里面有提到哦：![image](https://private-user-images.githubusercontent.com/20925848/301410963-a8daf7d2-0ed6-48a6-9c74-4bea89e04fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzA3MTUsIm5iZiI6MTcwNjc3MDQxNSwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MTA5NjMtYThkYWY3ZDItMGVkNi00OGE2LTljNzQtNGJlYTg5ZTA0ZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA2NTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3Yjc4MGUwYTgxYjg3MTBmN2MyZjFhODA2NDhkYTExMzcyMjdhZWY3MmVkMjM2ZDJjYTc1YmU2ZDJlZmRjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-0t-X5ngIA2mWWYwRgZWjqMBy22h4185pPPeHmzfKyI)
> 
> > > Your profile require namespace should has the label koordinator.sh/enable-colocation: "true", does the namespace has this label?
> > 
> > 
> > namespace中没有这个label，需要我手动添加吗？ 文档里面似乎没有看到需要手动添加这个标签呢，我是用chart部署的

修改完已经可以了，非常感谢！！！

**Comment by dongliangwu** [comment]
> For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu

我刚刚查了一下  这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？

**Comment by ZiMengSheng** [comment]
> > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> 
> 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
默认是关闭的，1.20 需要手动开启一下
![image](https://github.com/koordinator-sh/koordinator/assets/20925848/b6f2dc8d-c78b-4ed2-b388-1701bde1cdef)

**Comment by dongliangwu** [comment]
> > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > 
> > 
> > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > 默认是关闭的，1.20 需要手动开启一下
> > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)

部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？

**Comment by ZiMengSheng** [comment]
> > > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > > 
> > > 
> > > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > > 默认是关闭的，1.20 需要手动开启一下
> > > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)
> 
> 部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？
 不好意思，我记错了，可以提供更多细节吗，目前scheduler 不符合预期的现象是啥，测试pod 长啥样子

**Comment by dongliangwu** [comment]
> > > > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > > > 
> > > > 
> > > > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > > > 默认是关闭的，1.20 需要手动开启一下
> > > > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)
> > 
> > 
> > 部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？
> > 不好意思，我记错了，可以提供更多细节吗，目前scheduler 不符合预期的现象是啥，测试pod 长啥样子

不需要任何测试pod，只需要将chart部署起来就可以看到scheduler是running状态但是not ready 查看日志报错是： User "system:serviceaccount:koordinator-system:koord-scheduler"cannot list resource "csidrivers" in API group "storage.k8s.io" at cluster scope.
请问是需要设置v1.4.0版本chart包里面values.yaml中的的scheduler.compatible122FeatureGates和compatibleBelow122FeatureGates字段吗？具体需要怎么设置呢？我尝试设置了一下compatible122FeatureGates改为false似乎还是不行（因为操作的集群在公司电脑所以很多现象图片没办法发送，不好意思）

**Comment by ZiMengSheng** [comment]
> > > > > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > > > > 
> > > > > 
> > > > > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > > > > 默认是关闭的，1.20 需要手动开启一下
> > > > > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)
> > > 
> > > 
> > > 部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？
> > > 不好意思，我记错了，可以提供更多细节吗，目前scheduler 不符合预期的现象是啥，测试pod 长啥样子
> 
> 不需要任何测试pod，只需要将chart部署起来就可以看到scheduler是running状态但是not ready 查看日志报错是： User "system:serviceaccount:koordinator-system:koord-scheduler"cannot list resource "csidrivers" in API group "storage.k8s.io" at cluster scope. 请问是需要设置v1.4.0版本chart包里面values.yaml中的的scheduler.compatible122FeatureGates和compatibleBelow122FeatureGates字段吗？具体需要怎么设置呢？我尝试设置了一下compatible122FeatureGates改为false似乎还是不行（因为操作的集群在公司电脑所以很多现象图片没办法发送，不好意思）

嗯嗯，是的，看起来chart 没问题

**Comment by dongliangwu** [comment]
> > > > > > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > > > > > 
> > > > > > 
> > > > > > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > > > > > 默认是关闭的，1.20 需要手动开启一下
> > > > > > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)
> > > > 
> > > > 
> > > > 部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？
> > > > 不好意思，我记错了，可以提供更多细节吗，目前scheduler 不符合预期的现象是啥，测试pod 长啥样子
> > 
> > 
> > 不需要任何测试pod，只需要将chart部署起来就可以看到scheduler是running状态但是not ready 查看日志报错是： User "system:serviceaccount:koordinator-system:koord-scheduler"cannot list resource "csidrivers" in API group "storage.k8s.io" at cluster scope. 请问是需要设置v1.4.0版本chart包里面values.yaml中的的scheduler.compatible122FeatureGates和compatibleBelow122FeatureGates字段吗？具体需要怎么设置呢？我尝试设置了一下compatible122FeatureGates改为false似乎还是不行（因为操作的集群在公司电脑所以很多现象图片没办法发送，不好意思）
> 
> 嗯嗯，是的，看起来chart 没问题

不太清楚是哪里出了问题 我现在暂时还是使用修改rbac的方式去规避

**Comment by ZiMengSheng** [comment]
> > > > > > > > For kubernetes cluster below 1.20, you need to enable DisableCSIStorageCapacityInformer and CompatibleCSIStorageCapacity, thus the scheduler can work well @dongliangwu
> > > > > > > 
> > > > > > > 
> > > > > > > 我刚刚查了一下 这两个featuregates似乎默认都是开启的，部署的时候我也未做任何修改，请问，还有其他可能的原因吗？
> > > > > > > 默认是关闭的，1.20 需要手动开启一下
> > > > > > > ![image](https://private-user-images.githubusercontent.com/20925848/301420398-b6f2dc8d-c78b-4ed2-b388-1701bde1cdef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI4MDIsIm5iZiI6MTcwNjc3MjUwMiwicGF0aCI6Ii8yMDkyNTg0OC8zMDE0MjAzOTgtYjZmMmRjOGQtYzc4Yi00ZWQyLWIzODgtMTcwMWJkZTFjZGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjc1ODI2ODU0MDFjNmQ3OTk5MzEwMTQ1OTUyMmNkYWY5NzA2ZmMwNWE0YWE2MWM1YWZjMTQ4YTI4MTQ5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2FUKF0cwwTj7eOmvc0z1sRX2FQxRcyrtZQepn9sRQF4)
> > > > > 
> > > > > 
> > > > > 部署包里面value.yaml里面对应的这两个字段我看了一下都是true，所以需要在Helm install的时候手动指定这两个参数值是吧？
> > > > > 不好意思，我记错了，可以提供更多细节吗，目前scheduler 不符合预期的现象是啥，测试pod 长啥样子
> > > 
> > > 
> > > 不需要任何测试pod，只需要将chart部署起来就可以看到scheduler是running状态但是not ready 查看日志报错是： User "system:serviceaccount:koordinator-system:koord-scheduler"cannot list resource "csidrivers" in API group "storage.k8s.io" at cluster scope. 请问是需要设置v1.4.0版本chart包里面values.yaml中的的scheduler.compatible122FeatureGates和compatibleBelow122FeatureGates字段吗？具体需要怎么设置呢？我尝试设置了一下compatible122FeatureGates改为false似乎还是不行（因为操作的集群在公司电脑所以很多现象图片没办法发送，不好意思）
> > 
> > 
> > 嗯嗯，是的，看起来chart 没问题
> 
> 不太清楚是哪里出了问题 我现在暂时还是使用修改rbac的方式去规避

OK，目前看起来就是少了一个rbac 权限，是我们的chart 问题。在加了 rbac 之后，你好像还提到有 preferredCPUBindingPolicy 未生效的情况，那个测试Pod 是啥？

**Comment by saintube** [comment]
@dongliangwu [Release v1.4.1](https://github.com/koordinator-sh/koordinator/releases/tag/v1.4.1) 应该修复了您遇到的问题，请尝试更新到 v1.4.1 及以上的 chart 版本，如果遇到其他问题，欢迎重新打开 issue 反馈～
