### ISSUE TITLE
[proposal] improve coscheduling's log

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1895]
**What is your proposal**:

The logs of CoScheduling Plugin  needs to be optimized to remove unnecessary interference.

E.g.,
https://github.com/koordinator-sh/koordinator/blob/bdaf28494f888eb35ad1ef4904bc3bc54c63bca3/pkg/scheduler/plugins/coscheduling/core/gang.go#L189-L196

**Why is this needed**: 

**Is there a suggested solution, if so, please add it**:

**Comment by googs1025** [comment]
Hello, could you please tell me more details? Is it about adjusting the log level and removing unnecessary log outputs?

**Comment by googs1025** [comment]
@eahydra should we use `klog.V(4).ErrorS()`, This ensures log level printing and also reflects error messages
