### ISSUE TITLE
[question] RunPreFilterPlugins  err

### ISSUE THREAD

**Issue by ls-2018** [koordinator-sh/koordinator#1900]
![image](https://github.com/koordinator-sh/koordinator/assets/38821215/a67f2b28-4d91-4f6e-a7eb-654e10d99064)

This error is caused by a bug in the k8s scheduler RunPreFilterPlugins function. Version 1.25 has been fixed, whether koord will also be fixed, thus exposing real error messages to users

**Comment by eahydra** [comment]
Yes, the current version of koordinator relies on kubernetes v1.24, and this version of kubernetes introduced this issue. We will upgrade to 1.28 in the future.
