### ISSUE TITLE
[proposal] improve LoadAware plugin's Filter based on estimated requests

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1908]
**What is your proposal**:

Currently, the LoadAware plug-in of koord-scheduler supports request estimation in the Score stage, but not in the Filter stage. So we should consider supporting the estimation of the Filter phase to ensure that few newly created Pods are not crowded in the same node and exceed usage.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by zwForrest** [comment]
Is there any progress on this proposal? If not, I am willing to take it.

**Comment by AdrianMachao** [comment]
my  proposal is we should estimate the Pod that just be scheduled that have not reported，if that‘s the case，i will do it @eahydra

**Comment by saintube** [comment]
#1992
