### ISSUE TITLE
[proposal] improve the failed event of Reservation's scheduling

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#1909]
**What is your proposal**:

The reservation plugin of koord-scheduler traverses all reservations with the Restricted policy and determines whether a certain Reservation satisfies the Pod. When all reservations cannot be satisfied, we lose reasonable information, such as which resources cannot be satisfied, which can help users diagnose themselves.

So we should aggregate these messages to users.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by YarBor** [comment]
Hello, I am interested in solving this problem and starting to contribute to the community. Are there any good entry points to understand the code, for example, some test-cases? Or some fields?

**Comment by eahydra** [comment]
> Hello, I am interested in solving this problem and starting to contribute to the community. Are there any good entry points to understand the code, for example, some test-cases? Or some fields?

Welcome! You can start by reading the design documentation in the docs folder. And read the code for reservation scheduling, which is in package pkg/scheduler/plugins/reservation.

BTW, the code to be modified is the Filter method of the Reservation plug-in, and you need to ensure that the error message returned is clearer.

**Comment by eahydra** [comment]
Hi @YarBor , because we need to solve internal needs and need to solve this issue as soon as possible, @ZiMengSheng  will implement it first. If you are interested, you can check out other issues.
