### ISSUE TITLE
[proposal] numa topology policy on pod

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#1912]
**What is your proposal**:

Introduce new api for pod level numa topology policy. With the new api, users can specify numa topology policy for each 
pod, so that pods that are more sensitive to latency can decide how they need to be orchestrated, rather than being passively 
scheduled according to the numa topology policy on the node.

**Why is this needed**:

With numa topology policy set on node, users need to set nodeSelector or nodeAffinity to place the application under the 
same numa. This means to split the nodes in cluster into static groups. In large clusters, with lots of nodes that can serve 
different purposes, it's not unreasonable to dedicate a node (or set of nodes) to a certain numa topology policy, and 
direct pods to those nodes using a nodeSelector. It's mostly problematic in smaller clusters where you don't have the 
luxury of special-purposing nodes like this and you want to binpack pods onto nodes as tightly as possible (while still 
reaping the benefits of topology-alignment). So we need a way to specify numa topology policy for each pod.

**Is there a suggested solution, if so, please add it**:
#1910

**Comment by jasonliu747** [comment]
/close
fixed by #1939
