### ISSUE TITLE
[proposal] Support EulerOS

### ISSUE THREAD

**Issue by fengyehong** [koordinator-sh/koordinator#1915]
**What is your proposal**:
Support [EulerOS](https://en.wikipedia.org/wiki/EulerOS)

**Why is this needed**:

EulerOS also has cgroup features like `cpu.qos_level` `memory.qos_level` to get different qos for different workloads, and it's open-sourced.

AnolisOS is not always available. If koordinator supports more OS(AnolisOS, EulerOS, TencentOS, ...), it can be more widely adopted.

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
sounds good.
contribution is welcomed if you have any interest.
