### ISSUE TITLE
[proposal] make use of batch/mid resource of node capacity

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#1969]
**What is your proposal**:
Change capacity of batch/mid resource to node capacity * reclaimThreshold to make use of capacity field.

https://github.com/koordinator-sh/koordinator/blob/main/pkg/slo-controller/noderesource/plugins/batchresource/plugin.go#L147

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
I agree with you that capacity and allocatable may not be same for batch and mid; besides, I think we need to give the definition about the gap between capacity and allocatable(maybe batch reservation?)

**Comment by j4ckstraw** [comment]
In the beginning, I want to use the capacity to solve Cluster Autoscaler(CA) problem. 
when pod pending CA will scale out new node to satisfy user requests, it will select one node randomly from the cluster, use the allocatable of the node to calculate how many new node needed.
Because the allocatable is always changing, so I want to make capacity be stable to solve the CA problem.

So I think the capacity of batch should be this: `node capacity * reclaim threshold - reserved`, which means the max resource can be used for batch.
