### ISSUE TITLE
MultiArch Support

### ISSUE THREAD

**Issue by hitsub2** [koordinator-sh/koordinator#1998]
**What happened:**
Does koordinator support multiarch?If not, is there workaround to exclude the arm node?

**What you expected to happen:**

**Environment:**

- Koordinator version: - v1.4.1
- Kubernetes version (use kubectl version): v1.29
- docker/containerd version: containerd 1.7.11
- OS (e.g: cat /etc/os-release): Amazon LInux 2
- Kernel (e.g. uname -a): Linux ip-192-168-104-161.ec2.internal 5.10.213-201.855.amzn2.aarch64 #1 SMP Mon Mar 25 18:16:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Anything else we need to know:**

**Comment by saintube** [comment]
The multi-arch image building has been supported since v1.4.0. Please check PR #1697.

**Comment by hitsub2** [comment]
thx.Let me deep dive why it does work on my side.

**Comment by saintube** [comment]
> thx.Let me deep dive why it does work on my side.

OK. Please free feel to let us know if you have other common problems deploying the Koordinator on ARM.

**Comment by hitsub2** [comment]
It seems works fine for now.The reason why it failed is that the pre-registerd plugins was compile on x86.
