### ISSUE TITLE
Performance Collector Scope and specific OS Requirements

### ISSUE THREAD

**Issue by hitsub2** [koordinator-sh/koordinator#2002]
**What happened:**

For different OS, the PSI and CPI would have different exposing directory or names. For examples, in Amazon Linux, when querying PSI, the directory is

```
cat /proc/pressure/cpu
```

But on Alios

```
cat /sys/fs/cgroup/cpuacct/cpu.pressure
```

My question is 

1.what's the behaviour for koordinator to pick up different OS?

2.Any additional configuration should do?

**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.29
- docker/containerd version: containerd 1.7.11
- OS (e.g: cat /etc/os-release): Amazon Linux 2
- Kernel (e.g. uname -a): Linux ip-192-168-74-42.ec2.internal 5.10.213-201.855.amzn2.aarch64 #1 SMP Mon Mar 25 18:16:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
- 
**Anything else we need to know:**

**Comment by zwzhang0107** [comment]
PSI metrics are provided on pod level  and node level.

For pod level, the value is record in cgroup files under kubepods dir. This is supported for both cgroup v1/v2 for anolis kernel but only cgroup v2 for upstream kernel version.
koordinator supports both cgroup v1/v2 in latest version, i think this can work well in any other OS.

For node level, `/proc/pressure/cpu` or `cpu.pressure` in cgroup root dir should be same. Now koordinator only supports `cpu.pressure` in cgroup root. I'm not sure whether PSI is supported in cgroup v1 for Amazon Linux, maybe you can try cgroup v2 in Amazon Linux.

**Comment by Rouzip** [comment]
> **What happened:**
> 
> For different OS, the PSI and CPI would have different exposing directory or names. For examples, in Amazon Linux, when querying PSI, the directory is
> 
> ```
> cat /proc/pressure/cpu
> ```
> 
> But on Alios
> 
> ```
> cat /sys/fs/cgroup/cpuacct/cpu.pressure
> ```
> 
> My question is
> 
> 1.what's the behaviour for koordinator to pick up different OS?
> 
> 2.Any additional configuration should do?
> 
> **What you expected to happen:**
> 
> **Environment:**
> 
> * Koordinator version: - v0.6.2
> * Kubernetes version (use kubectl version): v1.29
> * docker/containerd version: containerd 1.7.11
> * OS (e.g: cat /etc/os-release): Amazon Linux 2
> * Kernel (e.g. uname -a): Linux ip-192-168-74-42.ec2.internal 5.10.213-201.855.amzn2.aarch64 [✨ Add NodeMetric API #1](https://github.com/koordinator-sh/koordinator/pull/1) SMP Mon Mar 25 18:16:08 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
> 
> **Anything else we need to know:**

The Koordinator collects CPI by invoking raw syscall. It is uncertain whether you can collect it within a VM or if you have privileges in a rootless environment.
