### ISSUE TITLE
[PodGroup update phase Error] PodGroup cannot Update phase from Scheduling to Scheduled when gangMember larger than two

### ISSUE THREAD

**Issue by PeterChg** [koordinator-sh/koordinator#2030]
**What happened**:
PodGroup cannot Update phase from Scheduling to Scheduled when gangMembers larger than two。
Regardless of whether all gangMembers have been successfully scheduled and running

....
status:
    phase: Scheduling
    running: 4
    scheduleStartTime: "2024-05-06T13:59:43Z"
    scheduled: 3

**What you expected to happen**:
when all gangMembers have been successfully scheduled and running，PodGroup should  Update phase from Scheduling to Scheduled

**How to reproduce it (as minimally and precisely as possible)**:
Enable gang scheduling， create job with more than one two pods. The more pods, the greater the probability of occurrence

**Anything else we need to know?**:
Occurrence version: 1.3.0

**Environment**:
- App version: 1.3.0
- Kubernetes version (use `kubectl version`): 1.22.3
- Install details (e.g. helm install args): 
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
PTAL /cc @ZiMengSheng @xulinfei1996

**Comment by jasonliu747** [comment]
/close
fix by #2032
