### ISSUE TITLE
REQUEST: New membership for <Suozz>

### ISSUE THREAD

**Issue by Suozz** [koordinator-sh/koordinator#2039]
### GitHub Username

@Suozz

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@zwzhang0107

### Sponsor 2

@saintube

### List of contributions to the Koordinator project

- pr list: https://github.com/koordinator-sh/yarn-copilot/pulls?q=is%3Apr+author%3ASuozz+is%3Aclosed
- design: https://github.com/koordinator-sh/koordinator/discussions/1297

**Comment by zwzhang0107** [comment]
Welcome!!
+1

**Comment by saintube** [comment]
+1
Welcome!
