### ISSUE TITLE
[BUG] Pod Cannot Start When CPUNormalization enable

### ISSUE THREAD

**Issue by LGTH** [koordinator-sh/koordinator#2047]
**What happened**:
When enable CPUNormalization, and scheduler the pod to node,  then kubelet send msg "wirte /sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepodspod-xxxxxxxx/docker-xxxxscope/cpu.cfs_quta_us:    invalid argument\\\"\" unkonw".  then Pod Status is RunContaiinerError.   The Pod request cpu is 4000m but，msg show write  "\\\400000\\\\" to cpu.cfs_quta_us failed.  
Then I delete koordlet, the pod can run successful, When I install koordlet again, the cpu.cfs_quta_us didn't expected reduce. It increase every miniute. I don't understand why.
**What you expected to happen**:
the pod can start, and ajust the request cpu by right， it should write 200000, because the CPUNormalization  rate is 2. And the cfs_quta_us should not increase every minitue.
**How to reproduce it (as minimally and precisely as possible)**:
 
**Anything else we need to know?**:

**Environment**:
- App version: 1.4.1
- Kubernetes version (use `kubectl version`): 1.20.8
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version: RedHat 7.9
  - Kernal version: 4.20.11
  - Cgroup driver: systemd
- Others:

**Comment by saintube** [comment]
@LGTH Could you please show the pod-level cfs quota? It seems due to the pod-level cfs_quota is already adjusted to 200000, which is too small for the container-level cfs_quota to fail the container-level cfs_quota writing.
e.g.
```
echo sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepodspod-xxxxxxxx/cpu.cfs_quta_us
```

If so, it is a race condition that happens in the environment where the container runtime is runc, the cgroup version is v1 and both the runtime-proxy and the [NRI mode](https://koordinator.sh/docs/installation/#optional-enable-nri-mode-resource-management) is not enabled, because the cgroup-v1 cfs_quota requires the parent cgroup to be no less than the child, but the koordlet in standalone mode may decrease the pod-level cfs_quota before the container-level in chance. The CPUNormalization runtime hook is not fully supported for this case, and we will improve this logic in the next versions.

**Comment by LGTH** [comment]
> il the cont



> @LGTH Could you please show the pod-level cfs quota? It seems due to the pod-level cfs_quota is already adjusted to 200000, which is too small for the container-level cfs_quota to fail the container-level cfs_quota writing. e.g.
> 
> ```
> cat sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepodspod-xxxxxxxx/cpu.cfs_quta_us
> ```
> 
> It is expected to be:
> 
> ```
> 200000
> ```
> 
> If so, it is a race condition that happens in the environment where the container runtime is runc, the cgroup version is v1 and both the runtime-proxy and the [NRI mode](https://koordinator.sh/docs/installation/#optional-enable-nri-mode-resource-management) is not enabled. It is because the cgroup-v1 cfs_quota requires the parent cgroup to be no less than the child, but the koordlet in standalone mode may decrease the pod-level cfs_quota before the container-level in chance. The CPUNormalization runtime hook is not fully supported for this case, and we will improve this logic in the next versions. Enabling the runtime-proxy/NRI, switching to cgroup-v2, or using VM-based container runtime also can avoid this issue.

<img width="1357" alt="WX20240517-091431@2x" src="https://github.com/koordinator-sh/koordinator/assets/1981452/b48db993-50b0-4ec3-99db-a44096944f4f">
like the above picture，pod-level cfs quota increase every minitue, but the conainter not.  And I already used  runtime-proxy

**Comment by saintube** [comment]
> > il the cont
> 
> > @LGTH Could you please show the pod-level cfs quota? It seems due to the pod-level cfs_quota is already adjusted to 200000, which is too small for the container-level cfs_quota to fail the container-level cfs_quota writing. e.g.
> > ```
> > cat sys/fs/cgroup/cpu,cpuacct/kubepods.slice/kubepodspod-xxxxxxxx/cpu.cfs_quta_us
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It is expected to be:
> > ```
> > 200000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If so, it is a race condition that happens in the environment where the container runtime is runc, the cgroup version is v1 and both the runtime-proxy and the [NRI mode](https://koordinator.sh/docs/installation/#optional-enable-nri-mode-resource-management) is not enabled. It is because the cgroup-v1 cfs_quota requires the parent cgroup to be no less than the child, but the koordlet in standalone mode may decrease the pod-level cfs_quota before the container-level in chance. The CPUNormalization runtime hook is not fully supported for this case, and we will improve this logic in the next versions. Enabling the runtime-proxy/NRI, switching to cgroup-v2, or using VM-based container runtime also can avoid this issue.
> 
> <img alt="WX20240517-091431@2x" width="1357" src="https://private-user-images.githubusercontent.com/1981452/331427269-b48db993-50b0-4ec3-99db-a44096944f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTAzMjAsIm5iZiI6MTcxNTkxMDAyMCwicGF0aCI6Ii8xOTgxNDUyLzMzMTQyNzI2OS1iNDhkYjk5My01MGIwLTRlYzMtOTlkYi1hNDQwOTY5NDRmNGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMDE0MDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTExZjYwNGMzYTRiYTZhYzI3NjRlM2E5NTg4YWQzYTA3YzY2YzliNTQ1NDc0ZGYwM2JmMzc0MjRlMDBiZGM2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y3mxIwaveFa9c6oLktwIersY667VlCQHlTNobxl1C1s"> like the above picture，pod-level cfs quota increase every minitue, but the conainter not. And I already used runtime-proxy

Did you also enable the CPUBurst feature and set the `cfsQuotaBurstPercent ` since the pod-level cfs_quota was `4000000` instead of `400000`? If so, please disable either the CPUBurst feature or the CPUNormalization feature, since they both control the LS pods' cfs_quota which may not cooperate well in the current version.

**Comment by LGTH** [comment]
@saintube  I disabled CPUBurst feature , but the problem is still occur. Actually My pod is a nginx container, no stress.  Has any other reason?

**Comment by saintube** [comment]
> @saintube I disabled CPUBurst feature (remove brust config or set policy to none), but the problem is still occur. Actually My pod is a nginx container, no stress. Has any other reason? by the way, pod qos calss is LS in the label, other no special.

Strangely, do you mean your pod-level cfs_quota is still increasing even though there are no other koordlet features that can enlarge it? You can try disabling all the runtime hooks so that there should be no thread of the koordlet adjusting the cfs_quota.

**Comment by LGTH** [comment]
I find the problem. As you say, it's  cpuburst caused.  When I turn off(need to set  koordlet damenset args), then it became riht. thanks @saintube
