### ISSUE TITLE
[proposal] Unify the command parameter style of koordlet

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#206]
**What is your proposal**:
Unify the startup parameter style of each component, recommend `Fully POSIX-compliant flags`

**Why is this needed**:

The command parameter styles of `koord-scheduler`, `koord-manager` and `koord-runtime-proxy` basically follow the `POSIX-compliant flags` style, but the style of `koordlet` is relatively independent, such as `KubeletIPAddr`, `KubeletSyncIntervalSeconds`, should we consider unifying them?

![image](https://user-images.githubusercontent.com/832246/171351219-4c77604a-db1a-4600-8d5d-69fae7512771.png)

**Is there a suggested solution, if so, please add it**:

**Comment by jasonliu747** [comment]
some work addressed in PR #304
