### ISSUE TITLE
[question] elastic quota allow-lent-resource 没有生效

### ISSUE THREAD

**Issue by zj619** [koordinator-sh/koordinator#2104]
**What happened:**
新建两个elastic quota，quota1和quota2资源如下
![image](https://github.com/koordinator-sh/koordinator/assets/40164590/d7dcbd93-e9b9-4db0-80b3-1487b3f0842b)
![image](https://github.com/koordinator-sh/koordinator/assets/40164590/57831a70-e54f-4760-ae1e-00c307d9907f)
新建replica为3的deploment，每个pod申请1个cpu，创建该deployment后，只有一个pod运行起来，并没有看到资源借用的效果
![image](https://github.com/koordinator-sh/koordinator/assets/40164590/b790dbf2-10c4-44ba-be6b-b55d3a0d02a0)

![image](https://github.com/koordinator-sh/koordinator/assets/40164590/c9ce4300-2bae-4690-8d45-78eae6a8872e)

**What you expected to happen:**
3个pod都能running
**Environment:**

- Koordinator version: - v1.4.0
- Kubernetes version (use kubectl version): v1.21.3
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by huangjiasingle** [comment]
this issue need reopen!

**Comment by huangjiasingle** [comment]
@saintube  eqs allow-lent-resource not work!  may be the feature not implement in koordiantor?
