### ISSUE TITLE
[question]koordinator yarn跑实时流计算作业

### ISSUE THREAD

**Issue by zj619** [koordinator-sh/koordinator#2109]
如果用koordinator yarn跑实时流计算作业，怎么让流计算任务不被驱逐。目前观察到nm的pod里面有个koordinator.sh/qosClass: BE的配置，另一个是slo-controller-config的host-application-config里面有个qos为BE的配置，这两种有什么区别，怎样做才能满足koordinator yarn跑实时流计算作业不被驱逐？
![f294f410cdd86dcef39903b1d1e172e1](https://github.com/koordinator-sh/koordinator/assets/40164590/c872ee9c-a446-4fd7-b935-88f65bcd1278)

**What happened:**

**What you expected to happen:**

**Environment:**

- Koordinator version: - v1.4.0
- Kubernetes version (use kubectl version): v1.22.3
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by saintube** [comment]
PTAL /cc @zwzhang0107

**Comment by zwzhang0107** [comment]
如开源例会讨论，YANR stream/batch混在一起和k8s混部，这种是不支持的；YARN stream单独和K8s部署不建议通过混部模式。
https://alidocs.dingtalk.com/document/edit?dontjump=true&type=d&dentryKey=paP7wO3nXFnLzMAa&docKey=oJGq769vBG4WnAKe
