### ISSUE TITLE
[dependency] Upgrade github.com/containerd/nri to v0.6.1

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#2131]
**What is your proposal**:

Upgrade the import version of github.com/containerd/nri to v0.6.1.

**Why is this needed**:

Koordinator v1.5.0 depends on the NRI framework of v0.3.0, which was released 10 months ago.
Now the NRI framework has [released v0.6.1](https://github.com/containerd/nri/releases), adding several bug fixes and enhancements. We should upgrade the dependency to take advantage of them.

**Is there a suggested solution, if so, please add it**:

**Comment by kangclzjc** [comment]
Yes, I'll test and upgrade it.
