### ISSUE TITLE
[BUG] Pods been deleted from gang.Children when recreated with same name.

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#2148]
**What happened**:

In my environment, a pod in gang may be recreated with same name.
Pod add event came before pod delete event, which cause this pod is deleted from gang.Children.
This can result in "No enough children in gang" and no pods can get scheduled.

**What you expected to happen**:

gang.Children can be set correctly when pod event came in wrong sequence.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by KunWuLuan** [comment]
We can record pod uid when calling GetId() to get podId, so that pod events sequence will be handled correctly.

**Comment by ZiMengSheng** [comment]
Nice Suggestion! Could you add the detail about why pod event disordered.
