### ISSUE TITLE
[proposal]koord-scheduler：Hope that the Aggregated of the load perception plug-in in Koord-SCHEDULER can take effect when starting

### ISSUE THREAD

**Issue by clay-wangzhi** [koordinator-sh/koordinator#2231]
**What is your proposal**:
当负载感知调度插件中使用 Aggregated ，但由于启动 koordlet 插件，导致 nodemetrics.slo.koordinator.sh 中，没有 maximum period 的值， 就跳过了判断。
我希望，如果 maximum period 中值为空，希望使用 其他 period 中的值，而不是直接跳过。

**Why is this needed**:
koordlet 可能处于刚启动阶段，收集的数据周期较短， 依然希望 koord-scheduler 中负载感知插件的 Aggregated 能生效。

**Comment by clay-wangzhi** [comment]
I would be happy to submit a PR if needed。
https://github.com/koordinator-sh/koordinator/blob/release-1.5/pkg/scheduler/plugins/loadaware/helper.go#L76

**Comment by saintube** [comment]
@clay-wangzhi 您是指当比如节点上 koordlet 冷启动时，节点 nodemetric 的 aggregated 为空的情况下，期望负载感知调度的 aggregated 的阈值可以**降级**采用 nodemetric 的 nodeUsage 这种短时结果是吧。听起来是合理的，如果您有兴趣，欢迎贡献～
