### ISSUE TITLE
[question] Why does the loadaware plugin of the koord-scheduler use the limit for Guaranteed pods and limit * scalingFactor for Burstable pods when estimating Pod resource usage?

### ISSUE THREAD

**Issue by JBinin** [koordinator-sh/koordinator#2232]
**What happened:**
koord-scheduler 的 loadaware 插件会用 `estimatedUsedByResource`  函数对 Pod 进行资源使用量估计，`estimatedUsedByResource` 在预估 Pod 的资源使用量的时候，如果 Pod 的 request 小于 limit，那么就拿 limit 作为估计值，如果request 等于 limit，那么就拿 `limit * scalingFactor`（`scalingFactor` 是一个预设的值，默认情况下 cpu 的 `scalingFactor` 为 85%）作为估计值。
根据 QoS 类别以及对应的运行质量要求，难道不应该在 Guaranteed（`request` 等于 `limit`）情况下预估的越大，而在 Burstable （`request` 小于 `limit`）的情况下可以带有 buffer 的预估，最后调度结果的稳定性越高吗？但是看实现好像正好相反，能否帮忙解答一下，非常感谢。
**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**
```
func estimatedUsedByResource(requests, limits corev1.ResourceList, resourceName corev1.ResourceName, scalingFactor int64) int64 {
	limitQuantity := limits[resourceName]
	requestQuantity := requests[resourceName]
	var quantity resource.Quantity
	if limitQuantity.Cmp(requestQuantity) > 0 {
		scalingFactor = 100
		quantity = limitQuantity
	} else {
		quantity = requestQuantity
	}

	if quantity.IsZero() {
		switch resourceName {
		case corev1.ResourceCPU, extension.BatchCPU:
			return DefaultMilliCPURequest
		case corev1.ResourceMemory, extension.BatchMemory:
			return DefaultMemoryRequest
		}
		return 0
	}

	var estimatedUsed int64
	switch resourceName {
	case corev1.ResourceCPU:
		estimatedUsed = int64(math.Round(float64(quantity.MilliValue()) * float64(scalingFactor) / 100))
		if limit := limitQuantity.MilliValue(); limit > 0 && estimatedUsed > limit {
			estimatedUsed = limit
		}
	default:
		estimatedUsed = int64(math.Round(float64(quantity.Value()) * float64(scalingFactor) / 100))
		if limit := limitQuantity.Value(); limit > 0 && estimatedUsed > limit {
			estimatedUsed = limit
		}
	}
	return estimatedUsed
}
```

**Comment by JBinin** [comment]
@eahydra

**Comment by LY-today** [comment]
I have the same problem

**Comment by DaPengDiting** [comment]
I'm also experiencing this confusion, and I'm glad to see someone bringing it up. I would appreciate it if the author could take a look at this issue.

**Comment by Park-Jiyeonn** [comment]
@JBinin  Thank you for bringing up this issue! I am facing a similar confusion, especially regarding the resource usage estimation for `Guaranteed` and `Burstable` Pods. I would really appreciate it if the maintainers could take a look at this or provide some clarification. Thanks a lot in advance!

**Comment by ZiMengSheng** [comment]
It's a bug, we will remove `scalingFactor = 100`

![image](https://github.com/user-attachments/assets/c2dca820-f52c-4236-91a3-9968d0035903)

**Comment by JBinin** [comment]
If that's possible, I'd be happy to submit a pull request to fix this bug.

**Comment by JBinin** [comment]
> It's a bug, we will remove `scalingFactor = 100`
> 
> ![image](https://private-user-images.githubusercontent.com/20925848/380599891-c2dca820-f52c-4236-91a3-9968d0035903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTc2ODEsIm5iZiI6MTczMDA5NzM4MSwicGF0aCI6Ii8yMDkyNTg0OC8zODA1OTk4OTEtYzJkY2E4MjAtZjUyYy00MjM2LTkxYTMtOTk2OGQwMDM1OTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA2MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTQzZTYwNjZlMWYwOGVhMDgzMTBmOTE0ZjVkNTA1NzA0NWQ4Yzk2ZDhmZDFlZmFmZWViYWQyMWYxOGUwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZMm-W04awwCATfZu27oOefJsMNGf35iI3sIV52oocHc)

If that's possible, I'd be happy to submit a pull request to fix this bug.

**Comment by ZiMengSheng** [comment]
> > It's a bug, we will remove `scalingFactor = 100`
> > ![image](https://private-user-images.githubusercontent.com/20925848/380599891-c2dca820-f52c-4236-91a3-9968d0035903.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTc2ODEsIm5iZiI6MTczMDA5NzM4MSwicGF0aCI6Ii8yMDkyNTg0OC8zODA1OTk4OTEtYzJkY2E4MjAtZjUyYy00MjM2LTkxYTMtOTk2OGQwMDM1OTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA2MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTQzZTYwNjZlMWYwOGVhMDgzMTBmOTE0ZjVkNTA1NzA0NWQ4Yzk2ZDhmZDFlZmFmZWViYWQyMWYxOGUwN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZMm-W04awwCATfZu27oOefJsMNGf35iI3sIV52oocHc)
> 
> If that's possible, I'd be happy to submit a pull request to fix this bug.

oo, i submitted a PR before seeing this message
