### ISSUE TITLE
support of fine-grained cpu orchestration in koordlet

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#229]
**What is your proposal**:

Compatible with kubelet's existing CPU management policies. The CPU manager policy static allows pods with certain resource characteristics to be granted increased CPU affinity and exclusivity in the node. If enabled the static policy, the cluster administrator must configure the kubelet reserve some CPUs. There are some options for static policy. If the full-pcpus-only(beta, visible by default) policy option is specified, the static policy will always allocate full physical cores. If the distribute-cpus-across-numa(alpha, hidden by default) option is specified, the static policy will evenly distribute CPUs across NUMA nodes in cases where more than one NUMA node is required to satisfy the allocation.

Similarly, the semantics of the existing K8s Guaranteed Pods in the community should be compatible. The cpu cores allocated to K8s Guaranteed Pods with static policy will not share to the default best effort Pods, so it is equivalent to LSE. But when the load in the node is relatively low, the CPUs allocated by LSR Pods should be shared with best effort workloads to obtain economic benefits.

More details please refer to #96 

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:
- [x] #232 
    - [x] v0.5 #264 
    - [x] v0.6 #345 
- [x] #233 
    - [x] v0.5 #265
    - [x] v0.6 #346
- [x] v0.6 #234

**Comment by zwzhang0107** [comment]
#232 
#233 
#234
