### ISSUE TITLE
REQUEST: New membership for cheimu

### ISSUE THREAD

**Issue by cheimu** [koordinator-sh/koordinator#249]
### GitHub Username

@cheimu

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jasonliu747

### Sponsor 2

@honpey

### List of contributions to the Koordinator project
PR https://github.com/koordinator-sh/koordinator/pull/251
PR https://github.com/koordinator-sh/koordinator/pull/247
PR https://github.com/koordinator-sh/koordinator/pull/243
PR https://github.com/koordinator-sh/koordinator/pull/239
PR https://github.com/koordinator-sh/koordinator/pull/238
PR https://github.com/koordinator-sh/koordinator/pull/231
PR https://github.com/koordinator-sh/koordinator/pull/220
PR https://github.com/koordinator-sh/koordinator/pull/127

**Comment by jasonliu747** [comment]
+1

**Comment by honpey** [comment]
+1

**Comment by cheimu** [comment]
/cc @hormes 

Thanks for invitation. It's so exciting.

**Comment by hormes** [comment]
+1 
Welcome to join, hope you have a pleasant experience.
