### ISSUE TITLE
[proposal]Increase unittests coverage to 70%

### ISSUE THREAD

**Issue by hormes** [koordinator-sh/koordinator#288]
![image](https://user-images.githubusercontent.com/4395943/174957384-c1fa5f1f-488f-4f71-94d5-50f8c14f0d51.png)

- [ ] koordlet pkg
- [ ] runtime proxy pkg
- [ ] util pkg
- [x] #193 
- [x] #107

**Comment by jasonliu747** [comment]
some work addressed in #374

**Comment by jasonliu747** [comment]
![image](https://user-images.githubusercontent.com/24452340/179937517-7959a8b9-839a-4f9c-93e5-b6346af6b633.png)
![image](https://user-images.githubusercontent.com/24452340/179937676-e227f227-1eaf-41d3-b941-2e5035385b0d.png)
