### ISSUE TITLE
[proposal] enhance Load-aware scheduling adopts different strategies according to the difference of workload type

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#314]
**What is your proposal**:

Load-aware scheduling adopts different strategies according to the difference of workload type.

**Why is this needed**:

Currently, load-aware scheduling does not distinguish the type of workloads, and only evaluates it according to the current load status of the node and the estimated value of the Pod. This approach also works efficiently, but it would be better if we supported some scheduling strategy for the workload type.

The situation caused by the current method is that the utilization among the nodes of the entire cluster is relatively balanced, but the utilization of latency-sensitive applications and best-effort applications is unbalanced.

If there are many BestEffort Pods scheduled in one Node, the latency-sensitive Pods may fail to schedule cause the load of node has reached the limit of usage.   

So we can do some optimizations and enhancements:

For latency-sensitive(LSE/LSR/LS) Pods, priority is given to scheduling to the nodes with low total utilization of the Prod Pods. BestEffort(BE) Pods are scheduled according to the utilization level of the whole node.  

**Is there a suggested solution, if so, please add it**:

**Comment by hormes** [comment]
Cool, does anyone in the community want to participate in the development of the scheduler feature?
