### ISSUE TITLE
[proposal] scheduler support device(.like gpu\rdma) card level schedule

### ISSUE THREAD

**Issue by buptcozy** [koordinator-sh/koordinator#321]
**What is your proposal**:
scheduler can schedule devices like gpu\rdma in card level

**Why is this needed**:
 for better schedule result, such as NvLink in A100\V100, Mig in A100, Nvlink with RDMA... etc

**Is there a suggested solution, if so, please add it**:
1. a new device reporter in koordlet can report card level device crd, which will not conflict with kubelet and existed device plugin
2. scheduler schedule pod with device card level
3. runtime-proxy use scheduler device schedule result to overwrite kubelet\device-plugin card assign result

more-detail please see:
https://github.com/koordinator-sh/koordinator/pull/322

**Comment by hormes** [comment]
awesome, looking forward to the expanded design docs

**Comment by yihuifeng** [comment]
Cozy has rich experience on resource scheduling, especially GPU related.   It is the first time we make such a proposal for AI scenario.

**Comment by fredkan** [comment]
the design can consider the hca level schedule for rdma. For rdma often be used in shared mode by multi pods in one node.
