### ISSUE TITLE
[proposal] scheduler support batchpod scheduling

### ISSUE THREAD

**Issue by buptcozy** [koordinator-sh/koordinator#331]
**What is your proposal**:
scheduler support batchpod scheduling

**Why is this needed**:
in some AI scenarios,  we may want  a batch of pods have strong relationships:
1. in gpu senario, when one cluster has multi-type-gpu-model nodes like P100 and V100, we want one job's worker run in same gpu-model nodes to avoid large speed gap between different gpu-model.  This may lead not only efficiency problem, but also correction problem.
2. in gpu nvlink scenario, we want to pack one job's pods in a best-nvlink-topo result in one card or between multi-card

**Is there a suggested solution, if so, please add it**:
https://github.com/koordinator-sh/koordinator/pull/341

**Comment by jasonliu747** [comment]
/close
I'll close this due do inactivity temporarily. Feel free to re-open it.
