### ISSUE TITLE
[proposal]Collect metrics data from the kubelet instead of the cgroup.

### ISSUE THREAD

**Issue by LambdaHJ** [koordinator-sh/koordinator#342]
**What is your proposal**:
Collect resource used metrics of node/pod  from kubelet instead of cgroup.
Kubelet has exported metircs by cAdvisor, We can collect metircs from kubelet directly.

**Why is this needed**:
Shield  the differences of CGroup V1 and V2

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
metrics from cAdvisor is limited both on precision and type
strategies in koordlet need more fine-grained metric, so instead of using cadvisor, we should consider the adaption of cgroup v2.
