### ISSUE TITLE
[BUG] koord-runtime-proxy report "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by wangxiaoq** [koordinator-sh/koordinator#352]
**What happened**:

After I deployed koordinator 0.5.0 and the koord-runtime-proxy, when I submit a pod with labels `koordinator.sh/enable-colocation: "true"`, the koord-runtime-proxy won't work and reported: 

```
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: I0708 15:01:25.128852  195448 pod.go:58] get pod info successful caa0e0e87a15124a051d517731ec0782e559f8659a9113a28a56411e2f3034c5
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: [signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x172b152]
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: goroutine 120 [running]:
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/resexecutor/cri.(*PodResourceExecutor).UpdateRequest(0xc000b2a070, 0x0, 0x0, 0x1af6100, 0xc00066e8e8, 0x1bd0e37, 0x7)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/resexecutor/cri/pod.go:132 +0x72
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/server/cri.(*RuntimeManagerCriServer).interceptRuntimeRequest(0xc000a683c0, 0x1, 0x1e3e740, 0xc0007116e0, 0x1af6100, 0xc00066e8e8, 0xc0003b5b20, 0x0, 0x0, 0x0, ...)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/server/cri/criserver.go:111 +0xa45
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: github.com/koordinator-sh/koordinator/pkg/runtimeproxy/server/cri.(*RuntimeManagerCriServer).StopPodSandbox(0xc000a683c0, 0x1e3e740, 0xc0007116e0, 0xc00066e8e8, 0xc000a683c0, 0xc0007116e0, 0xc000151ba0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/projects/koordinator/pkg/runtimeproxy/server/cri/runtime.go:41 +0x8e
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: k8s.io/cri-api/pkg/apis/runtime/v1alpha2._RuntimeService_StopPodSandbox_Handler(0x1b81b20, 0xc000a683c0, 0x1e3e740, 0xc0007116e0, 0xc00016aba0, 0x0, 0x1e3e740, 0xc0007116e0, 0xc000495bd0, 0x42)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/k8s.io/cri-api@v0.22.6/pkg/apis/runtime/v1alpha2/api.pb.go:8070 +0x217
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60, 0xc0006522a0, 0x29fd150, 0x0, 0x0, 0x0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).handleStream(0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60, 0x0)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0001bb920, 0xc000530540, 0x1e51858, 0xc000afe180, 0xc000b67e60)
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:934 +0xab
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Jul 08 15:01:25 xxx.xxx.xxx.xxx koord-runtime-proxy[195448]:         /root/go/pkg/mod/google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
```

The service file of koord-runtime-proxy is:

```
[Unit]
Description=Koordinator koord-runtime-proxy
Documentation=https://github.com/koordinator-sh/koordinator

[Service]
ExecStart=/usr/bin/koord-runtime-proxy  \
  --remote-runtime-service-endpoint=/var/run/containerd/containerd.sock \
  --remote-image-service-endpoint=/var/run/containerd/containerd.sock

Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**What you expected to happen**:

koord-runtime-proxy works properly.

**How to reproduce it (as minimally and precisely as possible)**:

1. deploy koordinator following the doc: https://koordinator.sh/docs/installation
2. create a pod with label: `koordinator.sh/enable-colocation: "true"`

**Environment**: CentOS Linux release 8.2.2004 (Core)
- App version: 0.5.0
- Kubernetes version (use `kubectl version`):  1.21.0
- Install details (e.g. helm install args):
- Others:

**Comment by jasonliu747** [comment]
Hi @wangxiaoq , thanks for reporting this issue. 
What is the content of json files under `cat /etc/runtime/hookserver.d/`?

**Comment by wangxiaoq** [comment]
It seems nothing under `/etc/runtime/hookserver.d/` directory

**Comment by novahe** [comment]
According to the error stack,
 ```
(*PodResourceExecutor).UpdateRequest(0xc000b2a070, 0x0, 0x0, 0x1af6100, 0xc00066e8e8, 0x1bd0e37, 0x7)
````
the frist parameter `rsp` of (*PodResourceExecutor).UpdateRequest is nil.
Flow the function logic：
https://github.com/koordinator-sh/koordinator/blob/1328009c2395d7c9362475f0950fed626049e844/pkg/runtimeproxy/dispatcher/dispatcher.go#L67-L90
the code reaches 90 lines. Therefore, the configuration may be incorrect.

**Comment by wangxiaoq** [comment]
@novahe thanks for your reply, I follow the doc: https://koordinator.sh/docs/installation to deploy.

**Comment by jasonliu747** [comment]
I apologize that the installation docs may not be detailed enough. Could you follow this one and try again? https://koordinator.sh/docs/designs/runtime-proxy#how-to-register-plugins

**Comment by wangxiaoq** [comment]
> I apologize that the installation docs may not be detailed enough. According to your error log, it seems like you haven't registerd any plugin. Could you follow this one and try again? https://koordinator.sh/docs/designs/runtime-proxy#how-to-register-plugins

I don't find `/var/run/koordlet-runtimehookserver.sock` on the host, only find `/var/run/koordlet/koordlet.sock`

**Comment by jasonliu747** [comment]
/assign @honpey 
PTAL

**Comment by zwzhang0107** [comment]
it see

> > I apologize that the installation docs may not be detailed enough. According to your error log, it seems like you haven't registerd any plugin. Could you follow this one and try again? https://koordinator.sh/docs/designs/runtime-proxy#how-to-register-plugins
> 
> I don't find `/var/run/koordlet-runtimehookserver.sock` on the host, only find `/var/run/koordlet/koordlet.sock`, but it doesn't work

it seems that the [doc](https://koordinator.sh/docs/designs/runtime-proxy/#how-to-register-plugins) does not follow the default config of [koordlet chart](https://github.com/koordinator-sh/charts/blob/main/versions/v0.5.0/templates/koordlet.yaml#L34), please change the remote endpoint in "/etc/runtime/hookserver.d/koordlet.json" to /var/run/koordlet/koordlet.sock.

we will fix the doc asap

**Comment by hormes** [comment]
[fix doc]( https://github.com/koordinator-sh/website/pull/64)

**Comment by wangxiaoq** [comment]
@zwzhang0107 @hormes thanks for fixing the doc, I follow the new doc, but the problem still exists
