### ISSUE TITLE
[support request] The Compatibility Problem of Koordinator in KIND Scenario.

### ISSUE THREAD

**Issue by ZiMengSheng** [koordinator-sh/koordinator#369]
**What is your problem or scenario?**
**The Compatibility Problem of Koordinator in KIND Scenario.**
**Procedure**
_step 1._ Install docker, KIND in local MAC machine.
_step 2._ Create a cluster by kind.
_step 3._ Install Koordinator in the cluster created in step2.
**Problem**
1. We can discover that koordlet is always restarting, as shown in figure：
<img width="978" alt="截屏2022-07-13 21 48 38" src="https://user-images.githubusercontent.com/20925848/178937705-99be2cdd-8877-46ca-b3d8-161a986dd5ec.png">

2. check logs of this pod：
<img width="1176" alt="截屏2022-07-13 21 51 54" src="https://user-images.githubusercontent.com/20925848/178937860-acd10062-c322-4055-b65f-7dde6eaf1b4e.png">

3. we can see that koordelet can't detect kubelet cgroup driver and the error log location is koordlet.go line 87 and line 83:
<img width="959" alt="截屏2022-07-13 21 55 21" src="https://user-images.githubusercontent.com/20925848/178938166-3029bee5-59ec-4b2b-8d7f-97de856f17e8.png">

**Comment by saintube** [comment]
@ZiMengSheng Could you please show us the output when executing commands below?

```
$ # execute in any of KinD nodes
$ ls -l /sys/fs/cgroup/cpu
$ ps -ef | grep "kubelet"
```

**Comment by ZiMengSheng** [comment]
> @ZiMengSheng Could you please show us the output when executing the commands below?
> 
> ```
> $ # execute on a KinD node
> $ ls -l /sys/fs/cgroup/cpu
> $ ps -ef | grep "kubelet"
> ```
@saintube Okay. The output of command `ls -l /sys/fs/cgroup/cpu` as follows:
![image](https://user-images.githubusercontent.com/20925848/179646510-d9e9e670-25ce-447b-8d31-29416e412425.png).
The output of command `ps -ef | grep "kubelet"` as follows:
![image](https://user-images.githubusercontent.com/20925848/179646691-eb559180-e859-4d03-9dc8-25d0ba2685bf.png)

**Comment by saintube** [comment]
@ZiMengSheng OK... Now I know the real reason.  
KinD nodes enables [cgroups-v2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html), while koordlet currently requires cgroups-v1 system. Could you please set cgroups-v1 in KinD nodes so the koordlet would identify the cgroups paths correctly?

**Comment by ZiMengSheng** [comment]
I have set cgroups-v1 in KinD node. But koordlet doesn't identify cgroups paths. this is the contents of 
/sys/fs/cgroup/cpu.
![image](https://user-images.githubusercontent.com/20925848/180122137-e0559e77-a480-419b-89cc-7d7320d45e9d.png)

**Comment by saintube** [comment]
@ZiMengSheng It seems KinD also change the cgroups root configuration of kubelet. Could you please check the `CgroupRoot` configured in your KinD nodes.  
FYI: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

e.g.
```bash
grep -i "cgroup" /var/lib/kubelet/config.yaml
```

**Comment by ZiMengSheng** [comment]
this is the output of `grep -i "cgroup" /var/lib/kubelet/config.yaml`
```
cgroupDriver: systemd
cgroupRoot: /kubelet
```
but I can't cd into /kubelet

**Comment by saintube** [comment]
> @saintube this is the output of `grep -i "cgroup" /var/lib/kubelet/config.yaml`
> 
> ```
> cgroupDriver: systemd
> cgroupRoot: /kubelet
> ```
> 
> but I can't cd into /kubelet

@ZiMengSheng I think `cgroupRoot` represents a sub-path of the real kubelet cgroup root. Could you please check the sub directories of your `/sys/fs/cgroup/kubelet.slice` or `/sys/fs/cgroup/kubelet`. Then you may get a cgroup sub-path named`kubepods.slice`, which is the wanted cgroup root of kubelet.

**Comment by ZiMengSheng** [comment]
yes, you may be right.
maybe this path
![image](https://user-images.githubusercontent.com/20925848/180229715-de491dd7-1709-4c9f-9a77-5d3fbd87c870.png)

**Comment by saintube** [comment]
> yes, you may be right. this is the path similar to your cgrouppath, but named kubelet-kubepods.slice. ![image](https://user-images.githubusercontent.com/20925848/180229715-de491dd7-1709-4c9f-9a77-5d3fbd87c870.png)

@ZiMengSheng So KinD uses a custom `CgroupRoot` for the Kubelet, which Koordlet does not currently support. Koordlet uses the default cgroup path of Kubelet since we often keep this configuration unchanged. This is a compatibility issue and Koordlet needs to support custom cgroup root, WDYT @zwzhang0107 @jasonliu747

**Comment by jasonliu747** [comment]
I assume kind is for local development environment only, not production use. And yes, we definitely can support it in the future release.  But right now, I think the best for us is to add it into known issues list.

**Comment by zwzhang0107** [comment]
current koordlet only support cgroup v1
`cgroup path` configuration has been supported, consider adding a feature-gate for KinD to support cgroup path prefix

**Comment by jasonliu747** [comment]
/close
Let's track this in #407
