### ISSUE TITLE
REQUEST: New membership for  LambdaHJ

### ISSUE THREAD

**Issue by LambdaHJ** [koordinator-sh/koordinator#388]
### GitHub Username

@LambdaHJ

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jasonliu747

### Sponsor 2

@zwzhang0107

### List of contributions to the Koordinator project

PR #361 
PR #180 
PR #320

**Comment by jasonliu747** [comment]
+1
@LambdaHJ has actively contributed to koordlet and I am excited to have him as part of our contributor group.

**Comment by zwzhang0107** [comment]
+1
Welcome!!

**Comment by eahydra** [comment]
+1 
Welcome! 🎉🎉🎉

**Comment by hormes** [comment]
@LambdaHJ I have sent an invitation, please check your email.
