### ISSUE TITLE
[BUG] Koordinator's priority and qos docs not found

### ISSUE THREAD

**Issue by tongchao199** [koordinator-sh/koordinator#39]
**What happened**:

* Koordinator's priority and qos docs not found
  - abnormal url address
    https://koordinator.sh/docs/core-concepts/resource-model/priority
    https://koordinator.sh/docs/core-concepts/architecture/qos

    ![image](https://user-images.githubusercontent.com/18660867/161910407-bc5ff6c4-c703-4fd1-8e2f-f70a4d12749b.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by jasonliu747** [comment]
Hi @tongchao199, thanks for the report. Could you let me know in what page did you find these two links?
The correct links should be:
- https://koordinator.sh/docs/core-concepts/priority
- https://koordinator.sh/docs/core-concepts/qos

**Comment by hormes** [comment]
Hi @tongchao199, we can't reproduce this issue, do you still have problems there?

**Comment by hormes** [comment]
It has been fixed, if there is a problem, reopen it

**Comment by tongchao199** [comment]
> Hi @tongchao199, we can't reproduce this issue, do you still have problems there?

This may be a CDN cache problem
