### ISSUE TITLE
Is there a slack channel or dingtalk group for koordinator?

### ISSUE THREAD

**Issue by cheimu** [koordinator-sh/koordinator#40]
Hi community, 

I'm new to koordinator and curious about some features about it. Is there a group or community meeting to discuss about it? Seems like this project is in the very early stage of open sourcing. 😄

**Comment by jasonliu747** [comment]
@cheimu Yes, you are welcome to join our Dintalk Group. Group num is: **33383887**

**Comment by hormes** [comment]
[join slack](https://join.slack.com/t/koordinator-sh/shared_invite/zt-1756qoub4-Cn4~esfdlfAPsD7cwO2NzA)
