### ISSUE TITLE
[BUG]README.md LICENSE linked error

### ISSUE THREAD

**Issue by MorganMaxg** [koordinator-sh/koordinator#44]
**What happened**:
README.md LICENSE linked error. `LICENSE.md` cannot be found.
**What you expected to happen**:
fix LICENSE.md to LICENSE in README.md
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Others:

**Comment by jasonliu747** [comment]
@MorganMaxg Nice catch! Would you like to submit a PR to fix this?

**Comment by MorganMaxg** [comment]
> @MorganMaxg Nice catch! Would you like to submit a PR to fix this?

OK
