### ISSUE TITLE
[proposal] slo-controller should record events when failed to unmarshal configmap or pod qos config annotation

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#482]
**What is your proposal**:

The slo-controller should record events when failed to unmarshal configmap or pod's qos config on annotation.

When we want to update the configurations for the koordlet or resource overcommitment, we modify the json data in the slo-controller-config (a configmap in the namespace koordinator-system), and the slo-controller parses the data into node-level configs (in CRD nodeslos, nodemetrics). But when we submit invalid config or make some typos, the node-level configs just change unexpectedly (use the default values or keep a old version).

To make the unmarshal failures more observable, we hope the slo-controller:

1. record some events on the configmap when it failed to unmarshal the configs
2. record events on the pod when it failed to unmarshal the qos configs on the pod annotations.

**Why is this needed**:

We expect the events on the slo-controller-config can help us find the unmarshal failures fast and accurately.

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
also add event to pod if annotation specifies wrong qos config such as cpuBrust/memoryQOS
