### ISSUE TITLE
when deploy on ACK 1.18.1 koord-manager pod always crash

### ISSUE THREAD

**Issue by cao99** [koordinator-sh/koordinator#49]
logs of koord-manager pod：
==========================
W0407 10:06:26.017519       1 noderesource.go:234] node koordinator.sh/batch-memory resource diff bigger than 0.1, need sync
W0407 10:06:26.032565       1 noderesource.go:234] node koordinator.sh/batch-memory resource diff bigger than 0.1, need sync
W0407 10:06:30.192036       1 noderesource.go:234] node koordinator.sh/batch-memory resource diff bigger than 0.1, need sync
W0407 10:06:30.212145       1 noderesource.go:234] node koordinator.sh/batch-memory resource diff bigger than 0.1, need sync
I0407 10:06:35.111049       1 request.go:597] Waited for 55.075105ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/alert.alibabacloud.com/v1beta1?timeout=32s
I0407 10:06:35.145232       1 request.go:597] Waited for 89.253202ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/autoscaling/v2beta2?timeout=32s
I0407 10:06:35.178362       1 request.go:597] Waited for 122.38075ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
I0407 10:06:35.211422       1 request.go:597] Waited for 155.435651ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/autoscaling/v2beta1?timeout=32s
I0407 10:06:35.244458       1 request.go:597] Waited for 188.457989ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/storage.kubesphere.io/v1alpha1?timeout=32s
I0407 10:06:35.278526       1 request.go:597] Waited for 222.531793ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/tenant.kubesphere.io/v1alpha1?timeout=32s
I0407 10:06:35.311777       1 request.go:597] Waited for 255.783658ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/batch/v1?timeout=32s
I0407 10:06:35.344844       1 request.go:597] Waited for 288.851137ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/authentication.k8s.io/v1?timeout=32s
I0407 10:06:35.377888       1 request.go:597] Waited for 321.886237ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.410868       1 request.go:597] Waited for 354.862882ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/authorization.k8s.io/v1?timeout=32s
I0407 10:06:35.445056       1 request.go:597] Waited for 389.044635ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/application.kubesphere.io/v1alpha1?timeout=32s
I0407 10:06:35.478284       1 request.go:597] Waited for 422.284091ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/rbac.authorization.k8s.io/v1?timeout=32s
I0407 10:06:35.511365       1 request.go:597] Waited for 455.363074ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/config.koordinator.sh/v1alpha1?timeout=32s
I0407 10:06:35.544428       1 request.go:597] Waited for 488.423354ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.577530       1 request.go:597] Waited for 521.517315ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/monitoring.coreos.com/v1?timeout=32s
I0407 10:06:35.611734       1 request.go:597] Waited for 555.722446ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/discovery.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.645163       1 request.go:597] Waited for 589.153428ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/node.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.678261       1 request.go:597] Waited for 622.239304ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/scheduling.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.710979       1 request.go:597] Waited for 654.969336ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/authentication.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.745052       1 request.go:597] Waited for 689.04109ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/networking.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.778181       1 request.go:597] Waited for 722.153387ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
I0407 10:06:35.811371       1 request.go:597] Waited for 755.351178ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/policy/v1beta1?timeout=32s
I0407 10:06:35.844491       1 request.go:597] Waited for 788.468955ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/apps.kruise.io/v1alpha1?timeout=32s
I0407 10:06:35.878183       1 request.go:597] Waited for 822.161498ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/networking.k8s.io/v1?timeout=32s
I0407 10:06:35.911844       1 request.go:597] Waited for 855.812499ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/coordination.k8s.io/v1?timeout=32s
I0407 10:06:35.944926       1 request.go:597] Waited for 888.890657ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/cluster.kubesphere.io/v1alpha1?timeout=32s
I0407 10:06:35.978193       1 request.go:597] Waited for 922.169979ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/apps.kruise.io/v1beta1?timeout=32s
I0407 10:06:36.011313       1 request.go:597] Waited for 955.28796ms due to client-side throttling, not priority and fairness, request: GET:https://192.168.124.1:443/apis/scheduling.k8s.io/v1?timeout=32s
E0407 10:06:36.016423       1 deleg.go:144] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"NodeSLO\" in version \"slo.koordinator.sh/v1alpha1\""  "kind"={"Group":"slo.koordinator.sh","Kind":"NodeSLO"}
================================

ps: 192.168.124.1 is the svc "kubernetes" in default namespace.

**Comment by cao99** [comment]
192.168.124.1 is the svc kubernetes in default namespace.

**Comment by jasonliu747** [comment]
@cao99 Hi, NodeSLO CRD was missing earlier, it shoud be fixed now. 
Please reinstall Koordinator using Helm with the latest chart and let us know if this issue is not resolved.

**Comment by eahydra** [comment]
@cao99 Hi, thanks for the feedback. The issue has been fixed, please reinstall the koordinator with latest charts.

**Comment by cao99** [comment]
![image](https://user-images.githubusercontent.com/39616902/162358885-e69fdc25-eec6-4927-907e-88d7db33b040.png)
after update NodeSLO CRD created，but meet the same error in logs

**Comment by eahydra** [comment]
> 

It doesn't look like it's installed correctly. Please uninstall and force update the chart package and install it again.
If installed correctly, there is CRD named `nodeslos.slo.koordinator.sh` in cluster.

**Comment by cao99** [comment]
after reinstall working now！

**Comment by cao99** [comment]
after reinstall working now！thks ！
