### ISSUE TITLE
REQUEST: New membership for j4ckstraw

### ISSUE THREAD

**Issue by j4ckstraw** [koordinator-sh/koordinator#525]
### GitHub Username

j4ckstraw

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@jasonliu747

### Sponsor 2

@saintube

### List of contributions to the Koordinator project

issues:
https://github.com/koordinator-sh/koordinator/issues/221
https://github.com/koordinator-sh/koordinator/issues/459

PRs:
https://github.com/koordinator-sh/koordinator/pull/248
https://github.com/koordinator-sh/koordinator/pull/460

**Comment by jasonliu747** [comment]
+1
We would love to have you onboard!

**Comment by saintube** [comment]
+1
Welcome! 🎉🎉🎉

**Comment by eahydra** [comment]
Welcome!

**Comment by jasonliu747** [comment]
Invitation has been sent, welcome to this community.
