### ISSUE TITLE
REQUEST: New membership for songtao98

### ISSUE THREAD

**Issue by songtao98** [koordinator-sh/koordinator#527]
### GitHub Username

@songtao98

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [x] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [x] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@zwzhang0107

### Sponsor 2

@jasonliu747

### List of contributions to the Koordinator project

issues:
#482  
#496 

PRs:
#505 
#518 
#526 
#540

**Comment by jasonliu747** [comment]
+1
Welcome! Thanks for your contributions so far.

**Comment by eahydra** [comment]
Welcome!

**Comment by jasonliu747** [comment]
Invitation has been sent, welcome to this community.
