### ISSUE TITLE
[feature request] set cgroup value by batch-request/limit for BE pod 

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#53]
**What would you like to be added**:

**Why is this needed**:

**Comment by zwzhang0107** [comment]
extend resource requires request==limit, so we should support `limit.batch-cpu` and `limit.batch-memory` on annotation field.
cc @jasonliu747

**Comment by jasonliu747** [comment]
> extend resource requires request==limit, so we should support `limit.batch-cpu` and `limit.batch-memory` on annotation field. cc @jasonliu747

noted, thanks.
