### ISSUE TITLE
REQUEST: New membership for buptcozy

### ISSUE THREAD

**Issue by buptcozy** [koordinator-sh/koordinator#539]
### GitHub Username

@buptcozy

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@eahydra

### Sponsor 2

@jasonliu747

### List of contributions to the Koordinator project

issues:
https://github.com/koordinator-sh/koordinator/issues/321
https://github.com/koordinator-sh/koordinator/issues/330
https://github.com/koordinator-sh/koordinator/issues/396

pr:
https://github.com/koordinator-sh/koordinator/pull/322
https://github.com/koordinator-sh/koordinator/pull/333
https://github.com/koordinator-sh/koordinator/pull/398

**Comment by eahydra** [comment]
![image](https://user-images.githubusercontent.com/832246/186846593-c29f3c25-4a1b-494e-89e3-1a470195cd34.png)

**Comment by eahydra** [comment]
+1  🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀🚀

**Comment by jasonliu747** [comment]
+1
![image](https://user-images.githubusercontent.com/24452340/186852396-f5764173-21dc-46ff-a495-b4a04953b907.png)

**Comment by hormes** [comment]
I have sent a invitation, please check.
