### ISSUE TITLE
[question] in elasticquota plugin，is the method syncHandler()  update quota cr too frequently?

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#657]
**What happened:**
if the patch operation takes 20ms,  the apiserver need to add 50 times/s overhead？

**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by xulinfei1996** [comment]
https://github.com/koordinator-sh/koordinator/pull/681/files this pr is to optimize some logics of the syncHandler, and SyncHandlerCycle can be a configuration if in need in the future.
