### ISSUE TITLE
[BUG] koordlet throws `Can't get node` error during initialization

### ISSUE THREAD

**Issue by ryan2333** [koordinator-sh/koordinator#664]
**What happened**:
I0928 10:38:13.629577   57236 feature_gate.go:245] feature gates: &{map[Accelerators:true AllAlpha:true AuditEvents:true AuditEventsHTTPHandler:true BECPUEvict:true BECPUSuppress:true BECgroupReconcile:true BEMemoryEvict:true CPUBurst:true CgroupReconcile:true RdtResctrl:true]}
I0928 10:38:13.629695   57236 feature_gate.go:245] feature gates: &{map[AllAlpha:true CPUSetAllocator:true GPUEnvInject:true GroupIdentity:true]}
I0928 10:38:13.629859   57236 main.go:64] Setting up client for koordlet
I0928 10:38:13.630049   57236 koordlet.go:75] NODE_NAME is 10.202.243.24,start time 1.664332693e+09
I0928 10:38:13.630075   57236 koordlet.go:78] sysconf: &{CgroupRootDir:/host-cgroup/ CgroupKubePath:kubepods/ SysRootDir:/host-sys/ SysFSRootDir:/host-sys-fs/ ProcRootDir:/proc/ VarRunRootDir:/host-var-run/ NodeNameOverride: RuntimeHooksConfigDir:/host-etc-hookserver/ ContainerdEndPoint: DockerEndPoint:},agentMode:dsMode
I0928 10:38:13.630110   57236 koordlet.go:79] kernel version INFO : {IsAnolisOS:false}
I0928 10:38:13.706803   57236 koordlet.go:106] can not detect cgroup driver from 'kubepods' cgroup name
E0928 10:38:13.706835   57236 koordlet.go:110] Can't get node
I0928 10:38:23.707231   57236 koordlet.go:106] can not detect cgroup driver from 'kubepods' cgroup name
E0928 10:38:23.707273   57236 koordlet.go:110] Can't get node
I0928 10:38:33.707522   57236 koordlet.go:106] can not detect cgroup driver from 'kubepods' cgroup name
E0928 10:38:33.707556   57236 koordlet.go:110] Can't get node 5.15.2-1.el7.elrepo.x86_64
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version: v0.7.0
- Kubernetes version (use `kubectl version`): 
  -  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:59:18Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
- Install details (e.g. helm install args): helm install koordinator nexus/koordinator --version 0.7.0
- Others:
   - nexus/koordinator: download the koordinator charts from github, package them with helm packages, and upload them to the private nexus repository
   - cgroupDriver: systemd

**Comment by ryan2333** [comment]
已收到，谢谢!!

**Comment by zwzhang0107** [comment]
could you please show more details about pod cgroup info, e.g. the content of dir
```
ls /sys/fs/cgroup/cpu/
```

**Comment by ryan2333** [comment]
[root@kubenode-243024 ~]# ls /sys/fs/cgroup/cpu/
cgroup.clone_children  cpuacct.usage             cpuacct.usage_percpu_user  cpu.cfs_period_us  cpu.rt_runtime_us  kubepods.slice     tasks
cgroup.procs           cpuacct.usage_all         cpuacct.usage_sys          cpu.cfs_quota_us   cpu.shares         notify_on_release  user.slice
cgroup.sane_behavior   cpuacct.usage_percpu      cpuacct.usage_user         cpu.idle           cpu.stat           release_agent
cpuacct.stat           cpuacct.usage_percpu_sys  cpu.cfs_burst_us           cpu.rt_period_us   kubepods           system.slice

NodeInfo: 
containerd/docker version: Docker version 20.10.12, build 459d0df
operate system version: CentOS Linux release 7.5.1804 (Core)
kernel version: 5.15.2-1.el7.elrepo.x86_64
cgroup driver: systemd

**Comment by zwzhang0107** [comment]
i see.
seems the systemd dir(`kubepods.slice`) and cgroupfs dir (`kubepods`) both exists, which makes koordlet confused. 
maybe the kubelet cgroup config has been changed before, you can try to remove the unused dir by `rmdir /sys/fs/cgroup/cpu/kubepod/`(also memory, blkio dir for safety) and reinstall koordlet.
if this works, then we can find a better way to make koordlet understand the cgroup driver.

**Comment by zwzhang0107** [comment]
> i see. seems the systemd dir(`kubepods.slice`) and cgroupfs dir (`kubepods`) both exists, which makes koordlet confused. maybe the kubelet cgroup config has been changed before, you can try to remove the unused dir by `rmdir /sys/fs/cgroup/cpu/kubepod/`(also memory, blkio dir for safety) and reinstall koordlet. if this works, then we can find a better way to make koordlet understand the cgroup driver.

hi, is this workable for you?

**Comment by zwForrest** [comment]
> > i see. seems the systemd dir(`kubepods.slice`) and cgroupfs dir (`kubepods`) both exists, which makes koordlet confused. maybe the kubelet cgroup config has been changed before, you can try to remove the unused dir by `rmdir /sys/fs/cgroup/cpu/kubepod/`(also memory, blkio dir for safety) and reinstall koordlet. if this works, then we can find a better way to make koordlet understand the cgroup driver.
> 
> hi, is this workable for you? @ryan2333

@zwzhang0107  this works for me.

**Comment by zwForrest** [comment]
> i see. seems the systemd dir(`kubepods.slice`) and cgroupfs dir (`kubepods`) both exists, which makes koordlet confused. maybe the kubelet cgroup config has been changed before, you can try to remove the unused dir by `rmdir /sys/fs/cgroup/cpu/kubepod/`(also memory, blkio dir for safety) and reinstall koordlet. if this works, then we can find a better way to make koordlet understand the cgroup driver.

this works for me.
