### ISSUE TITLE
[BUG] cpu.cfs_quota_us cannot be less than 1000, should be max(1000, batch-cpu/1000*cfs_period)

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#696]
**What happened**:
![image](https://user-images.githubusercontent.com/101699117/195355374-ae59003d-da66-4fc7-948c-9a302763963f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by lengrongfu** [comment]
Hi, I am a newbie, can I fix this?

**Comment by lengrongfu** [comment]
Is this a bug in the program? @zwzhang0107

**Comment by hormes** [comment]
very welcome

> Hi, I am a newbie, can I fix this?

**Comment by zwzhang0107** [comment]
#774
