### ISSUE TITLE
[BUG]quota runtime caculate error

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#697]
**What happened**:
if my request cpu is 100m,  after quota caculate, the rumtime is 1 (1000m), why is not 100m?  

**Anything else we need to know?**:
There is a loss of precision
fsc.quotaTree[resKey].updateRequest(quotaInfo.Name, reqLimitPerKey.Value())
maybe reqLimitPerKey.MilliValue() is valied

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by xulinfei1996** [comment]
https://github.com/koordinator-sh/koordinator/pull/675 this pr is to fix the runtime calculate error when the quota's request is  smaller than 1 core.

**Comment by fjding** [comment]
perfect
