### ISSUE TITLE
[question] kubelet start error when Specify parameters --docker-endpoint

### ISSUE THREAD

**Issue by leason00** [koordinator-sh/koordinator#711]
**What happened:**
kubelet start error:
Oct 18 16:23:06 qabb-qa-k8s-qa-iaas-u01-node1 kubelet[889296]: I1018 16:23:06.894635  889296 container_manager_linux.go:306] Creating device plugin manager: true
Oct 18 16:23:06 qabb-qa-k8s-qa-iaas-u01-node1 kubelet[889296]: I1018 16:23:06.894651  889296 manager.go:133] Creating Device Plugin manager at /var/lib/kubelet/device-plugins/kubelet.sock
Oct 18 16:23:06 qabb-qa-k8s-qa-iaas-u01-node1 kubelet[889296]: I1018 16:23:06.894731  889296 client.go:75] Connecting to docker on /var/run/koord-runtimeproxy/runtimeproxy.sock
Oct 18 16:23:06 qabb-qa-k8s-qa-iaas-u01-node1 kubelet[889296]: F1018 16:23:06.894741  889296 client.go:90] Couldn't connect to docker: unable to parse docker host `/var/run/koord-runtimeproxy/runtimeproxy.sock`

koord-runtime-proxy start log：
 Oct 18 16:18:04 qabb-qa-k8s-qa-iaas-u01-node1 koord-runtime-proxy[881037]: I1018 16:18:04.422563  881037 config_manager.go:101] add new watching file /etc/runtime/hookserver.d/koordlet.json with inode number 34616742
Oct 18 16:18:04 qabb-qa-k8s-qa-iaas-u01-node1 koord-runtime-proxy[881037]: I1018 16:18:04.423804  881037 config_manager.go:175] update config for /etc/runtime/hookserver.d/koordlet.json &{/var/run/koordlet//koordlet.sock Ignore [PreUpdateContainerResources PreRunPodSandbox PreCreateContainer]}

Start command：
/usr/local/bin/kubelet  $KUBELET_ARGS --docker-endpoint=/var/run/koord-runtimeproxy/runtimeproxy.sock

koord-runtime-proxy --backend-runtime-mode=Docker --remote-runtime-service-endpoint=/var/run/docker.sock
**What you expected to happen:**
no error
**Environment:**

- Koordinator version: - v0.7.0
- Kubernetes version (use kubectl version): v1.18.19
- docker/containerd version: docker 18.09.9
- OS (e.g: cat /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. uname -a): Linux qabb-qa-k8s-qa-iaas-u01-node1 4.19.0-6.el7.ucloud.x86_64 #1 SMP Wed Feb 12 07:32:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by hormes** [comment]
Try to use the following way to start kubelet

> /usr/local/bin/kubelet $KUBELET_ARGS --docker-endpoint=unix:///var/run/koord-runtimeproxy/runtimeproxy.sock

**Comment by leason00** [comment]
> Try to use the following way to start kubelet
> 
> > /usr/local/bin/kubelet $KUBELET_ARGS --docker-endpoint=unix:///var/run/koord-runtimeproxy/runtimeproxy.sock

It works， thx！

**Comment by leason00** [comment]
@hormes https://github.com/koordinator-sh/website/pull/87 Correction document
