### ISSUE TITLE
[proposal] Add more node usage type in NodeMetric

### ISSUE THREAD

**Issue by zwForrest** [koordinator-sh/koordinator#723]
**What is your proposal**:
NodeMetric cr has more time period node usage metric, eg 1h/1d.
 
**Why is this needed**:
In this way, more node usage information can be referred to when scheduling or descheduling.

**Is there a suggested solution, if so, please add it**:
```
// NodeMetricStatus defines the observed state of NodeMetric
type NodeMetricStatus struct {
	// UpdateTime is the last time this NodeMetric was updated.
	UpdateTime *metav1.Time `json:"updateTime,omitempty"`

	// NodeMetric contains the metrics for this node.
	NodeMetric *NodeMetricInfo `json:"nodeMetric,omitempty"`

	// PodsMetric contains the metrics for pods belong to this node.
	PodsMetric []*PodMetricInfo `json:"podsMetric,omitempty"`
}
```
can NodeMetric be changed to slice? Object NodeMetricInfo adds a node usage type field, and each type may have its own update interval.

**Comment by saintube** [comment]
hi @zwForrest , please refers to #856
