### ISSUE TITLE
[proposal] KoordRuntimeProxy support both Fail/Ignore FailurePolicyType

### ISSUE THREAD

**Issue by honpey** [koordinator-sh/koordinator#733]
**What is your proposal**:
Currently,  KoordRuntimeProxy supports two kinds FailurePolicyType, including Fail & Ignore.
but only Ignore policy is supported under containerd scenario while only Fail is supported under docker scenario.
KoordRuntimeProxy should support both Fail/Ignore under both containerd and docker scenario.

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by FillZpp** [comment]
Supported feature.
/close
