### ISSUE TITLE
[question]the elasticquota plugin start when new plugin, master and slave  scheduler update quota at the same time?

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#762]
**What happened:**
The elasticquota plugin background thread loop will start when New plugin,  but the New Plugin is before leader election.
if scheduler has to pod instance (master and slave), the master and slave while update quota at the same time ?

**What you expected to happen:**

**Environment:**

- Koordinator version: - v0.6.2
- Kubernetes version (use kubectl version): v1.22.5
- docker/containerd version: containerd 1.5.0
- OS (e.g: cat /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. uname -a): Linux 5.10.112-11.al8.x86_64 #1 SMP Tue May 24 16:05:50 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

**Anything else we need to know:**

**Comment by eahydra** [comment]
Thanks for feedback on this issue. We are solving this problem.
