### ISSUE TITLE
[question]Does  the community have any plans to improve the performance of offline scheduling？

### ISSUE THREAD

**Issue by mrningyang** [koordinator-sh/koordinator#768]
We all know that offline tasks put a lot of pressure on the scheduler，Does  the community have any plans to improve the performance of offline scheduling？

**Comment by eahydra** [comment]
What types of workloads does "offline task" refer to? This word is relatively abstract. At present, there are some scenarios in K8s that complete some jobs based on pods, so it is considered to optimize the scheduling throughput and delay of pods in the future. However, similar to task scheduling in some Hadoop scenarios, it may not necessarily be necessary to complete the scheduling in the koordinator scheduler, but consider coordinating with the koordinator scheduler to complete the scheduling requirements at the resource level. See #712 for this
