### ISSUE TITLE
[BUG]elasticquota when remove node A,  then add node A come back,  the  totalResource will not update

### ISSUE THREAD

**Issue by fjding** [koordinator-sh/koordinator#771]
**What happened**:
elasticquota when remove node A,  then add node A come back,  the  totalResource will not update

caused by:
In OnNodeDelete function not delete node from nodeResourceMapLock

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by eahydra** [comment]
Hi @fjding, thanks for your feedback. as we talked, waiting for your fix PR.
