### ISSUE TITLE
REQUEST: New membership for Mr-Linus

### ISSUE THREAD

**Issue by Mr-Linus** [koordinator-sh/koordinator#82]
### GitHub Username

@Mr-Linus

### Requirements

- [X] I have reviewed the [community membership guidelines](https://github.com/koordinator-sh/koordinator/blob/main/docs/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I am actively contributing to 1 or more Koordinator subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Koordinator GitHub organizations (excluding the contributor-playground)
- [ ] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Sponsor 1

@hormes

### Sponsor 2

@jasonliu747

### List of contributions to the Koordinator project

- PRs Reviewed / authored
[PR38](https://github.com/koordinator-sh/koordinator/pull/38)
[PR42](https://github.com/koordinator-sh/koordinator/pull/42)
[PR51](https://github.com/koordinator-sh/koordinator/pull/51)

- Issues responded to
[Issues50](https://github.com/koordinator-sh/koordinator/issues/50)

- Subprojects  I am involved with
koordinator-sh/koordinator

**Comment by jasonliu747** [comment]
+1

**Comment by hormes** [comment]
+1

**Comment by hormes** [comment]
Welcome to the Koordinator family and look forward to your contributions.

**Comment by jasonliu747** [comment]
@Mr-Linus 
![image](https://user-images.githubusercontent.com/24452340/164134198-906ca2fb-f7b5-4557-a022-cc8a2cd73e5e.png)
