### ISSUE TITLE
[proposal] elastic quota 支持对集群的不同节点组做配置

### ISSUE THREAD

**Issue by LarryZhangy** [koordinator-sh/koordinator#827]
**What is your proposal**:
一个k8s集群存在不同的节点组：
1）一批节点支持A100 GPU，另一批节点支持A40 GPU
2）一个集群的节点来自不同的zone，每个zone的网络环境，依赖的服务能力不一样
3）一个集群的节点由x86 + ARM组成，期望能区分不同节点

期望elastic quota能对这不同的节点组做资源配额管理，如elastic quota group a，配置使用来自zone a的100 c，来自zone b的10c。

**Why is this needed**:
集群资源是异构的，期望在配置配额时能区别一下。

**Is there a suggested solution, if so, please add it**:
是否能和kueue结合使用？

**Comment by hormes** [comment]
你有没有总体的方案设计的思路，可以 share 一下？
