### ISSUE TITLE
[proposal] compatible with k8s descheduler configuration

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#828]
**What is your proposal**:

Currently, users configure descheduler policies through the k8s descheduler configuration with version `descheduler/v1alpha1`. We need to be compatible with this configuration in koord-descheduler to facilitate smooth migration to koord-descheduler

**Comment by complone** [comment]
I'll do some research and start implementing the proposal when I'm familiar with it

**Comment by eahydra** [comment]
> I'll do some research and start implementing the proposal when I'm familiar with it

Hi, thanks for your attention to this issue. This issue is currently supported by #1044
