### ISSUE TITLE
[feature request] allow extended resources to be over-committed

### ISSUE THREAD

**Issue by jasonliu747** [koordinator-sh/koordinator#83]
**What would you like to be added**:
According to this PR https://github.com/kubernetes/kubernetes/pull/48922, extend resources could not be over-committed. Is it possible to overcommit `batch-cpu` and `batch-memory` in Koordinator?

**Why is this needed**:

**Comment by zwzhang0107** [comment]
A structured "protocol" is needed in annotation for multiple containers.

**Comment by zwzhang0107** [comment]
related kubernetes issue https://github.com/kubernetes/kubernetes/pull/48922

**Comment by jasonliu747** [comment]
another related issue: https://github.com/kubernetes/kubernetes/issues/110536

**Comment by zwzhang0107** [comment]
consider using kubernetes.io/koord-bach-cpu, kubernetes.io/koord-bach-memory as extended-resource for overcommitment.

**Comment by zwzhang0107** [comment]
- [ ] [proposal of refactor extended resource with koordinator.kubernetes.io namespace](https://github.com/koordinator-sh/koordinator/pull/350)
- [ ] koord-manager updates extended resource on node with new format
- [ ] koord-scheduler supports pod scheduling with old format exetened resource
