### ISSUE TITLE
[proposal] Improve the readability of the PreFilter error message of the DeviceShare plugin

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#840]
**What is your proposal**:

When I created a Pod with resource requests `kubernetes.io/gpu-core=50`, `kubernetes.io/gpu-memory=2Gi`  and  `kubernetes.io/gpu-memory-ratio=50`, I got the PreFilter error like this: `request is not valid, current combination: 010001000` .

This error message cannot be understood intuitively.

**Why is this needed**:

make sense of error messages.

**Is there a suggested solution, if so, please add it**:

**Comment by eahydra** [comment]
@jasonliu747

**Comment by jasonliu747** [comment]
Totally agree with you. Will improve readability ASAP.
/assign
