### ISSUE TITLE
[proposal] New repo: External Metrics Advisor for better extensibility

### ISSUE THREAD

**Issue by songtao98** [koordinator-sh/koordinator#842]
**What is your proposal**:
Enlighted by encapsulating the eBPF program of the CPU schedule latency collector into a separate tool, we noticed that Koordinator may develop a new sub-repo named External Metrics Advisor. This sub-project covers many underlying kernel metrics collection tools implemented with eBPF technology or others, and expands Koordinator's ability to collect metrics in the form of plug-ins. 

**Why is this needed**:
The eBPF technology itself is in a stage of rapid development, and it has also attracted a lot of attention from kernel workers. Koordinator can use such sub-projects as a cutting edge for exploration in this regard.
Furthermore, the sub-project can be connected to mature third-party monitoring tools such as the SysAK project of the OpenAnolis community. 
Therefore, the proposal aims to decouple the ability of Koordinator to collect the underlying indicators of the kernel, and leave the professional work to professional people.

**Is there a suggested solution, if so, please add it**:
We can provide the community with the implementation of the first eBPF monitoring tool, which is the CPU scheduling latency tool implemented according to issue #837 .

**Comment by zwzhang0107** [comment]
interference detection and solving includes several steps: metrics collection, metrics analysis and strategy execution.
the new sub-repo can do more than just metrics collection, but also analysis. Maybe we can name this repo as `koordetector`.
The special part of metrics in `koordetctor` is that it provides advanced metrics like `CPU schedule latency`, `memory allocation latency`, `cache miss`, which are related to underlying OS. 
`koordetctor` can  and let `koordlet` do the strategy.

The responsibilities of `koordetector` and `koordlet` are: 
- koordetector: metrics collection and analysis, and draws a conclusion about whether some pods get interference
- koordlet: receive the result of interference detect from `koordetector `and commit strategy(resource suppress/evict)

**Comment by jasonliu747** [comment]
are we planning to migrate all the current metrics collecting logics into `koordector`?

**Comment by songtao98** [comment]
> are we planning to migrate all the current metrics collecting logics into `koordector`?

Basically `koordector` should better just focus on **advanced metrics** such as CPU schedule latency. Those metrics either need to be collected by advanced methods like eBPF, or are more related to underlying OS. Thus I suggest not do migration for current metrics.

**Comment by zwzhang0107** [comment]
koordetector has been created
