### ISSUE TITLE
[proposal] more detailed data is need in NodeMetric for scheduler/descheduler 

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#856]
**What is your proposal**:
Add more aggregate data in nodeMetricUsage (e.g. p90, p99).

**Why is this needed**:
Scheduler/De-scheduler need more data about resource usage for load-aware scheduling.
The short/mid-term (seconds, minutes) usage info should comes from koordlet.
The long-term (hours, even days) usage info should comes from other sources(e.g. prometheus). (FUTURE WORK)

**Is there a suggested solution, if so, please add it**:

**Comment by FillZpp** [comment]
fixed by #861

/close
