### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Sword-zhj** [koordinator-sh/koordinator#865]
**What happened**:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/32220271/206167490-51c2229b-4910-4825-b96e-8bb9c96bad67.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/32220271/206167489-13453a07-7263-4b67-9ab7-c7ee40f03da8.png">

**What you expected to happen**:
pod-demo-0 should be scheduled at the same node with reservation-demo?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by saintube** [comment]
@Sword-zhj hi, could you please add more information about the reservation and corresponding pod object, and paste the related logs/configs of the koord-scheduler?
