### ISSUE TITLE
[BUG]orphan pod groups should be cleaned when scheduler restart

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#867]
**What happened**:
When pod was deleted during scheduler's restarting, podDelete event will not be triggered.
So the podgroup cr will continue exist although the pod has been deleted.

**What you expected to happen**:
When scheduler restarts, maybe we need to clean orphan pod groups.
**How to reproduce it (as minimally and precisely as possible)**:
First create a gang job
Then kill the scheduler
Then delete the job
Then restart the scheduler
The podgroup will still exists
```
$ k get po
NAME       READY   STATUS    RESTARTS   AGE
pi-ghcsq   1/1     Running   0          6m33s
pi-hg4hv   1/1     Running   0          6m33s
pi-vqvkh   1/1     Running   0          6m33s
$ k get pg
NAME       AGE
gang-job   6m36s
// Now kill the scheduler

$ k delete job pi
job.batch "pi" deleted
$ k get po
NAME       READY   STATUS        RESTARTS   AGE
pi-ghcsq   1/1     Terminating   0          7m26s
pi-hg4hv   1/1     Terminating   0          7m26s
pi-vqvkh   1/1     Terminating   0          7m26s
$ k get po
No resources found in default namespace.
// Now restart the sheduler
$ k get pg
NAME       AGE
gang-job   7m34s
```

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by buptcozy** [comment]
Thanks for reporting the issue. I think this is indeed a problem. we will try fix it.

**Comment by eahydra** [comment]
PodGroups are now no longer created if the Pod declares the gang spec using the annotation
