### ISSUE TITLE
[BUG]deadlock when schedule multi-gang-group

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#872]
**What happened**:
if there are pod group A,B,C,D in the cluster, A and B are a group while C and D are a group.
if the pod groups are scheduled in the following order: A C B D, a deadlock may happen when pod group A and C occupy all resource is the cluster.
**What you expected to happen**:
when pod group B find that the resource is not enough, it can reject pod group A so that pod group C and D can bind.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:
- Kubernetes version (use `kubectl version`):
- Install details (e.g. helm install args):
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version:
  - OS version:
  - Kernal version:
  - Cgroup driver: cgroupfs/systemd
- Others:

**Comment by eahydra** [comment]
Thanks for reporting the issue. I think this is indeed a problem. It is necessary to consider scheduling according to the same Group sorting, and reject all WaitingPods under the same Group when encountering a failure in strict mode

**Comment by KunWuLuan** [comment]
Another case, assume we have 2 pod groups A and B in 1 gang group. Total pods of A is more than min available pod. For simply, we just say the total is 10 and the min-available is 3 and the min-available. Assume all resource requests are same and the cluster can schedule 5 pods.
In this situation, gang A can assume 5 pods and B can assume 0 pods, which will made the schedule fail.

**Comment by eahydra** [comment]
cc @buptcozy

**Comment by buptcozy** [comment]
> Another case, assume we have 2 pod groups A and B in 1 gang group. Total pods of A is more than min available pod. For simply, we just say the total is 10 and the min-available is 3 and the min-available. Assume all resource requests are same and the cluster can schedule 5 pods. In this situation, gang A can assume 5 pods and B can assume 0 pods, which will made the schedule fail.

for now,  the behaviour is just like what you said. we will try to impriove it.

**Comment by eahydra** [comment]
> For case 1, we can modify the less function to make gang of the same group adjacent, and when the one pod enter postfilter, we reject all pods in one gang group to avoid the dead lock.
> 
> ```
> 	group1, _ := cs.pgMgr.GetGroupId(podInfo1.Pod)
> 	group2, _ := cs.pgMgr.GetGroupId(podInfo1.Pod)
> 	compare := bytes.Compare(group1, group2)
> 	if compare != 0 {
> 		return compare < 0
> 	}
> ```
> 
> For case 2, maybe we can modify the less function similarly. In less function, if we find waiting pods of gang A has met the requirements, we make gang A behind gang B which doesn't meet the requirements. Like this:
> 
> ```
> 	isgang1satisfied := cs.pgMgr.IsGangMinSatisfied(podInfo1.Pod)
> 	isgang2satisfied := cs.pgMgr.IsGangMinSatisfied(podInfo2.Pod)
> 	if isgang1satisfied != isgang2satisfied {
> 		return !isgang1satisfied
> 	}
> ```
> 
> @eahydra @buptcozy How do you think?

Looks all right, move on!
