### ISSUE TITLE
[BUG] koordlet pod always CrashLoopBackOff with a painc error

### ISSUE THREAD

**Issue by chclass** [koordinator-sh/koordinator#89]
**What happened**:
koordlet dosen't work when i install it with  helm

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- App version:v0.2.0
- Kubernetes version (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
- Install details (e.g. helm install args):
- Others: local install wtih minikube
i got the lscpu content on my node as follows

# lscpu -e=CPU,NODE,SOCKET,CORE,CACHE,ONLINE
CPU NODE SOCKET CORE CACHE ONLINE
  0    -      0    0 -        yes
  1    -      0    1 -        yes
  2    -      0    2 -        yes
  3    -      0    3 -        yes

**Comment by zwzhang0107** [comment]
running koordlet is not supported on mini-kube on darwin yet, you can try with a real k8s cluster environment.
