### ISSUE TITLE
[BUG] 设置runtime-proxy之后，容器cgroup目录不在kubepods下

### ISSUE THREAD

**Issue by yuexian1234** [koordinator-sh/koordinator#899]
**What happened**:
设置runtime-proxy之后，容器cgroup目录不在kubepods下，但pod层还是在kubepods
**What you expected to happen**:
容器cgroup在kubepods下
**How to reproduce it (as minimally and precisely as possible)**:
前提： docker kubelet cgroup driver都是cgroupfs
1. 启动proxy  ./koord-runtime-proxy --backend-runtime-mode=Docker --remote-runtime-service-endpoint=/var/run/docker.sock
2. kubelet设置参数 --docker-endpoint=unix:///var/run/koord-runtimeproxy/runtimeproxy.sock
3 创建任意pod， pid=`docker inspect $xx --format='{{.State.Pid}}'` ;cat /proc/$pid/cgroup
4 发现pod的cgroup目录不在kubepods层级
**Anything else we need to know?**:

**Environment**:
- App version:  
   Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", 
  GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", 
  GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", 
  GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", 
  GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

- Install details (e.g. helm install args):
   helm repo add koordinator-sh https://koordinator-sh.github.io/charts/
   helm install koordinator koordinator-sh/koordinator --version v1.0.0
- Node environment (for koordlet/runtime-proxy issue):
  - Containerd/Docker version: 
     docker: 19.03.14-sealer
     containerd: v1.3.9
     runc : 1.0.0-rc10
  - OS version: debian11
  - Kernal version: 5.10.0
  - Cgroup driver: cgroupfs
- Others:

**Comment by yuexian1234** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/14341344/209112814-b2f983be-20eb-49c5-947b-96e64ddc38a6.png">

去除runtime-proxy之后，新建的pod，容器cgroup层级在kubepod下

**Comment by saintube** [comment]
注意到您的 OS 版本是 Debian 11 (kernel 5.10)，您当前节点环境是否启用了 cgroups v2？

```bash
$ ls /sys/fs/cgroup
$ stat -fc %T /sys/fs/cgroup/
```

**Comment by yuexian1234** [comment]
> ```shell
> stat -fc %T /sys/fs/cgroup/
> ```

root@debian3:~# ls /sys/fs/cgroup
blkio  cpu  cpu,cpuacct  cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls  net_cls,net_prio	net_prio  perf_event  pids  rdma  systemd  unified
root@debian3:~# stat -fc %T /sys/fs/cgroup/
tmpfs

用的就是cgroup v1我特意调整过grub配置
