### ISSUE TITLE
[proposal] Call PreStop hook before a Pod is terminated 

### ISSUE THREAD

**Issue by czhenly** [koordinator-sh/koordinator#907]
**Why is this needed**:
For some offline Pods, there is a daemon process in the container. We want the daemon to do some cleanup, so the daemon expects to receive `SIGTERM` before the container terminates, so we want to use the `prestop` hook to send `SIGTERM` to the daemon.

**Comment by hormes** [comment]
@FillZpp Please evaluate this functional

**Comment by FillZpp** [comment]
@czhenly So you expect the daemon process in Pod to get `SIGTERM` before Pod terminating or container terminating?

**Comment by czhenly** [comment]
> @czhenly So you expect the daemon process in Pod to get SIGTERM before Pod terminating or container terminating?

Yeah, we want to send `SIGTERM`  to daemon process by `prestop` hook or other way. Now we send the SIGTERM signal through the prestop hook on K8s, but this way doesn't support koordinator-based
