### ISSUE TITLE
[proposal] change default value allocateOnce in reservation to true

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#934]
Can we change default value of allocateOnce in reservation to true?
Do you have many scenarios where allocateOnce needs to be set to false？

**What is your proposal**:

**Why is this needed**:

**Is there a suggested solution, if so, please add it**:

**Comment by eahydra** [comment]
@KunWuLuan This field can be modified as long as compatibility is maintained.

Discuss with @FillZpp , this field can be changed to bool pointer, and add a default parameter of the Reservation plugin to specify the default behavior of allocateOnce, and then check  if allocateOnce is nil in the code, execute according to the configured behavior.
