### ISSUE TITLE
[proposal] support fastfail for gang and multiple types of permit policies, correct scheduled semantics in coscheduling

### ISSUE THREAD

**Issue by KunWuLuan** [koordinator-sh/koordinator#940]
**FastFail**
In strict mode, we mark the gang failed when any pod of the gang can''t be scheduled. Pod in this gang can''t be scheduled until all pods in this gang has come.

The process of marking failure can be optimized as follows:
- When the total num of the pods in a pod group is larger than min-available, the number of scheduled pod can still meet the min-available requirement even if some pods fail to schedule. We can count the number of remaining pods that have not been scheduled and the number of pods that have failed to be scheduled to determine whether the podgroup can meet the min available requirements. If not, we mark the pod group failed.
- When any pod group in a gang group is in the status of schedule cycle invalid, any successful schedule in this gang group is useless. Only the pods in the gang group where all gangs are available should pass the prefilter.

**Matching Policy**

Koordinator support only `OnceResourceSatisfied` mode. Sometimes some pods in the pod group failed for some reasons, and we hope that the subsequently reconstructed Pod will still be constrained by the gang semantics. So we think that the logic to determine whether gang is satisfied can be expanded to allow users to freely choose which logic to use.

- For GPU topology, all my tasks need to be scheduled at the same time to ensure the best performance, so I hope that gang can only be satisfied when the number of pods waiting on permit is larger than the min-available.
- For task of elastic training, the new workers'' arrival is random. So I hope the gang can be satisfied when the total number of the running pods and waiting pods is large than the min-available. 
- Sometimes in elastic training, some workers complete earlier than the others, and the new workers should start to training at its arrival. So I hope the gang can be satisfied when the total number of the running pods, the succeed pods and waiting pods is large than the min-available. 
- In some specific scenarios, the completed task Pod may not exist due to node recycling. At this time, it is impossible to count the number of completed tasks. In this case, OnceResourceSatisfied can be used.

**Scheduled Semantics in Status**

I think the Scheduled attribute in the status means how many pods have been scheduled, not how many existing pods have been scheduled. And the implementation in koordinator can make patch the wrong status on the pod groups because the patch are requests from multiple goroutines. I think the status of pod groups should be updated in stead of patched.

**Comment by buptcozy** [comment]
“We can count the number of remaining pods that have not been scheduled and the number of pods that have failed to be scheduled to determine whether the podgroup can meet the min available requirements”

generally，all pods in a gang are Isomorphic, so one pod schedule's fail event can lead the infer that other pods may fail to schedule too.

**Comment by KunWuLuan** [comment]
Now that we have recorded the number of Pods in the pod group through the children map at runtime, we can achieve a better performance. Especially when the total number of pods in a pod group is much larger than the min available.
