### ISSUE TITLE
[proposal] memory.limit maybe too late to set for BE pods with batch-memory limit when running without runtime-proxy

### ISSUE THREAD

**Issue by zwzhang0107** [koordinator-sh/koordinator#954]
**What is your proposal**:
When running without runtime-proxy, `memory.limit` of BE pods are set async by koordlet.
Step1: koordlet get pods from kubelet.
Step2: koordlet set `memory.limit`

Although we have working hard to improve the efficiency of step1, it is still possible that pod may already consume memory greater than batch-memory-limit before koordlet finish the cgroup writing.

Then, koordlet will got the "device busy" error, and the memory usage of pod may out of control.

![image](https://user-images.githubusercontent.com/101699117/212065373-deefc877-d6b4-494f-9922-70ad5f91f52d.png)

![image](https://user-images.githubusercontent.com/101699117/212068157-5eb4986c-ff90-4ac3-92cb-ef436ef85a3c.png)

 Since there will always be some latency on step1, how about we extend the container preparing time on purpose. So that koordlet can set the memory.limit in time.

**Why is this needed**:
`runtime-proxy` may not deployed in every scenario, but batch-memory-limit must take effects.

**Is there a suggested solution, if so, please add it**:
- For those urgent memory-hungry workload, adding init container for pods (default=false) through webhook, which can only protect pod will not overused. This works for pods with single container.
  - This init container only finish when receive some signal from `koordlet`.
  - Or just add a container with `sleep Ns` command to solve the 99.99% problem.
  - Any more ideas?
- For pod with multi containers, we need to protect every container won't overused.
  - Any more ideas?

**Comment by LeoLiuYan** [comment]
In the suggested solution, how do we to distinguish `those urgent memory-hungry workload`?  

BTW,  when receive the inotify event, should we only update the changed pod other than list all pods from kubelet?

@zwzhang0107

**Comment by hormes** [comment]
The init container proposal is too heavy and affects the user's Pod spec. Is there a solution without hacking the user Pod spec?
