### ISSUE TITLE
[proposal] Support fine-grained CPU binding mechanism to improve QoS model

### ISSUE THREAD

**Issue by eahydra** [koordinator-sh/koordinator#96]
**What would you like to be added**:
It is necessary to support fine-grained CPU binding mechanisms to improve the QoS model defined by Koordinator: LSE and LSR. 

LSE and LSR simply require that cores must be bound and decide whether to share resources with other workloads.
LSE requires that the allocated CPU can only be used by a Pod and not shared with other workloads.
LSR binds logical cores on demand, but does not require strong isolation like LSE, allowing sharing with other offline workloads.

Considering different CPU architectures, such as Intel provides HT technology, under this technical mechanism, how different workloads bind logical cores will bring different runtime effects and resource allocation effects. Under the NUMA architecture, if the bound logical cores are unreasonable, cross-die access to memory will occur, which may have a catastrophic impact on latency-sensitive applications.

The CPU-bound scenarios I can think of,
- A Pod exclusively occupies N physical cores according to the amount of resource requests. 
- Pods of the same workload will require mutual exclusion in the physical core dimension similar to the Pod AnitAffinity mechanism.
- Pods of different workloads can be shared in the physical core dimension.
- Requires logic cores with optimal NUMA topology

**Why is this needed**:
Enhanced CPU allocation capability and improve QoS model

- [x] v0.5 #226
   - [x] v0.6 #354 
- [x] v0.6 #227
- [x] v0.6 #229 
    - [x] #232 
        - [x] #264  
        - [x] v0.6 #345 
    - [x] #233 
        - [x] #265  
            - [x] koordlet supports LSR
            - [x] koordlet supports CPU Shared Pool for LS, K8s Burstable and Guaranteed Pods（newly created）
            - [x] koordlet supports BE Shared Pool for BE, K8s BestEffort Pods 
            - [x] v0.6 #224
        - [x] v0.6 #346
    - [x] v0.6 #234 
- [x] v0.6 support Node CPU orchestration API
- [x]  v0.7 support kubelet reserved CPUs
- [ ] v0.8 #228
   - [ ] koordlet report complete NUMA Node information
   - [ ] koord-scheduler support NUMA Topology Alignment scheduling  
   - [ ] koord-scheduler support NUMA allocate strategy `DistributeEvenly`
- [x] support mainstream architecture, like Intel/AMD/ARM
- [ ] #230

**Comment by saintube** [comment]
related pr: https://github.com/kubernetes/enhancements/pull/3334

**Comment by eahydra** [comment]
We need to implement the CPU orchestration capabilities related to LSR and CPU Shared Pool first, and the logic compatible with the kubelet CPU Manager will be implemented in the next version.

Issues we need to address in v0.5:

- #226 
- #232 
- #234 
- #265 
   - [ ] koordlet supports LSR
   - [ ] koordlet supports CPU Shared Pool for LS, K8s Burstable and Guaranteed Pods（newly created）
   - [ ] koordlet supports BE Shared Pool for BE, K8s BestEffort Pods

**Comment by eahydra** [comment]
- #226 
   - [ ] #227 
   - [ ] support default CPUBindPolicy for LSR
- #234 
- #345
