### ISSUE TITLE
[proposal] koordlet should check if the cgroup exists before writing a cgroup file

### ISSUE THREAD

**Issue by saintube** [koordinator-sh/koordinator#972]
**What is your proposal**:

The koordlet should check if the cgroup directory exists before calling `os.WriteFile` to update a cgroup file. If the cgroup directory (of a pod or a container) does not exist, the koordlet should log more verbosely to avoid redundant messages.

**Why is this needed**:

Although the koordlet has tried its best avoiding to update a non-running pod/container's cgroup (e.g. by checking the pod phase and container statuses from the pod meta), the target cgroup files the koordlet wants to write still can be stale when the container is just terminated, especially for the containers which restart continuously.

**Is there a suggested solution, if so, please add it**:

**Comment by zwzhang0107** [comment]
![image](https://user-images.githubusercontent.com/101699117/215765793-566925eb-1495-400e-801c-7d6eed386c54.png)
these logs should be ignored

**Comment by zwzhang0107** [comment]
also check other files like the logs shows @saintube @Re-Grh

**Comment by zwzhang0107** [comment]
solved by https://github.com/koordinator-sh/koordinator/pull/984
